### ISSUE TITLE
All Logging needs a timestamp

### ISSUE THREAD

**Issue by rgamage** [aspnet/Extensions#1002]
Any logger implementation, in my opinion, needs to date/timestamp each entry.  Why does the default logger in .NET Core, in the year 2019, not have any date/timestamp associated with each log entry?  Am I missing something?

I'd like every Log.Information("my message") call to automatically prepend the current date and time.  Always.  Or at least by default.  Why is this not happening?

I have tried to implement Serilog, but its integration with the MEL is not great, and I've spent way too much time getting this to work locally in the debug console, on premises in an IIS server, and in Azure.  I need one simple logging solution that works for those three use cases, and I've spent weeks struggling with this.  Why?

I know I can add a timestamp manually to each log message, but that solution is repetitive and wasteful.

**Comment by glennc** [comment]
This is discussed and a PR put in here: https://github.com/aspnet/Logging/issues/483

In general though, you are likely to want more than the default logger implementations in production. So time spent on Serilog is not likely to be wasted depending on what sinks you want logs to go to. I am specifically thinking of things like a file logger here.

I'm going to close this, but feel free to re-open/keep discussing it if you want to talk about something more than what's happening in the other issue.
