### ISSUE TITLE
Evaluate obsolete APIs from 2.2 and consider removing them in 3.0.0

### ISSUE THREAD

**Issue by Eilon** [aspnet/Extensions#1025]
Here's everything marked obsolete in 'master' in this repo. Please use the links below to compare master and release/2.2 to see if this is a pre-existing obsolete message for a member that can now be deleted. For each item consider whether to log a bug because we will take an action, and then check the checkbox to mark it as done (even if there's no further action).

#### (1) src\Primitives\src\InplaceStringBuilder.cs
Links: <a href="https://github.com/aspnet/Extensions/blob/master/src/Primitives/src/InplaceStringBuilder.cs#L11">[master]</a> | <a href="https://github.com/aspnet/Extensions/blob/release/2.2/src/Primitives/src/InplaceStringBuilder.cs#L11">[release/2.2]</a>
[File a bug for this](https://github.com/aspnet/Extensions/issues/new?body=Remove%20this%20obsolete%20member%20in%20%5Bsrc%2FPrimitives%2Fsrc%2FInplaceStringBuilder.cs%5D%28https%3A%2F%2Fgithub.com%2Faspnet%2FExtensions%2Fblob%2Fmaster%2Fsrc%2FPrimitives%2Fsrc%2FInplaceStringBuilder.cs%23L11%29%3A%0D%0A%0D%0A%60%60%60c%23%0D%0A%20%20%20%20%5BObsolete%28%22This%20type%20is%20obsolete%20and%20will%20be%20removed%20in%20a%20future%20version.%22%29%5D%0D%0A%20%20%20%20public%20struct%20InplaceStringBuilder%0D%0A%20%20%20%20%7B%0D%0A%60%60%60%0D%0A%0D%0AAnd%20file%20a%20new%20issue%20in%20https%3A%2F%2Fgithub.com%2Faspnet%2FAnnouncements%2Fissues%2F%20if%20this%20is%20a%20notable%20breaking%20change.%0D%0A&labels=breaking-change&title=Remove%20obsolete%20member%20in%20src/Primitives/src/InplaceStringBuilder.cs&milestone=3.0.0-preview3)
* [x] I attest that I have taken appropriate action on this item

```c#
    [Obsolete("This type is obsolete and will be removed in a future version.")]
    public struct InplaceStringBuilder
    {
```

---

#### (2) src\Caching\Memory\src\MemoryCacheOptions.cs
Links: <a href="https://github.com/aspnet/Extensions/blob/master/src/Caching/Memory/src/MemoryCacheOptions.cs#L17">[master]</a> | <a href="https://github.com/aspnet/Extensions/blob/release/2.2/src/Caching/Memory/src/MemoryCacheOptions.cs#L17">[release/2.2]</a>
[File a bug for this](https://github.com/aspnet/Extensions/issues/new?body=Remove%20this%20obsolete%20member%20in%20%5Bsrc%2FCaching%2FMemory%2Fsrc%2FMemoryCacheOptions.cs%5D%28https%3A%2F%2Fgithub.com%2Faspnet%2FExtensions%2Fblob%2Fmaster%2Fsrc%2FCaching%2FMemory%2Fsrc%2FMemoryCacheOptions.cs%23L17%29%3A%0D%0A%0D%0A%60%60%60c%23%0D%0A%20%20%20%20%20%20%20%20%5BObsolete%28%22This%20is%20obsolete%20and%20will%20be%20removed%20in%20a%20future%20version.%22%29%5D%0D%0A%20%20%20%20%20%20%20%20public%20bool%20CompactOnMemoryPressure%20%7B%20get%3B%20set%3B%20%7D%0D%0A%0D%0A%60%60%60%0D%0A%0D%0AAnd%20file%20a%20new%20issue%20in%20https%3A%2F%2Fgithub.com%2Faspnet%2FAnnouncements%2Fissues%2F%20if%20this%20is%20a%20notable%20breaking%20change.%0D%0A&labels=breaking-change&title=Remove%20obsolete%20member%20in%20src/Caching/Memory/src/MemoryCacheOptions.cs&milestone=3.0.0-preview3)
* [x] I attest that I have taken appropriate action on this item

```c#
        [Obsolete("This is obsolete and will be removed in a future version.")]
        public bool CompactOnMemoryPressure { get; set; }

```

---

#### (3) src\Logging\Logging.Testing\src\Xunit\LoggedTestCase.cs
Links: <a href="https://github.com/aspnet/Extensions/blob/master/src/Logging/Logging.Testing/src/Xunit/LoggedTestCase.cs#L14">[master]</a> | <a href="https://github.com/aspnet/Extensions/blob/release/2.2/src/Logging/Logging.Testing/src/Xunit/LoggedTestCase.cs#L14">[release/2.2]</a>
[File a bug for this](https://github.com/aspnet/Extensions/issues/new?body=Remove%20this%20obsolete%20member%20in%20%5Bsrc%2FLogging%2FLogging.Testing%2Fsrc%2FXunit%2FLoggedTestCase.cs%5D%28https%3A%2F%2Fgithub.com%2Faspnet%2FExtensions%2Fblob%2Fmaster%2Fsrc%2FLogging%2FLogging.Testing%2Fsrc%2FXunit%2FLoggedTestCase.cs%23L14%29%3A%0D%0A%0D%0A%60%60%60c%23%0D%0A%20%20%20%20%20%20%20%20%5BObsolete%28%22Called%20by%20the%20de-serializer%3B%20should%20only%20be%20called%20by%20deriving%20classes%20for%20de-serialization%20purposes%22%29%5D%0D%0A%20%20%20%20%20%20%20%20public%20LoggedTestCase%28%29%20%3A%20base%28%29%0D%0A%20%20%20%20%20%20%20%20%7B%0D%0A%60%60%60%0D%0A%0D%0AAnd%20file%20a%20new%20issue%20in%20https%3A%2F%2Fgithub.com%2Faspnet%2FAnnouncements%2Fissues%2F%20if%20this%20is%20a%20notable%20breaking%20change.%0D%0A&labels=breaking-change&title=Remove%20obsolete%20member%20in%20src/Logging/Logging.Testing/src/Xunit/LoggedTestCase.cs&milestone=3.0.0-preview3)
* [x] I attest that I have taken appropriate action on this item

```c#
        [Obsolete("Called by the de-serializer; should only be called by deriving classes for de-serialization purposes")]
        public LoggedTestCase() : base()
        {
```

---

#### (4) src\Logging\Logging.Testing\src\Xunit\LoggedTheoryTestCase.cs
Links: <a href="https://github.com/aspnet/Extensions/blob/master/src/Logging/Logging.Testing/src/Xunit/LoggedTheoryTestCase.cs#L14">[master]</a> | <a href="https://github.com/aspnet/Extensions/blob/release/2.2/src/Logging/Logging.Testing/src/Xunit/LoggedTheoryTestCase.cs#L14">[release/2.2]</a>
[File a bug for this](https://github.com/aspnet/Extensions/issues/new?body=Remove%20this%20obsolete%20member%20in%20%5Bsrc%2FLogging%2FLogging.Testing%2Fsrc%2FXunit%2FLoggedTheoryTestCase.cs%5D%28https%3A%2F%2Fgithub.com%2Faspnet%2FExtensions%2Fblob%2Fmaster%2Fsrc%2FLogging%2FLogging.Testing%2Fsrc%2FXunit%2FLoggedTheoryTestCase.cs%23L14%29%3A%0D%0A%0D%0A%60%60%60c%23%0D%0A%20%20%20%20%20%20%20%20%5BObsolete%28%22Called%20by%20the%20de-serializer%3B%20should%20only%20be%20called%20by%20deriving%20classes%20for%20de-serialization%20purposes%22%29%5D%0D%0A%20%20%20%20%20%20%20%20public%20LoggedTheoryTestCase%28%29%20%3A%20base%28%29%0D%0A%20%20%20%20%20%20%20%20%7B%0D%0A%60%60%60%0D%0A%0D%0AAnd%20file%20a%20new%20issue%20in%20https%3A%2F%2Fgithub.com%2Faspnet%2FAnnouncements%2Fissues%2F%20if%20this%20is%20a%20notable%20breaking%20change.%0D%0A&labels=breaking-change&title=Remove%20obsolete%20member%20in%20src/Logging/Logging.Testing/src/Xunit/LoggedTheoryTestCase.cs&milestone=3.0.0-preview3)
* [x] I attest that I have taken appropriate action on this item

```c#
        [Obsolete("Called by the de-serializer; should only be called by deriving classes for de-serialization purposes")]
        public LoggedTheoryTestCase() : base()
        {
```

---

#### (5) src\TestingUtils\Microsoft.AspNetCore.Testing\src\xunit\SkippedTestCase.cs
Links: <a href="https://github.com/aspnet/Extensions/blob/master/src/TestingUtils/Microsoft.AspNetCore.Testing/src/xunit/SkippedTestCase.cs#L14">[master]</a> | <a href="https://github.com/aspnet/Extensions/blob/release/2.2/src/TestingUtils/Microsoft.AspNetCore.Testing/src/xunit/SkippedTestCase.cs#L14">[release/2.2]</a>
[File a bug for this](https://github.com/aspnet/Extensions/issues/new?body=Remove%20this%20obsolete%20member%20in%20%5Bsrc%2FTestingUtils%2FMicrosoft.AspNetCore.Testing%2Fsrc%2Fxunit%2FSkippedTestCase.cs%5D%28https%3A%2F%2Fgithub.com%2Faspnet%2FExtensions%2Fblob%2Fmaster%2Fsrc%2FTestingUtils%2FMicrosoft.AspNetCore.Testing%2Fsrc%2Fxunit%2FSkippedTestCase.cs%23L14%29%3A%0D%0A%0D%0A%60%60%60c%23%0D%0A%20%20%20%20%20%20%20%20%5BObsolete%28%22Called%20by%20the%20de-serializer%3B%20should%20only%20be%20called%20by%20deriving%20classes%20for%20de-serialization%20purposes%22%29%5D%0D%0A%20%20%20%20%20%20%20%20public%20SkippedTestCase%28%29%20%3A%20base%28%29%0D%0A%20%20%20%20%20%20%20%20%7B%0D%0A%60%60%60%0D%0A%0D%0AAnd%20file%20a%20new%20issue%20in%20https%3A%2F%2Fgithub.com%2Faspnet%2FAnnouncements%2Fissues%2F%20if%20this%20is%20a%20notable%20breaking%20change.%0D%0A&labels=breaking-change&title=Remove%20obsolete%20member%20in%20src/TestingUtils/Microsoft.AspNetCore.Testing/src/xunit/SkippedTestCase.cs&milestone=3.0.0-preview3)
* [x] I attest that I have taken appropriate action on this item

```c#
        [Obsolete("Called by the de-serializer; should only be called by deriving classes for de-serialization purposes")]
        public SkippedTestCase() : base()
        {
```

---

**Comment by muratg** [comment]
Filed bugs for the first two. Last three, I don't think we need to anything as they're test-only items.

**Comment by muratg** [comment]
Yup, good to close.
