### ISSUE TITLE
Remove obsolete member in src/Caching/Memory/src/MemoryCacheOptions.cs

### ISSUE THREAD

**Issue by muratg** [aspnet/Extensions#1027]
Remove this obsolete member in [src/Caching/Memory/src/MemoryCacheOptions.cs](https://github.com/aspnet/Extensions/blob/master/src/Caching/Memory/src/MemoryCacheOptions.cs#L17):

```c#
        [Obsolete("This is obsolete and will be removed in a future version.")]
        public bool CompactOnMemoryPressure { get; set; }

```

And file a new issue in https://github.com/aspnet/Announcements/issues/ if this is a notable breaking change.

**Comment by JunTaoLuo** [comment]
[Announcements](https://github.com/aspnet/Announcements/issues/340) and [Discussions](https://github.com/aspnet/Extensions/issues/1062) filed.
