### ISSUE TITLE
HttpClientFactory for several servers

### ISSUE THREAD

**Issue by jeremyVignelles** [aspnet/Extensions#1035]
I have a distributed application using .net core that needs to connect to its peers in HTTPS, using certificates signed by our authority.
We currently have an HttpMessageHandler implementation that checks the certificate, and a `DelegatingHandler` implementation that gets and renews an OpenId bearer token using IdentityModel.

I'd like to be able to connect to any number of peers, not known at startup, using the same pipeline of HttpClient but with different urls.

# What I want
I'd like to have a way to have a kind of IHttpClientFactory, but when `CreateClient` is called, to have a way to specify which url to connect to.

```
httpClientFactory.CreateClient(name, ip);
```

# What I've considered.
I tried to use the name parameter of `CreateClient`, but the fact that the name must be known when configuring the service provider makes it hard to use for me.

I'm using the old-style way, which is to create my own `HttpClient` and handlers manually, and disposing them myself.

**Comment by glennc** [comment]
@jeremyVignelles A few things I can think of, see if anything resonates:

1. Using the default client with no base address and specifying the whole URI in each request
2. Creating a handler that re-writes the URI on a per-request basis
3. Loop through a list of URIs and register a client for each base with a distinct name during startup

Do any of those approaches sound like they'd be interesting?

**Comment by jeremyVignelles** [comment]
Sorry, I just realized I've never replied.

1. could be done, I just need to parse the base URL and store authentication tokens in a dictionary

2. Not sure of what you mean

3. Not feasible since the number of peers is not known in advance

I currently did without a factory by instanciating a http client per host.
If you think there's nothing to be done on your side, feel free to close this.

**Comment by rynowak** [comment]
I think for now the only real solution that works is 1. We currently require any information that goes into the factory to be known at startup. 

If you're using long-lived http clients, you can set https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/SocketsHttpHandler.cs#L211 to some reasonable value. One of the issues with long-lived HTTP clients is that you may not see DNS updates since the connections could live a very long time.
