### ISSUE TITLE
HealthCheckPublisherOptions.Period sets the value of .Delay

### ISSUE THREAD

**Issue by guardrex** [aspnet/Extensions#1041]
`HealthCheckPublisherOptions.Period` sets the value of `HealthCheckPublisherOptions.Delay` ...

```csharp
services.Configure<HealthCheckPublisherOptions>(options =>
{
    options.Period = TimeSpan.FromSeconds(2);
});

services.AddSingleton<IHealthCheckPublisher, TestPublisher>();
```

`PublishAsync` is called on default 30-second intervals ... **_not the 2 seconds specified_**. When this setting is made `HealthCheckPublisherOptions.Delay` receives the value assigned to `Period`.

https://github.com/aspnet/Extensions/blob/release/2.2/src/HealthChecks/HealthChecks/src/HealthCheckPublisherOptions.cs

**Comment by guardrex** [comment]
@pranavkm I think Ryan is OOF for the conference. Do you have a sec to take a look? This is for the doc updates on `IHealthCheckPublisher` options + example ..... I'm having a devil of a time setting the options cleanly, especially `Period`.

I put the whole sample here :point_right: https://github.com/guardrex/HealthChecksSample

The important files are:

* [Publisher (IHealthCheckPublisher impl)](https://github.com/guardrex/HealthChecksSample/blob/master/ReadinessPublisher.cs)
* [Liveness Probe Startup](https://github.com/guardrex/HealthChecksSample/blob/master/LivenessProbeStartup.cs) &ndash; `Period` is set on Line 48.

For this scenario the sample is run with the `--scenario liveness` switch.

It's not honoring my 2-second setting ... it's using the 30-second default period.

**Comment by pranavkm** [comment]
@glennc could you review this? You're probably more familiar with the code here than I am.

**Comment by guardrex** [comment]
In the meantime, I need to load up 3.0 preview anyway for Blazor work, and I'll find out if this strange behavior goes away with 3.0 and ditching that funky workaround.

**Comment by guardrex** [comment]
Moved the app to 3.0 preview2. I was able to remove the workaround line ...

```csharp
services.TryAddEnumerable(
                ServiceDescriptor.Singleton(typeof(IHostedService), 
                    typeof(HealthCheckPublisherOptions).Assembly
                        .GetType(HealthCheckServiceAssembly)));
```

... but the `Period` is still defaulting to 30-seconds, and IDK where it's getting that 2-second setting for the delay given that it should be 5-seconds by default ...

<img width="417" alt="capture" src="https://user-images.githubusercontent.com/1622880/52155189-1b0ed080-2647-11e9-862f-89998a4a2f52.PNG">

**Comment by fugaku** [comment]
Is this available in aspnet.core 2.2 ?
If not, is there any workaround for this ?

**Comment by rynowak** [comment]
I opened https://github.com/aspnet/Extensions/issues/1311 to consider patching this for 2.2.X

For now the only workaround is to use reflection and set the field yourself.
