### ISSUE TITLE
Shipping packages now include .pdbs (regression from adopting Arcade)

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Extensions#1053]
I found another aspect of our packages that changed as a result of adopting Aracde: the shipping .nupkg files now include a .pdb file.

![image](https://user-images.githubusercontent.com/2696087/52150355-957a2900-2624-11e9-8ded-53bdc5404279.png)

Previously, we had decided as a team that we would not put symbols in .nupkg files because this increased their package size unnecessarily. Our symbols end up on symbols servers, so customers do need to acquire these via package download.

Should we workaround arcade or change approaches?

cc @markwilkie @ryanbrandenburg @Eilon @tmat

**Comment by tmat** [comment]
OK, so for now I'll disable including PDBs if `IncludeSymbols=true`. That should do.

**Comment by natemcmaster** [comment]
Thanks!

**Comment by tmat** [comment]
https://github.com/dotnet/arcade/pull/1960

**Comment by natemcmaster** [comment]
Should be resolved by the next update of Arcade. Thanks @tmat for a quick fix.

**Comment by poke** [comment]
@tmat 
> We need to transition to .snupkgs at some point. I have not had time to do that yet. 

Just wondering: Has there been any progress on that yet? It seems that the current 3.0 previews are not shipping with symbols yet?
