### ISSUE TITLE
Update AddTransientHttpErrorPolicy once Polly v7 is released

### ISSUE THREAD

**Issue by johnknoop** [aspnet/Extensions#1058]
I'm not sure if you are already aware of this, but Polly v7 will distinguish between `RetryPolicy` and `AsyncRetryPolicy`. Since all methods on the `HttpClient` are async, it would make sense if `AddTransientHttpErrorPolicy` only accepted  `AsyncPolicy` (note: not `IAsyncPolicy` since the sync version of RetryPolicy also implements that interface for some weird reason).

https://github.com/App-vNext/Polly/wiki/Polly-v7-breaking-changes

**Comment by reisenberger** [comment]
No changes to `AddTransientHttpErrorPolicy(...)` will be necessary to take advantage of Polly v7 cleaning up the sync/async split in Polly.  HttpClientFactory already only accepts `IAsyncPolicy<HttpResponseMessage>` - see: [`PollyHttpClientBuilderExtensions`](https://github.com/aspnet/Extensions/blob/557995ec322f1175d6d8a72a41713eec2d194871/src/HttpClientFactory/Polly/src/DependencyInjection/PollyHttpClientBuilderExtensions.cs).

> it would make sense if AddTransientHttpErrorPolicy only accepted AsyncPolicy (note: not IAsyncPolicy since the sync version of RetryPolicy also implements that interface)

That does not hold for Polly v7. Polly v7 clears up the weak sync/async split in Polly (which I inherited from previous maintainers of the project). For clarity again: No changes to `AddTransientHttpErrorPolicy(...)` will be necessary to take advantage of the changed sync/async handling in Polly v7.

---

The only relevant change that could be made on the Microsoft side would be (if desired, at a future release) to change the minimum supported version of Polly, in HttpClientFactory, to Polly v7.0.0.  This would prevent users configuring eg `.AddTransientHttpErrorPolicy(x => x.Retry(3))` (with v7 this will simply not compile) when `.AddTransientHttpErrorPolicy(x => x.RetryAsync(3))` should be used.

The only other breaking change in Polly v7.0.0 is [changes to cache provider interfaces](https://github.com/App-vNext/Polly/wiki/Polly-v7-breaking-changes#allow-cache-policies-to-cache-values-of-type-tresult). For cache providers which the Polly team maintains ([Polly.Caching.Memory](https://www.nuget.org/packages/polly.Caching.Memory), [Polly.Caching.Distributed](https://www.nuget.org/packages/Polly.Caching.Distributed) and [Polly.Caching.Serialization.Json](https://www.nuget.org/packages/Polly.Caching.Serialization.Json)), we will simultaneously release upgraded cache providers.  Thus, if Microsoft chooses to update HttpClientFactory in a future release to specify Polly v7.0.0 as the minimum-supported version, the only users forced to adjust their code for a breaking change would be any that had implemented their own custom cache providers for Polly CachePolicy.

Thanks @johnknoop for raising this :+1: ; a good prompt to document here how HttpClientFactory could be updated for Polly v7.

**Comment by glennc** [comment]
Thanks @reisenberger I appreciate all the context. I've fallen out of touch with your v7 work. Do you know when you plan to ship it?

**Comment by johnknoop** [comment]
Thanks for the clarification

**Comment by reisenberger** [comment]
@glennc We are planning to ship Polly v7 in the next fortnight: I will advise when it ships.  Polly v7 is both a [maintenance update](https://github.com/App-vNext/Polly/blob/98086907428c46aba92de1ebde30f9c8d3394755/CHANGELOG.md#700):

+ Clarify separation of sync and async policies - no impact on HttpClientFactory except improved usability for users - could update HttpClientFactory to Polly >= v7.0 as [discussed above](https://github.com/aspnet/Extensions/issues/1058#issuecomment-460259629)
+ Enable collection initialization syntax for PolicyRegistry - simplifies a few `StartUp` configuration scenarios for HttpClientFactory with PolicyRegistry
+ Enable cache policies to cache default(TResult)  - bug fix

And **major new features**:

+ Enable extensibility by custom policies - IE allow users to author their own Polly-compatible policies, turning Polly into _user-extensible_ middleware for _any_ outbound call - (the equivalent of what HttpClient has via custom `DelegatingHandler`s; but for _any_ Polly-wrapped execution, not just HttpClient)
+ the launch of [Simmy](https://github.com/App-vNext/Simmy), a software-level [fault-injection and chaos-injection tool](https://github.com/App-vNext/Polly/issues/499) based on custom Polly policies. Inject faults in a controllable manner into any calls you already guard with Polly. Including via HttpClient and HttpClientFactory. (May launch a few weeks behind Polly v7, but already build-able from the github repo)

Thanks!

/cc @joelhulen

**Comment by reisenberger** [comment]
@glennc  Polly v7 is shipped.  If you wish to upgrade HttpClientFactory for .NET Core 3.0 to reference Polly v7, we recommend that HttpClientFactory reference Polly v7.0.3 as the minimum version.  

As [described in more detail above](https://github.com/aspnet/Extensions/issues/1058#issuecomment-460259629):

_Advantages_: Improved async syntax enforcement.
_Risk of breaking change_: Only for a user who has implemented their own custom cache provider.

Let me know if you want to proceed.  HttpClientFactory [also references](https://github.com/aspnet/Extensions/blob/43435a80d007d568aa17d891ea32ca87363716fc/eng/Dependencies.props#L66-L67) to [Polly.Extensions.Http](https://www.nuget.org/packages/Polly.Extensions.Http), so if we go ahead, the sequence would be:

+ Polly team publish a [Polly.Extensions.Http](https://www.nuget.org/packages/Polly.Extensions.Http) v3.0.0, which also references min Polly v7.0.3 (... to avoid any diamond dependency conflicts)
+ HttpClientFactory is (in a single PR) repointed to reference Polly v7.0.3 and Polly.Extensions.Http v3.0.0

Thanks

/cc @joelhulen

**Comment by rynowak** [comment]
I'll catch up with @glennc and discuss with him. I can't think of a reason why we wouldn't do this. We want users to get the best version of things.

**Comment by reisenberger** [comment]
Pinging an update: Note that we are planning to publish a Polly v7.1.0 (intended by end of week) which would be the version to reference, if we go for this.

Will update, soon as that ships.

**Comment by rynowak** [comment]
Great!

**Comment by altso** [comment]
Any plans to upgrade HttpClientFactory v2.x to Polly 7?

**Comment by rynowak** [comment]
Yes, we're currently planning that as part of 3.0

**Comment by altso** [comment]
@rynowak apologies for the confusion. I understand that `Microsoft.Extensions.Http.Polly` 3.0.0 will have a dependency on `Polly` 7.1.0 (or higher). Will you be also releasing `Microsoft.Extensions.Http.Polly` 2.x.x (e.g. 2.3.0) with a dependency on `Polly` 7.1.0?

**Comment by rynowak** [comment]
No, we don't change dependency versions in a patch release.

**Comment by altso** [comment]
Got it. Thanks for the clarification.

**Comment by reisenberger** [comment]
@rynowak @glennc Polly v7.1.0 is [now on nuget](https://www.nuget.org/packages/polly).

[Here the procedure](https://github.com/aspnet/Extensions/issues/1058#issuecomment-466157832) to update inter-related components all to reference Polly v7.1.0.  Please let me know when you want me to enact this?  

Thanks!

**Comment by rynowak** [comment]
@reisenberger we are ready to do this whenever. Ideally we could get it done in the next two weeks for the next preview release.

**Comment by reisenberger** [comment]
@rynowak Thanks! I am in a conference all week but should get to this at the weekend.

**Comment by rynowak** [comment]
great!

**Comment by rynowak** [comment]
Here's a draft PR. https://github.com/aspnet/Extensions/pull/1313

I don't expect it to pass now since we're waiting for the new package.

**Comment by rynowak** [comment]
This is done!
