### ISSUE TITLE
Disscussion: CompactOnMemoryPressure removed from MemoryCacheOptions

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Extensions#1062]
Discussion for https://github.com/aspnet/Announcements/issues/340.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
