### ISSUE TITLE
Exposing JsonConfigurationFileParser externally as reusable JsonConfigurationParser

### ISSUE THREAD

**Issue by KenHundley** [aspnet/Extensions#1074]
I'm working on a custom configuration extension that will need to parse a JSON text string from an API call into valid configuration data. I knew the JSON parsing functionaly must already exist since it would be needed by the JsonConfigurationProvider, and I hoped that it was exposed in a way that I could reuse it directly. However, when I looked into the code the class is internal and part of the `Microsoft.Extensions.Configuration.Json` project. Looking at the internal workings of the class I don't see anything that make this a "FileParser" since it only deals with an input stream, which can come from any source.

I'd like to propose that this class be exposed for reuse as a base level parser (outside of the Json File Provider), available for all configuration providers to use. Maybe in the `Microsoft.Extensions.Configuration` package.

I know that I can simply copy the code into my project and achieve the same effect, but I believe it would be better long-term if this could be reused by Configuration projects in a consistent manner.

Thoughts?

**Comment by Eilon** [comment]
@KenHundley to better evaluate your suggestion, can you share what the API you're expecting might look like?

**Comment by KenHundley** [comment]
Oh, I just need something that flattens the JSON into valid Dictionary KeyValue pairs needed by the Configuration framework (colon delimited) . The class you already have would satisfy my needs as-is.

The provider I'm looking at creating would integrate with the AWS Secrets Manager Service to turn whatever JSON is in the secret into valid configuration data. 
https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_GetSecretValue.html#SecretsManager-GetSecretValue-response-SecretString

My thought was simply that JSON is such a ubiquitous structure for storing and/or returning information that having a process that reliability translates any JSON model into configruation KeyValue pairs would be best. That way if an improvement to the made to the Parser all services could take advantage. 

Let me know if you still need more detail.

**Comment by Eilon** [comment]
Thanks for the info. I'll let the experts of this area get back to you on possibilities.

**Comment by KenHundley** [comment]
Looks like this is similar to #496

**Comment by KenHundley** [comment]
Closing this as it appears this is already in the 3.0 milestone
