### ISSUE TITLE
Prevent dublicating hosted services registered with AddHostedService

### ISSUE THREAD

**Issue by Chakrygin** [aspnet/Extensions#1078]
Hi!

This issue related with https://github.com/aspnet/Extensions/pull/552

### Is your feature request related to a problem? Please describe.
If one hosted service is registered in two or more parts of an application (with AddHostedService), this leads to the creation of several instances of this service.

```
// services.AddFirstComponentServices()
services.AddHostedService<MyHostedService>();

...

// services.AddSecondComponentServices()
services.AddHostedService<MyHostedService>();
```

Two instances of `MyHostedService` will be created and started.
I think this is not the expected behavior.

### Describe the solution you'd like
Change AddHostedService to using TryAddEnumerable instead of AddSingleton or AddTransient.
Or add TryAddHostedService extension method.

```
public static class ServiceCollectionHostedServiceExtensions
{
    public static IServiceCollection AddHostedService<THostedService>(
        this IServiceCollection services, ServiceLifetime serviceLifetime = ServiceLifetime.Transient)
        where THostedService : class, IHostedService
    {
        services.TryAddEnumerable(
            new ServiceDescriptor(typeof(IHostedService), typeof(THostedService), serviceLifetime));

        return services;
    }
}
```

### Describe alternatives you've considered
Manual hosted service registration without AddHostedService method.

**Comment by davidfowl** [comment]
Yes we should do this. @Chakrygin do you want to send a pull request?
