### ISSUE TITLE
[Feature Request] Disable log level/category/eventid logging in ConsoleLogger

### ISSUE THREAD

**Issue by moraneva** [aspnet/Extensions#1088]
### Is your feature request related to a problem? Please describe.
Using the `ConsoleLogger` produces 2 lines in stdout every time a message is logged. The first line is a line relating to the log level/category/eventid for a message and the second line is the actual message being logged. This may be fine for some use cases, but when using a log aggregation tool that ports every line from stdout to a logging system it produces extreme clutter and doesn't provide any value. Essentially each message we log turns into **2** logs in our systems.

Taking splunk as an example, logging 1 message would produce the following entries:
![image](https://user-images.githubusercontent.com/11748634/52416372-6bf34e80-2ab7-11e9-85ba-e2048fcbbf5d.png)

Two log entries are shown in this picture. This one on the bottom is the log in question, where the one on top is the message that we actually care about. We have seen no value in the log in question and are always forced to filter it out when searching for certain logs.

Furthermore, if multiple logs are batched together and sent at the same time, then we cannot enforce order. Without order, then there is no way of knowing which message the log level/category/eventid line actually corresponds to so at that point it is useless.

This type of log aggregation is becoming more and more common as the industry moves towards container based systems such as kubernetes and docker. Specifically shipping **1** line of stdout.stderr to **1** log.

### Describe the solution you'd like
I would like to be able to disable logging this log level/category/eventid using configuration. Another option could be added to the [ConsoleLoggerOptions](https://github.com/aspnet/Extensions/blob/master/src/Logging/Logging.Console/src/ConsoleLoggerOptions.cs) to do this (named something like `DisableCategoryLogging`). 

If this option were true, then the `ConsoleLogger` would only log the message that was sent is and would not log the log level/category/eventid line. So if you sent in a message that had no new lines, then you would only ever be logging 1 line.

### Describe alternatives you've considered
There are a couple alternatives to this problem:

1. Live with the extra logs. Most logging systems have good filtering mechanisms that would make this easy.
2. Users implement their own `ConsoleLogger` that doesn't log the log level/category/eventid line. Downside to this would be those users would not stay up to date with changes in this package and there could possibly be many people that implement this on their own (which I assume we wouldn't want) .

**Comment by anurse** [comment]
We don't plan to provide this kind of customization on the existing console logger. Implementing a custom logger that adds this behavior is our recommended approach (and could even be a useful component for the ecosystem!)
