### ISSUE TITLE
[Question] HostBuilder: When and where IOption<ConsoleLifetimeOptions> registered with DI container

### ISSUE THREAD

**Issue by ghen** [aspnet/Extensions#1103]
From [HostingHostBuilderExtensions.cs](https://github.com/aspnet/Extensions/blob/ea0df662ab06848560d85545f3443964c57e9318/src/Hosting/Hosting/src/HostingHostBuilderExtensions.cs):

- **RunConsoleAsync()** method (line 157) would call **UseConsoleLifetime()** (line 130) to register **ConsoleLifetime** as **IHostLifetime**
- Then application host is built and can be run

However, **ConsoleLifetime()** constructor requires **IOptions&lt;ConsoleLifetimeOptions&gt;** instance. And we are unable to locate from the source code, **who and when would register IOptions&lt;ConsoleLifetimeOptions&gt; with the DI conteiner by default**?

We would like to know how **ConsoleLifetimeOptions** instance is constructed and its default state when **IOptions&lt;ConsoleLifetimeOptions&gt;** is resolved from DI container.

**Comment by anurse** [comment]
The `IOptions<ConsoleLifetimeOptions>` instance is registered by [this call to `Configure`](https://github.com/aspnet/Extensions/blob/6991e2b0e8f7a133208d015dc7d0ca4192523ba0/src/Hosting/Hosting/src/HostingHostBuilderExtensions.cs#L147).

What is the problem you are trying to solve?

**Comment by anurse** [comment]
If you want to create one yourself, you can use `Options.Create(new ConsoleLifetimeOptions())`. You can see more about the options pattern [in our documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.2)

**Comment by ghen** [comment]
Thank oyu, anurse.

This overload let us provide our own options.
Where we would like to know where the default settungs are coming from when [UseConsoleLifetime()](https://github.com/aspnet/Extensions/blob/6991e2b0e8f7a133208d015dc7d0ca4192523ba0/src/Hosting/Hosting/src/HostingHostBuilderExtensions.cs#L130) is used? It is also called from [RunConsoleAsync()](https://github.com/aspnet/Extensions/blob/6991e2b0e8f7a133208d015dc7d0ca4192523ba0/src/Hosting/Hosting/src/HostingHostBuilderExtensions.cs#L159)

**Comment by anurse** [comment]
I don't believe any of the options are configured by default. The `configurationOptions` delegate parameter in `UseConsoleLifetime`/`RunConsoleAsync` can be used to set your own option. If you don't do that, I believe you just get the default values (see https://github.com/aspnet/Extensions/blob/6991e2b0e8f7a133208d015dc7d0ca4192523ba0/src/Logging/Logging.Console/src/ConsoleLoggerOptions.cs).

**Comment by ghen** [comment]
Why exactly is this reference to ConsoleLoggerOptions?

The original question is: **Who and when would register IOptions<ConsoleLifetimeOptions> with the DI conteiner by default?**

Let me rphrase it.
- Application is starting
- Empty DI container
- We call **RunConsoleAsync()**
- **ConsoleLifetime()** constructor requires **IOptions<ConsoleLifetimeOptions>** instance
- Application starts successfully

We can't locate from source code, who and when would register IOptions<ConsoleLifetimeOptions> with the DI conteiner, so new ConsoleLifetime could be constructed successfully.

Here is a sample code (.NET Core 2.2):

`
using System;
using Microsoft.Extensions.Hosting;

namespace Test {

  internal class Program {

    private static void Main(String[] args) {

      Console.WriteLine("Main:: Entry point reached...");

      new HostBuilder().RunConsoleAsync()
        .GetAwaiter().GetResult();

      Console.WriteLine("Main:: Done.");

    }
  }
}
`

Output:

`
Main:: Entry point reached...
Application started. Press Ctrl+C to shut down.
Hosting environment: Production
Content root path: C:\Temp\TestCore\bin\Debug\netcoreapp2.2\

>> Ctrl+C <<

Main:: Done.
Press any key to continue . . .
`

**Comment by anurse** [comment]
Yeah, that's what I posted in my [earlier comment](https://github.com/aspnet/Extensions/issues/1103#issuecomment-474976733). The call to the `.Configure` method I linked configures the DI container so that when `ConsoleLifetime` is constructed, the DI container ensures that an instance of `IOptions<ConsoleLifetimeOptions>` is created and provided to it.

**Comment by ghen** [comment]
Thank you, Andrew.

Does it mean the options subsystem would create an emply IOptions<T> (using default constructor of T) for any requested T, unless specfic instance of T was registered?

Also as we didn't enable/add Options to our host builder explicitly in this example, does it mean it was added somewhere inside **RunConsoleAsync()** or **HostBuilder.Build()** silently? Just for clarity.

**Comment by anurse** [comment]
> Does it mean the options subsystem would create an emply IOptions (using default constructor of T) for any requested T, unless specfic instance of T was registered?

Essentially, yes. The way the options system works is like this:

1. The options subsystem [registers an "open-generic" registration for `OptionsManager<>` mapping to `IOptions<>`](https://github.com/aspnet/Extensions/blob/master/src/Options/Options/src/OptionsServiceCollectionExtensions.cs#L23). So when a component requests an `IOptions<Foo>`, an `OptionsManager<Foo>` will be automatically created.
2. Any calls to the `.Configure` extension method on `IServiceCollection` take in `Action<Foo>`, wrap it in an object that implements `IConfigureOptions<Foo>` and registers it in the DI container.
3. The [`OptionsManager<Foo>` class](https://github.com/aspnet/Extensions/blob/master/src/Options/Options/src/OptionsManager.cs) (via [`OptionsFactory<Foo>`](https://github.com/aspnet/Extensions/blob/master/src/Options/Options/src/OptionsFactory.cs)) pulls out all `IConfigureOptions<Foo>` registrations from DI.
4. The `OptionsFactory<Foo>` class, in the [`Create` method](https://github.com/aspnet/Extensions/blob/77062db28a6a99f116a9fd5cba1311bebd11ff51/src/Options/Options/src/OptionsFactory.cs#L42), constructs a new instance of `Foo` using the default constructor.
5. The `OptionsFactory<Foo>` class (still in `Create`) then runs any registered `IConfigureOptions<Foo>` components (including the `Action<Foo>` delegates) to allow them to **modify** the `Foo` instance
6. Finally, the instance of `Foo`, created in step 4 and **modified** by any registered configurers in step 5 is returned in the `IOptions<Foo>.Value` property.



> Also as we didn't enable/add Options to our host builder explicitly in this example, does it mean it was added somewhere inside **RunConsoleAsync()** or **HostBuilder.Build()** silently? Just for clarity.

Yes, the [`HostBuilder` automatically registers the Options component](https://github.com/aspnet/Extensions/blob/6991e2b0e8f7a133208d015dc7d0ca4192523ba0/src/Hosting/Hosting/src/HostBuilder.cs#L200) for you.

**Comment by ghen** [comment]
Excellent explanation.
Thank you, Andrew!
