### ISSUE TITLE
Caching Fallback mechanism

### ISSUE THREAD

**Issue by Vandersteen** [aspnet/Extensions#1105]
### Is your feature request related to a problem? Please describe.
I was wondering how I could configure the IDistributedCache so that it would not blow up the entire application should the cache be 'temporarily' unavailable. Say that I use RedisDistributedCache, and the redis server crashed. This does not mean that our application does not work at all anymore but only the caching layer. However, exceptions get thrown now that we are not always able to catch, e.g.: when using IdentityServer4.AccessTokenValidator with caching enabled. [ref](https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation/issues/111).

Is this something that can be configured right now, or would I have to implement my own version of RedisDistributedCache that does not throw exceptions.

### Describe the solution you'd like
The ability to make the application still work without blowing up, while being able to detect the issue / trigger warnings.
Or temporarily switch to another caching mechanism (e.g. InMemoryCache, or 'dummy' cache)

Or being able provide multiple layers of caching (e.g. Memory -> Redis -> Mysql)

### Describe alternatives you've considered
Writing my own implementation of RedisDistributedCache that is able to gracefully handle failures

**Comment by grprakash** [comment]
If you can add dependency on Polly, then probably using the [Fallback](https://github.com/App-vNext/Polly#fallback) would be a best option.

**Comment by anurse** [comment]
This isn't something we intend to add to the cache directly. Retry logic and dependency management is a common cross-cutting concern and I would suggest something like Polly, or custom retry code to achieve what you're looking for.
