### ISSUE TITLE
Consider patching #999: HttpClientFactory managed HttpClient deadlocks in single-threaded SynchronizationContext

### ISSUE THREAD

**Issue by rynowak** [aspnet/Extensions#1127]
This is a functional bug with a clear and simple fix.

**Comment by Eilon** [comment]
Original issue link: https://github.com/aspnet/Extensions/issues/999

**Comment by Eilon** [comment]
@mkArtakMSFT - can you start a thread so we can discuss?

**Comment by rynowak** [comment]
Another report here: https://github.com/aspnet/Extensions/issues/563

**Comment by rynowak** [comment]
We've missed our chance to patch this for 2.2 I think it's going out of support this month.
