### ISSUE TITLE
Read once from cache would be great

### ISSUE THREAD

**Issue by asfyra** [aspnet/Extensions#1157]
We would like to be sure that a value from cache (we use the SQL option) can be read only once from the first one who asks for it.

In an SQL like format it would be sth like: 

`DELETE from ASPCache output deleted.Value where [Id] = 'key'`

I have implemented this functionality by extending the SqlServerCache class, but it would be great if this feature was available officially.
I could make a PR with this feature if you are interested, but only for the SQL cache option.

Thanks is advance
  Alex Sfyrakis

**Comment by anurse** [comment]
That's not really how caches are designed to work. You're welcome to do so in your own extension but we don't intend to add this behavior to our caches.
