### ISSUE TITLE
HttpClient has many TIME_WAIT or CLOSE_WAIT connections

### ISSUE THREAD

**Issue by ahmettahasakar** [aspnet/Extensions#1196]
I use AddHttpClient() dependency injection to add a client to a service. At times, when I execute netstat -a on the server, I see many connections open with TIME_WAIT or CLOSE_WAIT status. I believe that these connections take up so much resource that, other TCP connections are unable to operate. Is this possible? Is there a way to stop these, and is it safe?

**Comment by muratg** [comment]
Sounds like an HttpClient issue. Do you mind moving this bug over to https://github.com/dotnet/corefx?

**Comment by ahmettahasakar** [comment]
Done. Thank you
