### ISSUE TITLE
Where si AddDockerSecrets configuration provider ?

### ISSUE THREAD

**Issue by RemiBou** [aspnet/Extensions#1199]
### Is your feature request related to a problem? Please describe.
This package was unlisted https://www.nuget.org/packages/Microsoft.Extensions.Configuration.DockerSecrets/ and the source code is no longer there, what are the alternative for reading docker secrets as configurations ?

### Describe the solution you'd like
AddDockerSecrets to be back or something else

Sorry if I missed something

**Comment by martincostello** [comment]
@RemiBou I believe you want [Microsoft.Extensions.Configuration.KeyPerFile](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.KeyPerFile)

https://github.com/aspnet/Extensions/blob/d7f8e253d414ce6053ad59b6f974621d5620c0da/src/Configuration/Config.KeyPerFile/src/KeyPerFileConfigurationProvider.cs#L30

**Comment by RemiBou** [comment]
I didn't know about this solution thanks.

I found the following solution : map secret as file and add the json file in loaded configuration

https://github.com/RemiBou/Toss.Blazor/blob/master/docker-compose.yml

In my compose file I define the volume like this :
`
secrets:
  tossserver2:
    file: /Users/remibourgarel/.microsoft/usersecrets/ae68635e-649c-4f23-a39b-24a5ea3987f4/secrets.json
`

I link it to the .net container like this

`
services:    
  web:
    image: toss
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    secrets:
      - source: tossserver2
        target: tossserver
`

And I use it like this in my Program.cs

`
webBuilder.UseConfiguration(new ConfigurationBuilder()
                        .AddCommandLine(args)
                        .AddUserSecrets<Startup>()
                        .AddJsonFile("/run/secrets/tossserver")
                        .AddEnvironmentVariables()
                        .Build())
`

I had to rename it because docker compose or swarm doesn't like secret change.
