### ISSUE TITLE
I can't seem to find right version of Microsoft.Extensions.Configuration.Json for .net framework 4.6.1

### ISSUE THREAD

**Issue by sk29110** [aspnet/Extensions#1201]
### Describe the bug
I upgraded my application from DNX451 to .net 4.6.1 and I am looking for the version of Microsoft.Extensions.Configuration.json for my framework but I can't seem to find one. Is it deprecated already?

### To Reproduce
1. Using version '2.2.0' of package 'Microsoft.Extensions.Configuration.Json'
2. Just tried to compile my application
3. using the following project.json

```
{
  "version": "1.0.0-*",
  "description": "ApiClient Console Application",
  "authors": [ "hasanm" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "compilationOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.AspNet.WebApi.Client": "5.2.3",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.2",
    "Microsoft.Extensions.Configuration.Json": "2.2.0"
  },

  "commands": {
    "ApiClient": "ApiClient"
  },

  "frameworks": {
    "net461": {
      "frameworkAssemblies": {
        "System.Runtime.Serialization": "4.0.0.0",
        "System.Xml": "4.0.0.0"

      }
    }
  }
}
```
4. Get the following compile error
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1002	The dependency Microsoft.Extensions.Configuration.Json 2.2.0 in project ApiClient does not support framework .NETFramework,Version=v4.6.1.	ApiClient	 	

### Expected behavior
I should be able to find a right version of Microsoft.Extensions.Configuration.Json pacakge for .net 4.6.1

### Screenshots
![image](https://user-images.githubusercontent.com/626182/53656139-300b5f00-3c07-11e9-9fdb-5ec24d3fa76a.png)

**Comment by davidfowl** [comment]
You might want to remove all `project.json` and start over.

**Comment by JanEggers** [comment]
and use 2.2 for Microsoft.Extensions.Configuration.EnvironmentVariables 

the Microsoft.Extensions.* packages should all be the same version at least same mayor version
