### ISSUE TITLE
Unable to name EventSource when using LoggingEventSource 

### ISSUE THREAD

**Issue by ChrisLucasMSFT** [aspnet/Extensions#1220]
### Is your feature request related to a problem? Please describe.
I have multiple services running on the same service fabric.  The fabric will often co-locate these on machines that already have a consumer of `EventSourceLoggerProvider`.  Because they share the same name, `Microsoft-Extensions-Logging` I can not selectively enable the ETW collection for services, separate them into different collection mechanisms, or keep the messages clearly separated from each other during debugging.

### Describe the solution you'd like
I'd like a way to specify the ETW provider name.

### Describe alternatives you've considered
I have rolled my own LoggingProvider that uses a generic EventSource to provide this functionality.

**Comment by anurse** [comment]
> I have multiple services running on the same service fabric.

Are these services running in multiple processes? You can selectively enable ETW providers by process ID if that would help.

The name has to be specified directly in the class itself as an attribute, so it's not possible to make this configurable. There are a few options you can use here:

1. You can selectively enable specific logger prefixes using the "FilterSpecs" parameter. There are some docs in the code here: https://github.com/aspnet/Extensions/blob/master/src/Logging/Logging.EventSource/src/LoggingEventSource.cs#L14

2. You can clone the EventSourceLogger code and make your own with a different name.

**Comment by anurse** [comment]
Closing this as we haven't heard from you and generally close issues with no response after ~7 days. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
