### ISSUE TITLE
Microsoft.Extensions.Logging.Abstractions licensing

### ISSUE THREAD

**Issue by mfkl** [aspnet/Extensions#1252]
Hi,

`Microsoft.Extensions.Logging.Abstractions` is currently licensed under Apache2. 

It's a great initiative by MSFT to offer this so that the .NET logging implementation story gets better. The idea is that everyone should take a dependency on this 
https://twitter.com/davidfowl/status/1104883885999964160
https://twitter.com/davidfowl/status/1105032919058329600

For LGPL/GPL projects, apache2 dependencies are not possible. If you want true adoption of this package, I think you should consider re-licensing it under another license.

**Comment by Eilon** [comment]
Standard IANAL disclaimer, but according to the Apache Software Foundation, Apache v2 (which is what Microsoft.Extensions is licensed as) is compatible with GPL v3: https://www.apache.org/licenses/GPL-compatibility.html

Of course, that's the FSF's take, so you'd need to consult a suitable legal expert to address any specific concerns that you have regarding licenses and license compatibility. We are unable to provide any legal guidance on this forum.

At this time we have no plans to change the licensing of this project, so I am closing the issue.

**Comment by mfkl** [comment]
IANAL either.

Should have been more specific by mentioning I meant LGPLv2.1, which appears to be incompatible with Apache v2: https://opensource.stackexchange.com/a/5756

> We are unable to provide any legal guidance on this forum.

Getting legal guidance was not the point of my issue.

> At this time we have no plans to change the licensing of this project

Fine. I think you are making a mistake. And I believe re-licensing just the logging part of your extensions would be beneficial for wider ecosystem adoption (which .NET really needs regarding its logging interop story).

**Comment by Eilon** [comment]
Hi @mfkl , this is something I'll keep in mind, but there are no plans to change the license at this time.
