### ISSUE TITLE
Caching - Null value semantics

### ISSUE THREAD

**Issue by brandondahler** [aspnet/Extensions#1255]
### Describe the bug
When storing a null value in caches, `TryGetValue<TItem>(object key, out TItem value)` always returns `false` even when`TryGetValue(object key, out object value)` returns `true`.

### To Reproduce
``` C#
    class Program
    {
        static int Main(string[] args)
        {
            var memoryCache = new MemoryCache(Options.Create<MemoryCacheOptions>(new MemoryCacheOptions()));

            memoryCache.Set<object>("a", null);

			
            Console.WriteLine(memoryCache.TryGetValue("a", out _) == memoryCache.TryGetValue<object>("a", out _));

            return 0;
        }
    }
```

#### Expected behavior
Program prints `True`

#### Actual Result
Program prints `Flase`

### Recommended Solution
I believe TryGetValue<TItem> should be updated to always return `true` if the resulting value is null.  Pull request to follow.

### Workaround
Issue can be worked around using a wrapper object; however, it appears the intent of CacheEntry is to allow null value to be properly cached -- no other code deals with the null semantics in this way.

### Additional context
Appears to be a side-effect of the addition of https://github.com/aspnet/Caching/pull/395 .  `null is TItem` will always return `false` while the previous code `(TItem) null` would always successfully cast null to reference types.

I don't personally think this would be a breaking change, but could be considered a breaking change since it would be altering the way null semantics are handled for this particular function.

**Comment by Tratcher** [comment]
That check is here:
https://github.com/aspnet/Extensions/blob/4b314dd3ce296dc1f951b91623ed070bccdaa918/src/Caching/Abstractions/src/MemoryCacheExtensions.cs#L27-L31

`is TItem` returns false for null values.
