### ISSUE TITLE
AzureKeyVaultConfigurationProvider is not honoring ReloadInterval correctly

### ISSUE THREAD

**Issue by sukhong** [aspnet/Extensions#1265]
### Describe the bug
AzureKeyVaultConfigurationProvider is not honoring ReloadInterval correctly.

In https://github.com/aspnet/Extensions/blob/master/src/Configuration/Config.AzureKeyVault/src/AzureKeyVaultConfigurationProvider.cs,

WaitForReload() function is taking _reloadInterval.Value.Milliseconds as delay time.

However, Value.Milliseconds do not corectly represent the whole TimeSpan, as it only contains milliseconds portion of it.

For example:
TimeSpan.FromMilliseconds(5000) returns 0 for its Milliseconds value, 
TimeSpan.FromMilliseconds(5010) will return 10 for Milliseconds value.

### To Reproduce
1. Using 3.0.0-preview4.19164.7 version of Microsoft.Extensions.Configuration.AzureKeyVault package,
2. Run this code:
`var azureKeyVaultConfirationOption = new AzureKeyVaultConfigurationOptions("[some keyvault]");
azureKeyVaultConfirationOption.ReloadInterval = TimeSpan.FromMilliseconds(5000);
config.AddAzureKeyVault(azureKeyVaultConfirationOption);`

3. This will attempt to reload the keys at every possible moment, since it is essentially waiting Task.Delay(0);

### Expected behavior
ReloadInterval should honor the whole TimeSpan, not just Milliseconds portion.

**Comment by Tratcher** [comment]
Yes, this looks like a bug.

**Comment by anurse** [comment]
This is done in https://github.com/aspnet/Extensions/pull/2000
