### ISSUE TITLE
Httpclient bug

### ISSUE THREAD

**Issue by lun3322** [aspnet/Extensions#1270]
### Describe the bug
Httpclient accesses part of the domain name in the dotnet core and throws an exception. Normally in freamwork 4.7

### To Reproduce
https://github.com/lun3322/httpclient-bug

### Expected behavior
System.AggregateException: One or more errors occurred.

**Comment by muratg** [comment]
You may want to move this to https://github.com/dotnet/corefx if it's an HttpClient bug.
