### ISSUE TITLE
PatternMatchingResult should implement IEnumerable

### ISSUE THREAD

**Issue by MikeChristensen** [aspnet/Extensions#1274]
### Describe the bug
We should be able to `foreach` through a `PatternMatchingResult` instance.  The enumerator would simply return an enumeration of `FilePatternMatch` objects.

### To Reproduce
1. Using version '...' of package '...'
Latest (2.2.0)

2. Run this code '....'

This should work:

```
var results = matcher.Execute(dirInfo);
foreach(var result in results) { } // Error
```

The above should be the same as:

```
var results = matcher.Execute(dirInfo);
foreach(var result in results.Files) { }
```

3. With these arguments '....'

### Additional context
Include the output of `dotnet --info`

**Comment by anurse** [comment]
We generally avoid implementing `IEnumerable` on custom types when they are simply wrapping collections. These objects are designed to be simple POCOs.
