### ISSUE TITLE
IHostLifetime that stops when all IHostedService's stop running

### ISSUE THREAD

**Issue by ejsmith** [aspnet/Extensions#1276]
Currently there is no way to use the generic host to run code that doesn't run indefinitely. I want to be able to have a worker type generic host that runs a few `IHostedService` instances and then terminates once those background services stop running. Is that something you would consider a pull request for?

**Comment by Tratcher** [comment]
Hmm, right now there's not even a concept of a IHostedService stopping itself.  You can already stop the host using IApplicationLifetime.StopApplication. The bit your missing is the coordination across services. This wouldn't be hard for you to do via a central service but I don't think IHostLifetime is that service. You'd still want IHostLifetime around to manage Console or ServiceBase lifetime.

**Comment by ejsmith** [comment]
The IHostedService doesn’t have to run forever or be a loop. The code might just do some work and then return. Basically I have a job runner console app that can run several different jobs that are executed in the generic host using IHostedService. Some of them run forever and some of them don’t. I want to make use of the same bootstrapping and other infrastructure code for all of them. Does that make sense?

**Comment by glennc** [comment]
The way I think I would approach this is to make a new "job" concept for your app, IJob for example. It has an `Execute` method. Then a single hosted service that executes all the jobs and waits for them to finish, calling stop on the application when it's done. The HostedService can get an IEnumerable<IJob> from DI so you register the hosted service + all the jobs and adding it all hangs together.

The other I can think of, which I think @Tratcher alluded to, is a cooperative stop service that you add to DI. All the hosted services call a method on that service, and it takes care of stopping the application once all hosted services have called the method. For example, it could accept all hosted services from DI in its constructor and use that as the list of all things that have to report in. Does that make sense @Tratcher?

**Comment by ejsmith** [comment]
I’m doing something similar here:
https://github.com/FoundatioFx/Foundatio/tree/master/src/Foundatio.Hosting/Jobs

But I was just thinking that it might make sense to have that as one of the included host lifetimes. I was thinking that the code that kicks off all of the hosted services would have access to the Task instances to wait for completion, but now that I’m thinking about it. Those tasks complete immediately after they have kicked off the long running task in the hosted service. So I guess that wouldn’t work and you really don’t know currently when all of the IHostedServices have completed.

**Comment by Tratcher** [comment]
Right, each hosted service would have to notify the shared shutdown service that they are starting so it can keep track, and then they would have to notify again when they completed.

**Comment by thomaslevesque** [comment]
> Then a single hosted service that executes all the jobs and waits for them to finish, calling stop on the application when it's done

The problem with this is that `IApplicationLifetime.StopApplication()` doesn't let you specify a return code, so the program will always appear to exit successfully. There should be a way to notify the host that the program ended unsuccessfully.

> Right, each hosted service would have to notify the shared shutdown service that they are starting so it can keep track, and then they would have to notify again when they completed.

Maybe `IHostedService` isn't the right abstraction for this. It's clearly designed for workers that run forever. Maybe a new abstraction should be introduced (e.g. `IJob`), along with a new method on `IHost`, e.g. `RunJobsAsync()`. A program that isn't meant to run forever would look like this:

```csharp
public static async Task Main(string[] args)
{
    var host = new HostBuilder()
        .ConfigureServices(services => services.AddJob<MyJob>())
        .Build();
    await host.RunJobsAsync();
}
```

**Comment by thomaslevesque** [comment]
Hi @ejsmith, why close this now that it's been added to the backlog?

**Comment by ejsmith** [comment]
Because it’s not going to work with the current IHostedService design and it sounds like the team is offering work around and not wanting to make changes. I will just keep doing things like I’m doing them now.

**Comment by mslot** [comment]
> > Then a single hosted service that executes all the jobs and waits for them to finish, calling stop on the application when it's done
> 
> The problem with this is that `IApplicationLifetime.StopApplication()` doesn't let you specify a return code, so the program will always appear to exit successfully. There should be a way to notify the host that the program ended unsuccessfully.
> 
> > Right, each hosted service would have to notify the shared shutdown service that they are starting so it can keep track, and then they would have to notify again when they completed.
> 
> Maybe `IHostedService` isn't the right abstraction for this. It's clearly designed for workers that run forever. Maybe a new abstraction should be introduced (e.g. `IJob`), along with a new method on `IHost`, e.g. `RunJobsAsync()`. A program that isn't meant to run forever would look like this:
> 
> ```cs
> public static async Task Main(string[] args)
> {
>     var host = new HostBuilder()
>         .ConfigureServices(services => services.AddJob<MyJob>())
>         .Build();
>     await host.RunJobsAsync();
> }
> ```

The exit code can be controlled by Environment.ExitCode.
