### ISSUE TITLE
StringValues - deserialized values lost

### ISSUE THREAD

**Issue by stephenlautier** [aspnet/Extensions#1277]
### Describe the bug
Currently when serializing, and then deserialize a `StringValues` object, when deserialized values are being lost

Using `Newtonsoft.Json` for serialization
https://github.com/JamesNK/Newtonsoft.Json/issues/879

### To Reproduce
1. `JsonConvert.SerializeObject`
2. `JsonConvert.DeserializeObject`

### Expected behavior
Data should be deserialized correclty and values are retained.

### Screenshots
![image](https://user-images.githubusercontent.com/3908723/54569191-2ee57a80-49da-11e9-9c37-adba569b1799.png)

**Comment by anurse** [comment]
`StringValues` isn't designed to be serialized directly like this. If you need to use custom types (like `StringValues`) during JSON serialization, I suggest implementing a [custom JsonConverter](https://www.newtonsoft.com/json/help/html/CustomJsonConverter.htm)
