### ISSUE TITLE
Question: MemoryCache and CancellationTokenSource

### ISSUE THREAD

**Issue by kimbell** [aspnet/Extensions#1278]
We have migrated an older ASP .NET Framework app to ASP .NET Core 2.2.3. In this new code we are using MemoryCache and we set up a ```CancellationTokenSource``` so that we can flush the content of the cache. When we started getting production load, the memory usage increased dramatically.

We are not 100% certain that the issue is related to MemoryCache, but that is the only place we use CancellationTokens, so it is our best guess. 

![image](https://user-images.githubusercontent.com/11733077/54595431-e1492c00-4a32-11e9-9bf1-9efac3e82a92.png)

We created a memory dump and discovered that the CanncellationToken related objects consumed a lot of memory. We upgraded to 2.2.3. since that contained a fix related to this area, but we still have an issue. 
```
              MT    Count    TotalSize Class Name
000007fe83d29290    15498    454549680 Microsoft.Extensions.Primitives.IChangeToken[]
000007fed1c81fe0 26172568    837522176 System.Threading.CancellationTokenRegistration
000007fed1c83468 18920744   1513659520 System.Threading.CancellationTokenSource+CallbackNode

            Addr     Size      Followed by
000000010d4fa738    0.6MB 000000010d59f8e8 System.Threading.CancellationTokenRegistration
000000010dae8e48    1.1MB 000000010dc023c0 System.Threading.CancellationTokenRegistration
000000010e17c0a8    0.6MB 000000010e209958 System.Threading.CancellationTokenSource+CallbackNode
000000010f121570    0.6MB 000000010f1c50e8 System.Threading.CancellationTokenRegistration
00000001107a6a20    0.6MB 0000000110833a90 Microsoft.Extensions.Primitives.CancellationChangeToken
0000000110a5c150    0.5MB 0000000110ae34b0 System.Threading.CancellationTokenRegistration
0000000190cae718    0.6MB 0000000190d47080 Microsoft.Extensions.Primitives.CancellationChangeToken
0000000190e47fe8    0.9MB 0000000190f34190 Microsoft.Extensions.Primitives.CancellationChangeToken
00000001912495d8    1.3MB 0000000191399f68 System.Threading.CancellationTokenRegistration
000000019141b8a8    1.3MB 00000001915749c0 Microsoft.Extensions.Primitives.CancellationChangeToken
000000019163c7b0    0.6MB 00000001916da248 Microsoft.Extensions.Primitives.CancellationChangeToken

```
Is it normal that these objects are close to 1 MB?

In our current code, we share a ```CancellationTokenSource``` across all the entries being added to the MemoryCache. 

There seems to be two approaches of adding entries. I'm not sure which one is the best. 

```cs
 using (var entry = _memoryCache.CreateEntry(cacheKey))
            {
                entry.Value = data;
                entry.ExpirationTokens.Add(CreateChangeToken(sourceName));
                entry.AbsoluteExpirationRelativeToNow = expires;
                entry.Size = data.Content.Length;
                entry.Priority = CacheItemPriority.Low;
            }
```
```cs
var entryOptions = new MemoryCacheEntryOptions
            {
                AbsoluteExpirationRelativeToNow = expires,
                Size = data.Content.Length,
                Priority = CacheItemPriority.Low
            };

            entryOptions.ExpirationTokens.Add(CreateChangeToken(sourceName));

            _memoryCache.Set(cacheKey, data, entryOptions);
```

I started exploring the ASP.NET Core codebase to see if I could pick up any tricks in this area. I found some code in the CacheTagHelper that doesn't make things clearer. 

This code is using both the Set and CreateEntry versions. Why? 
Since its disposing of the ```CancellationTokeSource```, I'm guessing it doesn't care about external expiry, so why does it create it at all? 

Is there a specific way we need to use MemoryCache and ```CancellationTokenSource``` together? 
Should we create a new ```CancellationChangeToken``` for each entry, or should we re-use an existing one? 

```cs
private async Task<IHtmlContent> CreateCacheEntry(CacheTagKey cacheKey, TagHelperOutput output)
        {
            var tokenSource = new CancellationTokenSource();

            var options = GetMemoryCacheEntryOptions();
            options.AddExpirationToken(new CancellationChangeToken(tokenSource.Token));
            options.SetSize(PlaceholderSize);
            var tcs = new TaskCompletionSource<IHtmlContent>(creationOptions: TaskCreationOptions.RunContinuationsAsynchronously);

            // The returned value is ignored, we only do this so that
            // the compiler doesn't complain about the returned task
            // not being awaited
            _ = MemoryCache.Set(cacheKey, tcs.Task, options);

            IHtmlContent content;
            try
            {
                // The entry is set instead of assigning a value to the
                // task so that the expiration options are not impacted
                // by the time it took to compute it.

                // Use the CreateEntry to ensure a cache scope is created that will copy expiration tokens from
                // cache entries created from the GetChildContentAsync call to the current entry.
                var entry = MemoryCache.CreateEntry(cacheKey);

                // The result is processed inside an entry
                // such that the tokens are inherited.

                var result = ProcessContentAsync(output);
                content = await result;
                options.SetSize(GetSize(content));
                entry.SetOptions(options);

                entry.Value = result;

                // An entry gets committed to the cache when disposed gets called. We only want to do this when
                // the content has been correctly generated (didn't throw an exception). For that reason the entry
                // can't be put inside a using block.
                entry.Dispose();

                // Set the result on the TCS once we've committed the entry to the cache since commiting to the cache
                // may throw.
                tcs.SetResult(content);
                return content;
            }
            catch (Exception ex)
            {
                // Remove the worker task from the cache in case it can't complete.
                tokenSource.Cancel();

                // Fail the TCS so other awaiters see the exception.
                tcs.TrySetException(ex);
                throw;
            }
            finally
            {
                // The tokenSource needs to be disposed as the MemoryCache
                // will register a callback on the Token.
                tokenSource.Dispose();
            }
        }
```

**Comment by Eilon** [comment]
@sebastienros - any idea on this?

**Comment by kimbell** [comment]
Just to give some more context. This is a REST type of application, no Razor. 

I would imagine ASP.NET uses CancellationTokeSources as part of the request pipeline, but that is not something we can influence. We have other applications that have been running on all versions of NET Core since 1.0 and we haven't seen any issues with those. But in those we don't use Memory cache or CancellationTokenSource. 

This is the first time we are using MemoryCache and CancellationTokeSource, so it's reasonable to suspect we are doing something wrong.

**Comment by Tratcher** [comment]
Pattern aside: There's not much difference between CreateEntry and Set except for an esoteric feature about scoped, nested expiration tokens. Note you should not use `using` with CreateEntry as you don't want to add the entry if something inside that using block throws.

What's going on in CreateChangeToken?

@stephentoub why would a CancellationTokenRegistration show up as 1.3mb?

**Comment by stephentoub** [comment]
What command is that text dump the output of?

**Comment by brandondahler** [comment]
@kimbell Are you using the same instance of CancellationTokenSource for every item (or at least a whole bunch of items) you are adding to the cache?

If so, that probably explains why this is happening -- each time you register a CancellationToken with a CacheEntry, you are adding another entry to the list of callbacks that the CancellationTokenSource must make when you call .Cancel() on that CancellationTokenSource instance.  That would result in the holding list of these callbacks (namely a linked-list of `System.Threading.CancellationTokenSource+CallbackNode`) which would presumably be counted in the inclusive bytes of each item.

**Comment by kimbell** [comment]
@brandondahler  We are using the same CancellationTokenSource instance for multiple cache entries. That seems to be the easiest way of implementing cache flush. 

@stephentoub This is the start of our debugging. 
```

Microsoft (R) Windows Debugger Version 10.0.17763.132 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [D:\temp\New folder (2)\w3wp.DMP]
User Mini Dump File with Full Memory: Only application data is available

Symbol search path is: srv*
Executable search path is: 
Windows 7 Version 7601 (Service Pack 1) MP (4 procs) Free x64
Product: Server, suite: TerminalServer SingleUserTS
Machine Name:
Debug session time: Wed Mar 13 13:10:17.000 2019 (UTC + 1:00)
System Uptime: 20 days 8:17:29.990
Process Uptime: 0 days 1:07:44.000
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
..............
Loading unloaded module list
.........
ntdll!ZwWaitForSingleObject+0xa:
00000000`77a498ca c3              ret
0:000> C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.2.3\sos
Address expression missing from ':\Program Files\dotnet\shared\Microsoft.NETCore.App\2.2.3\sos'
0:000> !dumpheap -stats
No export dumpheap found
0:000> !dumpheap -stat
No export dumpheap found
0:000> !dumpheap -stat
No export dumpheap found
0:000> .load C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.2.3\sos
0:000> !dumpheap -stat
Statistics:
              MT    Count    TotalSize Class Name
000007fed1cb2db0        1           24 System.Collections.Generic.GenericEqualityComparer`1[[System.Int32, System.Private.CoreLib]]
000007fed1cb2be0        1           24 System.Collections.Generic.GenericEqualityComparer`1[[System.Int64, System.Private.CoreLib]]
000007fed1cb1d90        1           24 System.Collections.Generic.GenericComparer`1[[System.Int32, System.Private.CoreLib]]
000007fed1cb1700        1           24 System.Collections.Generic.GenericComparer`1[[System.UInt64, System.Private.CoreLib]]
```

Another thing we can't get our head around is the total number of CallbackNodes and CancellationTokeRegistration. Close to 19 and 26 million seems way excessive compared to our load. Looking at the statistics for the Framework version, we have around 300K requests over the span of 5 hours. When switching to the NetCore version, we ran out of memory in a matter of an hour. 

```
000007fed1c81fe0 26172568    837522176 System.Threading.CancellationTokenRegistration
000007fed1c83468 18920744   1513659520 System.Threading.CancellationTokenSource+CallbackNode
```

**Comment by kimbell** [comment]
We found some code that is a candidate for this problem. 

The code that adds entries to the IMemoryCache is wrapped inside our custom CacheManager class. This class maintains the CancellationTokenSource and handles the cache flush. The method our CacheManager provides to add information to the cache takes in a MemoryCacheEntryOptions. 

We discovered that the code using our CacheManger were basically using singleton instances of MemoryCacheEntryOptions. The result being that every time something was added to the cache, the ExpirationTokens list of the MemoryCacheEntryOptions increased. Since this is a singleton, references are kept and memory cannot be cleaned up. 

We changed the code so that we create a new instance of MemoryCacheEntryOptions when we add stuff to the cache. We have tested it locally and things seem to have improved. We'll let you know how things progress when we get things tested with more realistic load.

**Comment by kimbell** [comment]
Yesterday we deployed a fix to our production environment. Over the last 24 hours, the memory has on average been bellow 600MB, so things are looking a lot better now. 

In some of the ASP.NET Community standups, there has been mentions about Roslyn analyzers to detect problematic code. Having an analyzer for MemoryCacheEntryOptions could save people some grief.
