### ISSUE TITLE
Not seeing version 2.2.0 in release page

### ISSUE THREAD

**Issue by jaydeept** [aspnet/Extensions#1281]
Why I am not seeing the version 2.2.0 in release? I am seeing 2.2.2 and 2.2.0 preview but not the main one.
Also the link: https://github.com/aspnet/Extensions/archive/v2.2.0.zip isn't working.

**Comment by Eilon** [comment]
Hi, there are no release downloads on GitHub. Everything is available either via NuGet or the Microsoft Download Center. Which specific project are you trying to download?

**Comment by jaydeept** [comment]
I think I found what I was looking: https://github.com/aspnet/Extensions/archive/2.2.0.zip
