### ISSUE TITLE
EventLog logger should send a warning to Application log when custom event source can't be created

### ISSUE THREAD

**Issue by anurse** [aspnet/Extensions#1285]
Related https://github.com/aspnet/AspNetCore/issues/8683

If Generic Host is going to use EventLog for logging, using a custom Event Source is more desirable. But you need to be an admin to create a source. If we can't create the source, the EventLog logger should log a warning to the Application log saying "We couldn't create a custom scope. Please have an administrator blah blah blah..."

**Comment by Tratcher** [comment]
https://github.com/aspnet/Extensions/pull/1296
