### ISSUE TITLE
Simplified constructor injection syntax

### ISSUE THREAD

**Issue by apkd** [aspnet/Extensions#1310]
Constructors for dependency injection have always seemed needlessly verbose to me, especially after having seen how nicely [the parameter property syntax](https://www.typescriptlang.org/docs/handbook/classes.html#parameter-properties) works in TypeScript. Consider the following common case (adapted from the [ASP.NET Core fundamentals page](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.2)) of a class with a few dependencies injected via the constructor:

```csharp
public class IndexModel : PageModel
{
    public IndexModel(
        OperationService operationService,
        IOperationTransient transientOperation,
        IOperationScoped scopedOperation,
        IOperationSingleton singletonOperation,
        IOperationSingletonInstance singletonInstanceOperation)
    {
        OperationService = operationService;
        TransientOperation = transientOperation;
        ScopedOperation = scopedOperation;
        SingletonOperation = singletonOperation;
        SingletonInstanceOperation = singletonInstanceOperation;
    }

    public OperationService OperationService { get; }
    public IOperationTransient TransientOperation { get; }
    public IOperationScoped ScopedOperation { get; }
    public IOperationSingleton SingletonOperation { get; }
    public IOperationSingletonInstance SingletonInstanceOperation { get; }
}
```

In the constructor we're forced to define a parameter for each injected service. Should we call it differently from the properties we're assigning to, or do we use the same name and the `this` prefix? What naming rule should we use? And how do we make sure that we don't assign the field/property or the parameter to itself by mistake?

Looking to save a few characters, I've come across some people using the C# 7 tuple deconstruction syntax. When we make it as compact as we can, it looks like this:

```csharp
public IndexModel(OperationService a, IOperationTransient b, IOperationScoped c, IOperationSingleton d, IOperationSingletonInstance e)
    => (OperationService, TransientOperation, ScopedOperation, SingletonOperation, SingletonInstanceOperation) = (a, b, c, d, e);
```

Now, this already saves us a lot of lines. But then, what if the DI container allowed us to go a step further and inject a tuple?

```csharp
public IndexModel((OperationService, IOperationTransient, IOperationScoped, IOperationSingleton, IOperationSingletonInstance) dependencies)
    => (OperationService, TransientOperation, ScopedOperation, SingletonOperation, SingletonInstanceOperation) = dependencies;
```

Now we only need to name one parameter (and we don't ever need to rename it while adding/removing injected properties). Refactoring is easier and it is impossible to assign a variable to itself.

I do realize that this issue is unlikely to get much traction (given the DI library's focus on simplicity) but I figured that I'd start a discussion anyway.

**Comment by anurse** [comment]
We don't have plans to implement this kind of logic in the built-in DI library at this time. As you said, we are focused on a simple implementation that meets the needs for ASP.NET Core apps. Perhaps other DI container implementations might be interested in this though!
