### ISSUE TITLE
Consider patching https://github.com/aspnet/Extensions/issues/1041 in 2.2

### ISSUE THREAD

**Issue by rynowak** [aspnet/Extensions#1311]
## Impact

It's not possible to set the `Period` of the health check publisher hosted service without using reflection. The wrong backing field is set.

This isn't very discoverable because the bug manifests in a setting not being honoured. You might think you are publishing health data every 30 seconds, but it's going to always use the default period.

## Workaround

The workaround is to use reflection. 

## Risk

The risk here is that someone is setting `Period` - which actually sets `Delay` and they are relying on this detail. If a user actually wanted to set `Delay`, they can already do that.

**Comment by guardrex** [comment]
> The workaround is to use reflection.

I see some examples of how this is done around the Net. Should I add an example to show the reflection workaround in the topic's WARNING? ...

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-2.2#health-check-publisher

**Comment by rynowak** [comment]
Yeah, I think this would be worth adding for now.

**Comment by Eilon** [comment]
Showing a reflection workaround in the docs? I'd rather not...

**Comment by rynowak** [comment]
What workaround would you prefer?

**Comment by Eilon** [comment]
We can post a workaround in this issue, but I don't think having a hack in our docs is a good idea.

**Comment by guardrex** [comment]
The issue is already crosslinked, so we're good on the docs side.

**Comment by Eilon** [comment]
Looks like fix in https://github.com/aspnet/Extensions/pull/1312 was merged.

Let's keep this bug open until after we've verified the fix is in the final build.

**Comment by rynowak** [comment]
Done and verified
