### ISSUE TITLE
VS version is higher than the VS version available to download

### ISSUE THREAD

**Issue by kshyju** [aspnet/Extensions#1330]
Pulled the latest from master, ran `restore.cmd` and then `startvs.cmd` . Getting the error message about VS version of solution is higher!

![image](https://user-images.githubusercontent.com/144469/55203877-47982200-518a-11e9-9672-c6f775dc9d04.png)

My VS 2019 is up to date as per the "Check updates" result window.

![image](https://user-images.githubusercontent.com/144469/55203904-5f6fa600-518a-11e9-82fb-3cc23692ebc8.png)

Appreciate any help :)

**Comment by Eilon** [comment]
Hi, you'll need to use the pre-release version of Visual Studio 2019 to open these solutions.

**Comment by kshyju** [comment]
Thanks! Is that the daily VS build ? Where can I download it ? I do have 2019 Preview V 16.0.0. Preview 4.4 as of this writing and still getting the same error.

**Comment by Eilon** [comment]
@ryanbrandenburg / @dougbu - do you know exactly which VS2019 is required to open the SLN here?

**Comment by dougbu** [comment]
I suspect it's a subset of what we require for aspnet/AspNetCore:
```
      "versionRange": "[16.0.28608.199, 17.0)",
      "requiredWorkloads": [
        "Microsoft.VisualStudio.Component.VC.ATL",
        "Microsoft.VisualStudio.Component.VC.Tools.x86.x64",
        "Microsoft.VisualStudio.Component.VC.v141.ATL",
        "Microsoft.VisualStudio.Component.VC.v141.x86.x64",
        "Microsoft.VisualStudio.Component.Windows10SDK.17134"
      ]
```

**Comment by Eilon** [comment]
Any idea what version that actually translates into?

**Comment by dougbu** [comment]
VS 2019 RC Community with the Managed Desktop and .NET Core Tools should be more than enough to build this repo.

If not, the "required workloads" are actually ids of components on top of the basic Managed Desktop and .NET Core Tools workloads. I'd add the Windows 10 SDK first because the rest are Visual C and I don't see any C or C++ source in this repo.

**Comment by Eilon** [comment]
Thanks, @dougbu !
