### ISSUE TITLE
Microsoft.Extensions.Hosting.WindowsServices - detect running as Windows Service?

### ISSUE THREAD

**Issue by drmcclelland** [aspnet/Extensions#1337]
Within my console application's Main() method, I am trying to detect whether the app is running as a Windows Service vs running as a console app.

When my code is running as a Windows Service, I want to do certain things - but if I'm just running the EXE from the command line I'd like it to do other things.

I have seen this approach used, but is requires an extra command line parameter:  https://github.com/stevejgordon/IHostedServiceAsAService/blob/de55562bb1e424973660892e71b67a6c8200bfc3/IHostedServiceAsAService/Program.cs#L11-L29

And I saw the IsWindowsService() static method in <code>Microsoft.Extensions.Hosting.WindowsServices</code>, but it's private:  https://github.com/aspnet/Extensions/blob/898f0947fa4271d08e88daea503be6fd8ffb3c4f/src/Hosting/WindowsServices/src/WindowsServiceLifetimeHostBuilderExtensions.cs#L54-L67

**Comment by glennc** [comment]
@Tratcher Does it seem reasonable to make this an extension method on something like `IHostEnvironment` rather than its current home?

**Comment by Tratcher** [comment]
No reason to make it an extension method, it's completely static. We could move it to a new type like ServiceHelpers.

**Comment by drmcclelland** [comment]
Just tried to contribute my first PR #1369 to help out   :-)
