### ISSUE TITLE
Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=2.2.0.0

### ISSUE THREAD

**Issue by ygoe** [aspnet/Extensions#1376]
### Describe the bug
Starting my app I get this output and then it dies:

> Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

This has worked with .NET Core 2.1 but fails with 2.2. Lots of other things have changed, I have no details on those.

What does that error mean? I'm not using this namespace, it must be something that runtime needs and has added. I know nothing about that.

### To Reproduce
Sorry, no details available, it's a complex application in pre-production that is now not running. It uses EF Core.

### Expected behavior
No error

### Additional context
A self-contained publishing works. So it must be a problem with the installed .NET Core runtime. I guess installing the runtime on a production system is a bad idea anyway. I'm going to clean up my workflow and only use self-contained builds in the future to avoid such errors.

`dotnet --info`:

```
.NET Core SDK (gemäß "global.json"):
 Version:   2.1.400
 Commit:    8642e60a0f

Laufzeitumgebung:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.400/

Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84

.NET Core SDKs installed:
  2.0.3 [/usr/share/dotnet/sdk]
  2.1.4 [/usr/share/dotnet/sdk]
  2.1.400 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by davidfowl** [comment]
> Sorry, no details available, it's a complex application in pre-production that is now not running. It uses EF Core.

You're going to have a make an effort to give us a repro (unless somebody else is aware of a known issue here).
