### ISSUE TITLE
[Question] - Creating targeting packs

### ISSUE THREAD

**Issue by dazinator** [aspnet/Extensions#1386]
### Is your feature request related to a problem? Please describe.
No problem but it relates to a part of the workflow used in this repo. Having seen the "eng" directory in this repo, I see that this team has a way of producing reference assemblies for targeting packs.

I'd like to create my own targeting pack as a learning exercise. I'd love to know what the end to end process is for generating a reference assembly, right through to being able to create a project in VS and select that targeting pack. Does the team have any useful resources to suggest for this learning excercise?

**Comment by Eilon** [comment]
@natemcmaster - is this more of an SDK thing? Or are we using "custom" stuff from Arcade?

**Comment by natemcmaster** [comment]
>  I'd love to know what the end to end process is for generating a reference assembly, right through to being able to create a project in VS and select that targeting pack.

I'll provide pointers on the first one, but there is no story for creating custom targeting packs or using them in VS. Targeting packs are a feature (for now) reserved for use by the .NET team itself.

Reference assembly info:

* https://oren.codes/2018/07/03/create-and-pack-reference-assemblies/ and https://oren.codes/2018/07/09/create-and-pack-reference-assemblies-made-easy/ walks you how to use the "generate reference assemblies" feature of the C# compiler
* For servicing reasons, we don't generate ref assemblies on the fly, but instead use https://github.com/dotnet/arcade/tree/master/src/Microsoft.DotNet.GenAPI (currently undocumented.) This console tool reads a .dll file and emits C# source to match the public API
* https://github.com/dotnet/standard/blob/master/docs/history/evolution-of-design-time-assemblies.md - explanation of ref assemblies in general and why the .NET team uses them

Targeting pack info:
* https://github.com/dotnet/designs/pull/50 is the most recent version of @nguerrera's spec on .NET Core 3 targeting packs. It might be a little out of date now, but it's good overview of how the .NET team is thinking about this subject.

Hope that helps. Closing, but feel free to continue discussion.

**Comment by dazinator** [comment]
Thanks ever so much @natemcmaster , that has given me plenty to digest for the meantime ;-)
