### ISSUE TITLE
Project namespace optimize

### ISSUE THREAD

**Issue by xyz0822** [aspnet/Extensions#1423]
I'm am trying to debug the source code, and i found the namespace not as the same as the project name, like the project **Microsoft.Extensions.DependencyInjection.Abstractions**,but classes in it with **Microsoft.Extensions.DependencyInjection** namespace? why not  **Microsoft.Extensions.DependencyInjection.Abstractions**?

**Comment by xyz0822** [comment]
in my worktime,i often segguested them to keep the namespace as the same as the project name if i found like above, cause when u trying to found the class,u may confused and not abled to found the class when the class`s namespace not as the same as project name,in that time, u can only to search in the whole project to find the class.

**Comment by xyz0822** [comment]
update then issue name

**Comment by Eilon** [comment]
Hi, this was done on purpose and it would be a breaking change if we changed it, so we do not plan on any changes to this.

**Comment by xyz0822** [comment]
> Hi, this was done on purpose and it would be a breaking change if we changed it, so we do not plan on any changes to this.

Hi,I just wonder if visual studio could stepped into source code by F12(download online or attached source code zip like 'Microsoft.Extensions.DependencyInjection.zip') not metadata by namespace  in the future, would the namespace that differefent project have the same that we do now could be a difficuit to visual studio team ? or even like the class **CacheItemPriority** with the namespace **Microsoft.Extensions.Caching.Memory** in the project **Microsoft.Extensions.Caching.Abstractions**

**Comment by Eilon** [comment]
@xyz0822 that should work as long as you enabled stepping into source code, and you have enabled the Microsoft Symbol Servers. Then you can step into most Microsoft code.

**Comment by xyz0822** [comment]
@Eilon Thanks for your reply.
