### ISSUE TITLE
Remove incorrect ArrayBufferWriter usage in Logging

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/Extensions#1464]
In the EventSource logger we are currently relying on `ArrayBufferWriter` being in the Microsoft.Bcl.Json.Sources package and using it from there.
https://github.com/aspnet/Extensions/blob/0a8f632248f4ec652935f0c9dc9b06ff82c3c97c/src/Logging/Logging.EventSource/src/EventSourceLogger.cs#L210

We should instead switch to a "real" implementation and not rely on the sources package.

cc @anurse

**Comment by BrennanConroy** [comment]
This is now semi-urgent. We'll be switching to a package instead of sources so the `ArrayBufferWriter` we were using wont be available.
See https://github.com/dotnet/corefx/pull/37129

**Comment by dougbu** [comment]
fd3dbc6b0eb7
