### ISSUE TITLE
RunConsoleAsync: Prevent interruption of ongoing work

### ISSUE THREAD

**Issue by johnknoop** [aspnet/Extensions#1546]
I have a few console apps that subscribe to messages off an Azure Service Bus queue. Some of these handlers aren't idempotent, and there are typically always two things that need to happen atomically:

1. Carry out whatever side-effect it is supposed to do, like save something to a database
2. Flag the service bus message as completed

When a message arrives I always check the cancellation token to see if termination has begun, and in this case I just abandon the message and short-circuit out. But if termination _hasn't_ begun, I want to carry out the two operations mentioned above and be sure the program won't be interrupted inbetween them, because, as I stated above, not all of these handlers are idempotent (I rely on deduplication of messages in these cases), so I don't want to save something to db and then fail to flag the message as completed, because then it'll be consumed again and I'll end up with two things in the database.

Is this achievable with the tools in this repo? So far I haven't found a way, so I've written my own [GracefulConsoleRunner](https://github.com/johnknoop/GracefulConsoleRunner), but I would be much happier using something that already exists in the framework.

**Comment by davidfowl** [comment]
Isn't this inherently racy? What sort of guarantee are you looking for? What if the power goes off between those 2 operations? There are other ways to achieve atomiticy.

**Comment by johnknoop** [comment]
Hi @davidfowl 

Well, preferably I would love the level of guarantee of atomicity that for example a transaction would provide. And I know that the service bus client can register itself with an ambient TransactionScope, but unfortunately the MongoDb driver cannot, so I'm afraid I'll have to settle with some weaker mechanism.

My own solution isn't water tight, and the power outage example you mention is a good example of something it wouldn't handle. But apart from those extreme corner cases, it makes a good enough job of making sure the handling of a message is allowed to complete without being interrupted (within a graceperiod). The way I implemented this is with a [WorkWrapper](https://github.com/johnknoop/GracefulConsoleRunner/blob/master/src/WorkWrapper.cs) class that providers the interface of an IDisposable, and internally holds a Task which is completed when the object is disposed, so the runner can await any outstanding task(s) before exiting. In my own opinion it makes for a pretty nice API.

The way I see it, one of these three things is true:
a) I'm designing for a case that cannot happen since it's inherently solved by the framework somehow waiting for all running code to complete
b) there's a feature in the Microsoft.Extensions.Hosting namespace that would solve this, that I'm not aware of
c) it's a case that is currently not supported by the Microsoft.Extensions.Hosting constructs, in which case I'll either stick with my own code or write a plugin or something.

I don't think it's vulnerable to race conditions (or I hope, but both me and a co-worker have looked at the code quite long).

**Comment by davidfowl** [comment]
> b) there's a feature in the Microsoft.Extensions.Hosting namespace that would solve this, that I'm not aware of

I think you're looking for is the generic host https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.2. 

> c) it's a case that is currently not supported by the Microsoft.Extensions.Hosting constructs, in which case I'll either stick with my own code or write a plugin or something.

I think it is supported because the generic host has a graceful shutdown concept but I'm not completely clear what sort of guarnatees you want to get. I still think you should use reliable storage if you *really* want atomicity but if you're ok with basic with the grace period then IHostedService is what you want https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.2

> I don't think it's vulnerable to race conditions (or I hope, but both me and a co-worker have looked at the code quite long).

It is, but you're likely narrowing the chances by having a long grace period.

**Comment by johnknoop** [comment]
Hi again @davidfowl 

I'm not sure how I could get GenericHost to wait for my message processing to complete before terminating.

I tried this simple example:

```csharp
static async Task Main(string[] args)
{
	var hostBuilder = new HostBuilder();

	hostBuilder.ConfigureServices(x => x
		.AddHostedService<MyListener>()
	);

	await hostBuilder.RunConsoleAsync();
}
```
This is my hosted service:
```csharp
internal class MyListener : IHostedService
{
	public Task StartAsync(CancellationToken cancellationToken)
	{
		var timer = new System.Timers.Timer();

		Console.WriteLine("Started listening...");

		timer.Interval = 1000;
		timer.Elapsed += (sender, args) =>
		{
			Console.WriteLine("Processing message...");
			Task.WaitAll(Task.Delay(5000));
			Console.WriteLine("Done");
		};

		timer.Start();

		return Task.CompletedTask;
	}

	public Task StopAsync(CancellationToken cancellationToken)
	{
		Console.WriteLine("Closing down");
		return Task.CompletedTask;
	}
}
```
After one second, the timer event fires to simulate a message arriving on the bus. If I press CTRL+C after I see the "Processing message..." line in the output, it terminated immediately without allowing the timer event to complete.

About the other solution... if you have the time, would you mind explaining how a race condition would occur? I'm probably not seeing what you see :P

Thanks

**Comment by davidfowl** [comment]
Here's what the code would look like;

```C#
public class MyListener : IHostedService
{
    private TaskCompletionSource<object> _completingWork;

    public Task StartAsync(CancellationToken cancellationToken)
    {
        var timer = new System.Timers.Timer();

        Console.WriteLine("Started listening...");

        timer.Interval = 1000;
        timer.Elapsed += (sender, args) =>
        {
            Console.WriteLine("Processing message...");
            Task.WaitAll(Task.Delay(5000));
            Console.WriteLine("Done");

          // Signal that work has completed
            _completingWork?.TrySetResult(null);
        };

        timer.Start();

        return Task.CompletedTask;
    }

    public async Task StopAsync(CancellationToken cancellationToken)
    {
        Console.WriteLine("Closing down");

        // Create a tcs to wait on for either cancellation of waiting of outstanding work to complete
        _completingWork = new TaskCompletionSource<object>();

        // The token will fire when the graceful period runs out
        cancellationToken.Register(state => ((TaskCompletionSource<object>)state).TrySetCanceled(), _completingWork);

        try
        {
            await _completingWork.Task;
            // Gracefully completed
        }
        catch (OperationCanceledException)
        {
            // Ungraceful!

        }
    }
}
```

The token passed in will fire when the grace period ends.

PS: The sample allows overlapping work to happen so the console output is a little weird.

**Comment by davidfowl** [comment]
> About the other solution... if you have the time, would you mind explaining how a race condition would occur? I'm probably not seeing what you see :P

If any operation takes longer than the grace period then it won't work.

**Comment by johnknoop** [comment]
> Here's what the code would look like;

Aha, I thought you meant it was already implemented in the GenericHost somehow. Now I'm with you. Although you'd need to create a new TaskCompletionSource everytime the timer fires since there will be multiple messages arriving at the bus. That's basically what my other solution does. I'll probably re-write it as an extensionmethod to the hostbuilder.

> If any operation takes longer than the grace period then it won't work.

Oh, yes. That's why it's called a graceperiod :) Don't think that counts as a race condition though.

Anyway, thanks a lot that you took the time, appreciate it!

**Comment by davidfowl** [comment]
> Aha, I thought you meant it was already implemented in the GenericHost somehow. 

The generic host lets you configure a shutdown timeout, its up to you to wait on the token and it will fire once that timeout fires.

> Now I'm with you. Although you'd need to create a new TaskCompletionSource everytime the timer fires since there will be multiple messages arriving at the bus. That's basically what my other solution does. I'll probably re-write it as an extensionmethod to the hostbuilder.

Are you doing work in parallel? Then sure, you need a way to work on the outstanding work, I'm not sure you need a new TCS per work item and it's only needed when you're shutting down.

> Oh, yes. That's why it's called a graceperiod :) Don't think that counts as a race condition though.

I wouldn't describe what you're doing as atomic in any way shape or form. It's a best effort and it can go horribly wrong if things fail or suddenly die (which happens in the real world 😄 ). As long as you understand those caveats then it's fine.

**Comment by johnknoop** [comment]
Yeah, work can happen in parallel unfortunately. In the service bus scenario, you tell the IReceiveClient what max level of concurrency you want. That's why I went for a BlockingCollection to hold all the unfinished tasks.

I'm not sure if there might be a whole different approach to tackle the problem in another way. Just in high level terms.. how would you go about solving the  problem? The goal is basically that we wanna mimic the behaviour of AspNetCore in the way it drains all ongoing requests before it shuts down. But instead of HTTP requests, in my case it's messages arriving on a service bus. And the complicating factor is that the operation I need to carry out for these messages cannot be registered with a TransactionScope. And also, I wanna be able to set a timeout/grace period, so that if the processing of one message doesn't finish, it will be interrupted.

Is there some totally different way to attack this problem in your perspective?

Cheers

**Comment by davidfowl** [comment]
> I'm not sure if there might be a whole different approach to tackle the problem in another way. Just in high level terms.. how would you go about solving the problem?

Which problem specifically? Graceful shutdown is easy just use the algorithm I describe above (keeping track of the count of outstanding work and waiting for it to get to 0).

If you're asking how to guarantee the dequeue and the database operation happen atomically then I think you'd need to design a process that can handle duplicate messages or resume from partially complete operations. Or live with the occasional weirdness that might happen between dequeue and the database operation. I know some queues have features like this https://docs.microsoft.com/en-us/rest/api/servicebus/peek-lock-message-non-destructive-read that might aid in writing more reliable logic

**Comment by johnknoop** [comment]
> Graceful shutdown is easy just use the algorithm I describe above (keeping track of the count of outstanding work and waiting for it to get to 0).

That's in a nutshell what I'm doing in my solution. I just got the impression that there might be a totally different way to attack it, sorry for the misunderstanding :P

Have a nice weekend!
