### ISSUE TITLE
MemoryCacheItem PostEvictionCallbacks async handlers

### ISSUE THREAD

**Issue by ronMilne** [aspnet/Extensions#1624]
Is it ok to declare the lambda as async as i need to call the evicted item to perform cleanup. Which includes awaiting.
```
 entry.RegisterPostEvictionCallback(async (K, V, R, S) => { /* await calls here */ });
```

**Comment by Tratcher** [comment]
That will be `async void`, memory cache won't await your call. There are many hazards of using `async void`, but it's possible.

**Comment by anurse** [comment]
Closing, as the question has been answered. The cache will continue invoking callbacks without waiting for your async operation to complete, but you can use `async`.
