### ISSUE TITLE
EnvironmentVariables config provider default behavior is unexpected/unwanted

### ISSUE THREAD

**Issue by bradwilson** [aspnet/Extensions#1650]
### Describe the bug

The `EnvironmentVariablesConfigurationSource` class has unexpected (and undesirable) behavior with respect to how configuration properties are filled. It does not take into account the requested configuration section when choosing an appropriate variable to fill in a missing configuration name. This results in two separate, related problems:

1. Configuration properties are unexpectedly filled in from generic environment variable names;
2. It is impossible to differentiate between option properties with the same property name.

### To Reproduce

Start with two configuration classes: (this is slimmed down from a real-world repro)

```csharp
public class LoggingOptions
{
    private string _hostName;

    // Host name of the logging server
    public string HostName
    {
        get => string.IsNullOrWhitespace(_hostname) ? "localhost" : _hostName;
        set => _hostName = value;
    }
}

public class MetricsOptions
{
    private string _hostName;

    // Host name of the metrics server
    public string HostName
    {
        get => string.IsNullOrWhitespace(_hostname) ? "localhost" : _hostName;
        set => _hostName = value;
    }
}
```

With configuration set up like this:

```csharp
services.Configure<LoggingOptions>(_config.GetSection("Logging"));
services.Configure<MetricsOptions>(_config.GetSection("Metrics"));
```

For traditional JSON-based configuration, you would write:

```json
{
    "Logging": {
        "HostName": "logging-service"
    },
    "Metrics": {
        "HostName": "metrics-service"
    }
}
```

**When providing configuration values**, this works as expected. The two related issues come about when **attempting to utilize the default values** for the options classes.

First, we have the problem of naming. Because the environment variable configuration system is "section"-ignorant, we have two default values covered by only a single potential environment variable: `HOSTNAME`. I would have expected that these got mapped to `LOGGING_HOSTNAME` and `METRICS_HOSTNAME` respectively (plus any prefixes, of course). In the current system, it's impossible for me to configure these two different values with two separate environment variables because they're both fed by just `HOSTNAME`. (Renaming the properties is not an acceptable workaround, as it invalidates the entire purpose behind configuration sections in the first place.)

Second, we have the problem of "section"-ignorance ending up filling in values when property names match commonly used environment variables. On an empty Alpine Docker container, that means we have at least 6 unintentionally "reserved" names which cannot align with property names:

```bash
$ docker run --rm -it alpine ash -c export
export HOME='/root'
export HOSTNAME='a85f54237ac4'
export PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
export PWD='/'
export SHLVL='1'
export TERM='xterm'
```

Other environments (Windows vs. Linux, different distros, addition of software--including runtimes like .NET Core, NodeJS, etc.) will naturally grow this list in possibly unpredictable ways.

### No Full Workaround

There is no full workaround that fixes both of these problems, without writing our own custom environment variable configuration provider.

Today we are forced to remove the default environment variables provider. Replacing the default with one that uses a prefix isn't actually a full workaround, because it only fixes the "clashes with well known environment variables" problem, and not the "collision of `LoggingOptions.HostName` vs. `MetricsOptions.HostName`" problem.

**Comment by Eilon** [comment]
@Tratcher / @HaoK / @anurse / @ajcvickers / @glennc - any thoughts on this? Is this expected?

**Comment by anurse** [comment]
> we have two default values covered by only a single potential environment variable: `HOSTNAME` ...  In the current system, it's impossible for me to configure these two different values with two separate environment variables because they're both fed by just `HOSTNAME`.

This is surprising to me. My understanding is that [environment variables use `__` (two `_` characters) as the section mapping](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.2#environment-variables-configuration-provider). So it should be `LOGGING__HOSTNAME` and `METRICS__HOSTNAME`. If `HOSTNAME` is filling in both values, that seems like a bug to me.

**Comment by anurse** [comment]
I don't think I can repro this from your description, I tried here: https://github.com/anurse/EnvVarRepro_AspNet. Granted, I'm using 3.0 but I don't think anything changed in this regard here. Am I missing something in my repro that is relevant to your environment?

**Comment by anurse** [comment]
I backported that sample app down through 2.2 and 2.1 and still can't reproduce the issue.

**Comment by bradwilson** [comment]
When creating the repro, I realized there was a piece missing from the description: the setup class.

Here is my repro project: https://github.com/bradwilson/aspnet-extrensions-1650

I'm using VS Code, and the `tasks.json` sets up a `dotnet watch run` which includes setting the problematic environment variable.

Commenting out this line makes the bug go away: https://github.com/bradwilson/aspnet-extrensions-1650/blob/51247f44c76aa4c5c675f9731e42ca8fb18ebd5a/Startup.cs#L22

Without line 22:

```
$ curl -k https://localhost:5001/api/values
{"foo":"Default Value"}
```

With line 22:

```
$ curl -k https://localhost:5001/api/values
{"foo":"Invalid value from environment"}
```

(The actual code that has failures is also registering `IOptionsChangeTokenSource<T>`, but that did not appear to be necessary to repro the issue.)

So questions:

1. Is `IConfigureOptions<T>` & `IOptionsChangeTokenSource<T>` still a supported thing?
2. Am I holding it wrong?

**Comment by HaoK** [comment]
I'll take a look

**Comment by HaoK** [comment]
Sorry for the super long delay but, I ran the repo app, and hopefully can provide some clarity...

So `FooSetup : ConfigureFromConfigurationOptions<FooOptions>` is basically just sugar for doing binding the configuration (from DI) against the options:

`services.Configure<FooOptions>(o => ConfigurationBinder.Bind(config, o)`

https://github.com/aspnet/Extensions/blob/730c5d93b2e3f2dc0f045c90e79ad9443ea169da/src/Options/ConfigurationExtensions/src/ConfigureFromConfigurationOptions.cs#L23

So the binder is what's doing the setting of any properties that match the section with the value of the section.

I'm not clear exactly what default behavior you want for your hostnames (assuming the issue is you have multiple config files and the default hostname ends up being last one wins).  You could do your own config -> options binding to make it only bind these default properties if the value was unset if you want first one wins?

**Comment by bradwilson** [comment]
So are you saying that setup classes are unnecessary?

**Comment by HaoK** [comment]
I'm not sure if they are unnecessary, but specifically FooSetup https://github.com/bradwilson/aspnet-extrensions-1650/blob/master/FooSetup.cs from ConfigureFromConfigurationOptions is what is explicitly binding all properties from the config to the FooOptions.

But as you mentioned in your original post, there isn't really a built in simple way to do what you are trying to do, i.e. easily tease apart values where multiple configuration providers are defining the same value.  Configuration just exposes key/value pairs to the configuration options binder, which just naively binds those to the poco's properties via reflection

**Comment by bradwilson** [comment]
I guess, allow me to be more explicit: do I need the XxxSetup classes if I want to force the users to register their configuration wire-up via:

```csharp
services.Configure<LoggingOptions>(_config.GetSection("Logging"));
```

It sounds like what you're saying is the Setup class allows users to forego explicit configuration registration. I'm fine with requiring the above code, because it's in all of our "new app" templates.

**Comment by HaoK** [comment]
Nope you don't have to have the setup classes, they are just different ways of registering IConfigureOptions, configure is the most common.  They actually end up doing similar things, the slight yet important difference is you are passing in a specific section to bind in the configure, while the setup is binding against the root configuration from DI.
