### ISSUE TITLE
Smarter default addition of ConsoleLoggerProvider?

### ISSUE THREAD

**Issue by martincostello** [aspnet/Extensions#1706]
### Is your feature request related to a problem? Please describe.

While creating the repro for #1691, it occurred to me that in the context from where the original issue came, which was an xunit test for an app, there was no real reason for the console logger to even be there in the first place as there was no console to even output to as xunit redirects it.

If there's no console there, like in an IIS-hosted web app, it seems a bit pointless to add the extra logger overhead and allocations for something that then just disappears into the void.

It's perfectly possible that there's other reasons (like redirected output) where actually this is a bad idea, but I figured I'd ask the question rather, even if it's a stupid one.

I put together a benchmark in this repo that compares the default, no console at all and a "smart" check that doesn't register the console if stdout and stderr are both redirected: https://github.com/martincostello/No-Console-Perf

This "smart" check is just simply `bool useConsole = !Console.IsErrorRedirected || !Console.IsOutputRedirected` ([link](https://github.com/martincostello/No-Console-Perf/blob/ecf29bf26ae70466a98850b1704eba74da1f455c/ServerBenchmarks.cs#L121)).

This gives some marginal improvement as per the results from one of the runs on my laptop:

``` ini

BenchmarkDotNet=v0.11.5, OS=Windows 10.0.17763.437 (1809/October2018Update/Redstone5)
Intel Core i7-6700HQ CPU 2.60GHz (Skylake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.0.100-preview5-011568
  [Host]     : .NET Core 3.0.0-preview5-27626-15 (CoreCLR 4.6.27622.75, CoreFX 4.700.19.22408), 64bit RyuJIT
  DefaultJob : .NET Core 3.0.0-preview5-27626-15 (CoreCLR 4.6.27622.75, CoreFX 4.700.19.22408), 64bit RyuJIT


```
|           Method |     Mean |    Error |   StdDev | Ratio | RatioSD | Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------- |---------:|---------:|---------:|------:|--------:|------:|------:|------:|----------:|
|      WithConsole | 210.1 us | 4.107 us | 5.758 us |  1.00 |    0.00 |     - |     - |     - |   2.09 KB |
|        NoConsole | 205.4 us | 2.676 us | 2.503 us |  0.99 |    0.03 |     - |     - |     - |   2.09 KB |
| WithSmartConsole | 201.4 us | 3.213 us | 3.006 us |  0.97 |    0.03 |     - |     - |     - |   2.09 KB |

From looking at the code the main benefit is new needing to allocate the `ConsoleLogger` instances for each log type (in the app the original issue came from there were about 270 of them), removing the need for the background processing thread and the message formatting:

https://github.com/aspnet/Extensions/blob/b7b79d8202765f2758d47fcff4bf29ef91bc9380/src/Logging/Logging.Console/src/ConsoleLoggerProvider.cs#L15

https://github.com/aspnet/Extensions/blob/b7b79d8202765f2758d47fcff4bf29ef91bc9380/src/Logging/Logging.Console/src/ConsoleLoggerProcessor.cs#L22-L28

https://github.com/aspnet/Extensions/blob/b7b79d8202765f2758d47fcff4bf29ef91bc9380/src/Logging/Logging.Console/src/ConsoleLogger.cs#L80-L121

### Describe the solution you'd like

A reliable best guess way to check if the console is not available is made in `Host.CreateDefaultBuilder()`, and only calls `AddConsole()` if there is a chance the console actually exists.

Alternatively, there could be a simple extension method and/or option to allow it to be explicitly opted out of. For example:

```csharp
var host = Host.CreateDefaultBuilder()
    .ConfigureLogging((builder) => builder.RemoveConsole())
    .Build();
```

### Describe alternatives you've considered

It's possible to remove the console logger already if desired using methods such as the below, but given the console is present by default in the templates and would be used by most people, there's some redundant overhead in scenarios like IIS hosting where there's no console to see the messages output anyway.

  * Call `ClearProviders()` manually and add all the defaults back in manually.
  * Enumerate the registered services manually before startup and remove `ConsoleLoggerProvider` as a registration for `ILoggerProvider`.

**Comment by anurse** [comment]
We definitely still want to register the logger if stdout and stderr are redirected. The IIS hosting models expect to be able to scrape the console logs by exactly this mechanism. It's used to forward console output to a file. Also, scraping the console logs is a common pattern in Linux service models (like systemd). We can't really know the difference between something that has redirected the console because it wants to collect it, and something that has redirected it to `/dev/null`.

> Alternatively, there could be a simple extension method and/or option to allow it to be explicitly opted out of. For example:

I'm not sure adding the extension method really adds a lot of value, and we wouldn't be doing this for every logger provider so Console would end up special cased here. The default builder (`CreateDefaultBuilder`) is intentionally opinionated, but you're always free to create your own host builder to configure everything from scratch (and `ClearProviders` exists to let you reset the logger providers).

> I figured I'd ask the question rather, even if it's a stupid one.

No such thing as a stupid question! Glad to have the discussion, especially with the background research you've done here!

I don't think there's a change we'd make here given that removing the Console logging is a fairly marginal improvement (by the data you showed above). Especially since startup is not as *hot* as per-request performance, since it only happens once.

**Comment by martincostello** [comment]
Thanks for the explanation - that all makes a lot of sense.

I hadn't considered that IIS hosting expects to scrape the console and things like that, so I guess those are all the things I'm not aware of that explain why it's baked in by default.

I was more interested in the per-request performance from all the string building to make the log entries and cope with the background thread processing the logger messages that potentially aren't actually doing anything, but as the numbers show and you've said the overhead of that is marginal.

I guess for scenarios that really care enough and definitely know the console is completely pointless, then they can manually de-configure it and configure everything they need themselves.

I'll close this issue now everything's been nicely rationalised 😃
