### ISSUE TITLE
Do not return an IDisposable HttpClient from factory methods if it's not intended to be disposed by callers

### ISSUE THREAD

**Issue by joeyj-msft** [aspnet/Extensions#1710]
### Describe the bug
HttpClients are pooled/managed by IHttpClientFactory; however, HttpClient is IDisposable--indicating it needs to be disposed. This causes false positives in Code Analysis and each developer has to read the documentation and suppress them. We can prevent this by returning an object that isn't IDisposable and make it clear via the contract we don't expect the caller to dispose.

### Expected behavior
IHttpClientFactory should not return objects that are IDisposable

### Docs
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.1#httpclient-and-lifetime-management

**Comment by rynowak** [comment]
There's no meaningful change we can do here. We're not going to introduce another type besides `HttpClient`.

This is also already a documented use-case for `HttpClient` independent of the factory: https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.-ctor?view=netframework-4.8#System_Net_Http_HttpClient__ctor_System_Net_Http_HttpMessageHandler_System_Boolean_

Disposing an `HttpClient` instance may or may not close underlying connections depending on how it was constructed.
