### ISSUE TITLE
Question: AppConfiguration, how is the order of precedence defined?

### ISSUE THREAD

**Issue by TheReaLee** [aspnet/Extensions#1711]
We are using the  WebHost.CreateDefaultBuilder(args) method which automatically adds several app configurations automatically... Furthermore we are then adding AzureKeyVault and AzureApp Configuration Providers...

My question is, which configuration provider has precedence over the other?

I conducted some tests and need someone to confirm whether the results are correct

After several tests the following is confirmed. The order of precedence is defined by the last App Configuration configured.
Note: Let's say we are using the CreateDefaultBuilder and require environment variables to have precedence, if we are to re-configure them in program.cs last we will have duplicate configurations as seen in the IConfiguration.Provideers section:

- [0] ChainedConfigurationProvider
- [1] JsonConfigurationProvider
- [2] JsonConfigurationProvider
- [3] EnvironmentVariablesConfigurationProvider
- [4] CommandLineConfigurationProvider
- [5] AzureKeyVaultConfigurationProvider
- [6] AzureAppConfigurationProvider

0 - 4 - Automatically set by the CreateDefaultBuilder
5-6 - Manually set from Program.cs

Conclusion, from the conducted tests it seems that to be fully able to control the order of precedence we would need to create our own CreateBuilder method as the last added config provider overrules other providers. 

Is this correct? and if so, are there other options instead of creating a custom CreateBuilder?

**Comment by Tratcher** [comment]
Yes, precedence is by order.

Rather than creating your own builder, you could just add duplicate providers in the order you prefer. E.g. 
[1] JsonConfigurationProvider
[2] JsonConfigurationProvider
[3] EnvironmentVariablesConfigurationProvider
[4] CommandLineConfigurationProvider
[5] AzureKeyVaultConfigurationProvider
[6] AzureAppConfigurationProvider
[7] JsonConfigurationProvider
[8] EnvironmentVariablesConfigurationProvider
[9] CommandLineConfigurationProvider

**Comment by TheReaLee** [comment]
Thanks @Tratcher

**Comment by TheReaLee** [comment]
@Tratcher what does the ChainedConfigurationProvider do exactly?

I'm asking this as

**Comment by Tratcher** [comment]
It lets you add a previously built IConfiguration. That's how we include the host config when creating the app config.

**Comment by TheReaLee** [comment]
Perfect, Thanks @Tratcher
