### ISSUE TITLE
Environment Variables Config Source not respecting prefix

### ISSUE THREAD

**Issue by epignosisx** [aspnet/Extensions#1724]
### Describe the bug
I created a new webapi app from the webapi template: `dotnet new webapi` and did the following changes to the `ValuesController`:

```cs
    [ApiController]
    public class ValuesController : ControllerBase
    {
        private readonly IConfiguration _config;

        public ValuesController(IConfiguration config)
        {
            _config = config;
        }
        // GET api/values
        [HttpGet]
        public IEnumerable<KeyValuePair<string, string>> Get()
        {
            return _config.AsEnumerable();
        }
    }
```

And I'm getting back all the environment variables:

<details>
<pre>
[
   {
      "key":"_",
      "value":"/usr/bin/dotnet"
   },
   {
      "key":"XMODIFIERS",
      "value":"@im=ibus"
   },
   {
      "key":"XDG_VTNR",
      "value":"2"
   },
   {
      "key":"XDG_SESSION_TYPE",
      "value":"x11"
   },
   {
      "key":"XDG_SESSION_ID",
      "value":"2"
   },
   {
      "key":"XDG_SESSION_DESKTOP",
      "value":"pop"
   },
   {
      "key":"XDG_SEAT",
      "value":"seat0"
   },
   {
      "key":"XDG_RUNTIME_DIR",
      "value":"/run/user/1000"
   },
   {
      "key":"XDG_MENU_PREFIX",
      "value":"gnome-"
   },
   {
      "key":"XDG_DATA_DIRS",
      "value":"/usr/share/pop:/usr/local/share/:/usr/share/"
   },
   {
      "key":"XDG_CURRENT_DESKTOP",
      "value":"pop:GNOME"
   },
   {
      "key":"XDG_CONFIG_DIRS",
      "value":"/etc/xdg/xdg-pop:/etc/xdg"
   },
   {
      "key":"XAUTHORITY",
      "value":"/run/user/1000/gdm/Xauthority"
   },
   {
      "key":"WINDOWPATH",
      "value":"2"
   },
   {
      "key":"VTE_VERSION",
      "value":"5401"
   },
   {
      "key":"USERNAME",
      "value":"epignosisx"
   },
   {
      "key":"USER",
      "value":"epignosisx"
   },
   {
      "key":"URLS",
      "value":"https://localhost:5001;http://localhost:5000"
   },
   {
      "key":"TERM",
      "value":"xterm-256color"
   },
   {
      "key":"SSH_AUTH_SOCK",
      "value":"/tmp/ssh-fq11s8NyYH2N/agent.2819"
   },
   {
      "key":"SSH_AGENT_PID",
      "value":"2946"
   },
   {
      "key":"SHLVL",
      "value":"1"
   },
   {
      "key":"SHELL",
      "value":"/bin/bash"
   },
   {
      "key":"SESSION_MANAGER",
      "value":"local/pop-os:@/tmp/.ICE-unix/2819,unix/pop-os:/tmp/.ICE-unix/2819"
   },
   {
      "key":"QT_IM_MODULE",
      "value":"xim"
   },
   {
      "key":"QT_ACCESSIBILITY",
      "value":"1"
   },
   {
      "key":"QT4_IM_MODULE",
      "value":"xim"
   },
   {
      "key":"PWD",
      "value":"/home/epignosisx/Documents/ConfigApp"
   },
   {
      "key":"PATH",
      "value":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/epignosisx/.dotnet/tools"
   },
   {
      "key":"PAPERSIZE",
      "value":"letter"
   },
   {
      "key":"OLDPWD",
      "value":"/home/epignosisx/Documents"
   },
   {
      "key":"LS_COLORS",
      "value":"rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:"
   },
   {
      "key":"LOGNAME",
      "value":"epignosisx"
   },
   {
      "key":"Logging",
      "value":null
   },
   {
      "key":"Logging:LogLevel",
      "value":null
   },
   {
      "key":"Logging:LogLevel:System",
      "value":"Information"
   },
   {
      "key":"Logging:LogLevel:Microsoft",
      "value":"Information"
   },
   {
      "key":"Logging:LogLevel:Default",
      "value":"Debug"
   },
   {
      "key":"LESSOPEN",
      "value":"| /usr/bin/lesspipe %s"
   },
   {
      "key":"LESSCLOSE",
      "value":"/usr/bin/lesspipe %s %s"
   },
   {
      "key":"LC_TIME",
      "value":"en_US.UTF-8"
   },
   {
      "key":"LC_TELEPHONE",
      "value":"en_US.UTF-8"
   },
   {
      "key":"LC_PAPER",
      "value":"en_US.UTF-8"
   },
   {
      "key":"LC_NUMERIC",
      "value":"en_US.UTF-8"
   },
   {
      "key":"LC_NAME",
      "value":"en_US.UTF-8"
   },
   {
      "key":"LC_MONETARY",
      "value":"en_US.UTF-8"
   },
   {
      "key":"LC_MEASUREMENT",
      "value":"en_US.UTF-8"
   },
   {
      "key":"LC_IDENTIFICATION",
      "value":"en_US.UTF-8"
   },
   {
      "key":"LC_ADDRESS",
      "value":"en_US.UTF-8"
   },
   {
      "key":"LANGUAGE",
      "value":"en_US:en"
   },
   {
      "key":"LANG",
      "value":"en_US.UTF-8"
   },
   {
      "key":"IM_CONFIG_PHASE",
      "value":"2"
   },
   {
      "key":"HOME",
      "value":"/home/epignosisx"
   },
   {
      "key":"GTK_MODULES",
      "value":"gail:atk-bridge"
   },
   {
      "key":"GTK_IM_MODULE",
      "value":"ibus"
   },
   {
      "key":"GPG_AGENT_INFO",
      "value":"/run/user/1000/gnupg/S.gpg-agent:0:1"
   },
   {
      "key":"GNOME_TERMINAL_SERVICE",
      "value":":1.92"
   },
   {
      "key":"GNOME_TERMINAL_SCREEN",
      "value":"/org/gnome/Terminal/screen/f511b7e6_a462_4077_955a_e32c13da39a6"
   },
   {
      "key":"GNOME_SHELL_SESSION_MODE",
      "value":"pop"
   },
   {
      "key":"GNOME_DESKTOP_SESSION_ID",
      "value":"this-is-deprecated"
   },
   {
      "key":"GJS_DEBUG_TOPICS",
      "value":"JS ERROR;JS LOG"
   },
   {
      "key":"GJS_DEBUG_OUTPUT",
      "value":"stderr"
   },
   {
      "key":"GDMSESSION",
      "value":"pop"
   },
   {
      "key":"ENVIRONMENT",
      "value":"Development"
   },
   {
      "key":"DISPLAY",
      "value":":1"
   },
   {
      "key":"DESKTOP_SESSION",
      "value":"pop"
   },
   {
      "key":"DBUS_SESSION_BUS_ADDRESS",
      "value":"unix:path=/run/user/1000/bus"
   },
   {
      "key":"contentRoot",
      "value":"/home/epignosisx/Documents/ConfigApp"
   },
   {
      "key":"COLORTERM",
      "value":"truecolor"
   },
   {
      "key":"CLUTTER_IM_MODULE",
      "value":"xim"
   },
   {
      "key":"ASPNETCORE_URLS",
      "value":"https://localhost:5001;http://localhost:5000"
   },
   {
      "key":"ASPNETCORE_ENVIRONMENT",
      "value":"Development"
   },
   {
      "key":"applicationName",
      "value":"ConfigApp"
   },
   {
      "key":"AllowedHosts",
      "value":"*"
   }
]
</pre>
</details>

### To Reproduce
Here is the entire app:

```cs
//Program.cs
namespace ConfigApp
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>();
    }
}

    //Startup.cs
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseDeveloperExceptionPage();
            app.UseMvc();
        }
    }

    //Controller
    [Route("api/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {
        private readonly IConfiguration _config;

        public ValuesController(IConfiguration config)
        {
            _config = config;
        }
        // GET api/values
        [HttpGet]
        public IEnumerable<KeyValuePair<string, string>> Get()
        {
            return _config.AsEnumerable();
        }
    }
```

### Expected behavior
I was expecting to get a filtered list of environment variables that start with ASPNETCORE_ [as described in the documentation.](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.2#environment-variables-configuration-provider).

I can see from the source code that in fact the prefix is specified:
https://github.com/aspnet/AspNetCore/blob/5cb615fcbe8559e49042e93394008077e30454c0/src/Hosting/Hosting/src/WebHostBuilder.cs#L45-L47

So makes me wonder if I'm holding it wrong...

### Additional context
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.203
 Commit:    e5bab63eca

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.10
 OS Platform: Linux
 RID:         ubuntu.18.10-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.203/

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524

.NET Core SDKs installed:
  2.2.203 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by Tratcher** [comment]
Note you're getting back prefixed and non-prefixed variables:
ASPNETCORE_ENVIRONMENT and ENVIRONMENT.

This is expected.
https://github.com/aspnet/AspNetCore/blob/5814a036d93246dec28ac19e4c8b1db4dda7ba32/src/Hosting/Hosting/src/WebHostBuilder.cs#L46
https://github.com/aspnet/AspNetCore/blob/5814a036d93246dec28ac19e4c8b1db4dda7ba32/src/DefaultBuilder/src/WebHost.cs#L181

**Comment by epignosisx** [comment]
Thanks for the reply @tratcher.

What would I need to change in the app to only get back the environment variables with a prefix? Do I have to give up CreateDefaultBuilder?

**Comment by Tratcher** [comment]
In ConfigureAppConfiguration you can remove some or all of the entries from IConfigurationBuilder.Sources.
