### ISSUE TITLE
ASP.NET 2.2 - Only first registered IHostedService will be started.

### ISSUE THREAD

**Issue by dendle** [aspnet/Extensions#1774]
### Describe the bug
ASP.NET Core 2.2 - Hosted Services - First Registration of any IHostedService wins (any subsequent registration will not be added, and StartAync is never called.

### To Reproduce
1. Create a new ASP.NET Core 2.2 Web Application 
2. Create two classes that implement Microsoft.Extensions.Hosting.IHostedService (Assembly Microsoft.Extensions.Hosting.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
3. Register both services as Hosted Services using the extension method provided
```
public void ConfigureServices(IServiceCollection services)
{
services.AddHostedService<HostedServiceA>();
services.AddHostedService<HostedServiceB>();
///..redacted for brievity
}
 ```
4. HostedServiceA will have its StartAysnc method called.  HostedServiceB will not.

### Expected behavior
All hosted services should be registered and started.

### Additional context
I was referencing the wrong branch below, so not sure where the source of the problem is.  Will keep looking.
~~TryAdd is used here, which is failing for subsequent adds - I suggest this should be keyed by implementation type.
https://github.com/aspnet/Extensions/blob/9b500afd34f000b1c40fc393fb51d02aec60ed2c/src/Hosting/Abstractions/src/ServiceCollectionHostedServiceExtensions.cs#L20~~

**Comment by dendle** [comment]
Oops!
Was my fault, both of my services did not return from the StartAsync method, so the loop that starts all services never progressed to the second service I registered!

**Comment by mosakashaka** [comment]
Hi, I'm sorry but I have a similar problem that only one service runs.

If a service is supposed to be blocking, should I create a seperated thread to run it in `StartAsync` and return from `StartAsync`?
