### ISSUE TITLE
UseWindowsService() should take an overload to configure the eventlog

### ISSUE THREAD

**Issue by erikmf12** [aspnet/Extensions#1794]
Since the addition of automatically creating the eventlog log with `UseWindowsService()`, it would be nice to have an overload to control the logname and source of that eventlog. I'm thinking just overloading `UseWindowsService()` to `UseWindowsService(Action<EventLogSettings> configure)` then just handing that Action to the call to AddEventLog().

**Comment by erikmf12** [comment]
I just created [PR #1800](https://github.com/aspnet/Extensions/pull/1800) that includes my proposed changes.

**Comment by anurse** [comment]
As discussed in the PR, we don't want to couple the event logging config to the `UseWindowsService` method. Closing.

**Comment by losdamianos** [comment]
can we please reopen this or provide a solution on how to overrride default event log source ? I want to set up my own destination rather than polluting Application source in the event log
I was able to do this with
                    //configure logging
                    .ConfigureLogging(loggerFactory =>
                        //add event log
                        loggerFactory.AddEventLog(settings)
but now UseWindowsService() is overriding it

**Comment by erikmf12** [comment]
@losdamianos All you have to do is add 

    
    services.Configure<EventLogSettings>(settings =
  	{
	    settings.LogName = "MyService";
        settings.SourceName = "MyService";
    });

in `ConfigureServices` after the call to `UseWindowsService`.

**Comment by anurse** [comment]
> I want to set up my own destination rather than polluting Application source in the event log

The default logic for `UseWindowsService` *does* in fact attempt to log to an Event Source named after the application. However, as @erikmf12 said, you need to either have created the Event Source manually in advance or launch your application at least once as an Administrator so that it can create the source.

**Comment by losdamianos** [comment]
> @losdamianos All you have to do is add
> 
> ```
> services.Configure<EventLogSettings>(settings =
> {
>     settings.LogName = "MyService";
>     settings.SourceName = "MyService";
> });
> ```
> 
> in `ConfigureServices` after the call to `UseWindowsService`.
> 
> Also, don't forget that if it yells at you that it cannot create the Source, just start your app once as Admin and then it will have the correct credentials.

@erikmf12 Thanks for getting back to me. I run VS as admin before running this test snippet, it was working fine on preview 5 but just cant get it to work on preview 6 

```
        public static IHostBuilder CreateHostBuilder(string[] args)
        {
            string _sourceName = "MyProgram"; //source program name
            string _logName = "MyProgram"; //new event log or targeted event log name


            //if custom event log does not exist, create it
            if (!EventLog.SourceExists(_logName))
            {
                //event log creates new app log and associates program, "My Program", with new log, "My Event Log"
                EventLog.CreateEventSource(_sourceName, _logName);
            }
            //event log settings
            EventLogSettings settings = new EventLogSettings
            {
                SourceName = _sourceName,
                LogName = _logName
            };

            return Host.CreateDefaultBuilder(args)
                    //configure logging
                    .ConfigureLogging(loggerFactory =>
                        //add event log
                        loggerFactory.AddEventLog(settings)
                                    //add console
                                    .AddConsole(x => x.DisableColors = true))
                    .ConfigureServices(services =>
                    //add worker service
                    services.AddHostedService<Worker>()
                      //Configure db context
                      .AddDbContext<DBContext>(options => options.UseSqlServer(_configuration.GetConnectionString("MSQLDEVDatabase"))));
        }
```

To keep it simple I just changed it to below, still no luck, error test message logs directly to application with the source = ".NET Runtime"
```
            return Host.CreateDefaultBuilder(args)
                    .UseWindowsService()
                    .ConfigureServices(services =>
                    services.AddHostedService<Worker>()
                    .Configure<EventLogSettings>(z=> new EventLogSettings
                    {
                        SourceName = "MyProgram",
                        LogName = "MyProgram"
                    })
```

**Comment by losdamianos** [comment]
@erikmf12  thanks! I got it working in the end

**Comment by anurse** [comment]
Ah yeah, the `Configure` delegate takes an `Action<TOptions>` so constructing a new instance in your handler won't do anything other than running the constructor of the class. You're expected to just modify the existing value. If you think the IntelliSense docs could be clearer here, a PR to [fix them](https://github.com/aspnet/Extensions/blob/master/src/Options/Options/src/OptionsServiceCollectionExtensions.cs#L56) would be cool!
