### ISSUE TITLE
Two more test cases for DependencyInjectionSpecificationTests to test disposable singletons

### ISSUE THREAD

**Issue by peter-perot** [aspnet/Extensions#1799]
.NET Core dependency injection is a "tracking" container, i.e. it tracks disposable objects and disposes them if the container is disposed or the scope is left.

When a disposable singleton is registered, the container **only tracks the object if it is created by a factory**, in order to dispose it if the container itself is disposed. If the singleton is **added as an existing instance, the container does not track the object**, and it does not dispose it. This behavior is correct since disposable singletons which are added as an existing instance are considered "externally owned".

However, some 3rd party containers which implement the .NET Core abstractions behave differently here, e.g. Autofac.

I propose to file two additional test cases to check the behavior mentioned above:

```csharp
using System;
using System.Collections.Generic;
using Xunit;

namespace Microsoft.Extensions.DependencyInjection.Specification
{
  public abstract class DependencyInjectionSpecificationTests2 : DependencyInjectionSpecificationTests
  {
    [Fact]
    public void SingletonServiceCreatedFromFactoryIsDisposedWhenContainerIsDisposed()
    {
      // Arrange
      var collection = new TestServiceCollection();
      collection.AddSingleton(_ => new TestDisposable());
      var provider = this.CreateServiceProvider(collection);

      // Act
      var service = provider.GetService<TestDisposable>();
      ((IDisposable)provider).Dispose();

      // Assert
      Assert.True(service.IsDisposed);
    }

    [Fact]
    public void SingletonServiceCreatedFromInstanceIsNotDisposedWhenContainerIsDisposed()
    {
      // Arrange
      var collection = new TestServiceCollection();
      collection.AddSingleton(new TestDisposable());
      var provider = this.CreateServiceProvider(collection);

      // Act
      var service = provider.GetService<TestDisposable>();
      ((IDisposable)provider).Dispose();

      // Assert
      Assert.False(service.IsDisposed);
    }

    internal class TestDisposable : IDisposable
    {
      public bool IsDisposed { get; private set; }

      public void Dispose()
      {
        this.IsDisposed = true;
      }
    }

    internal class TestServiceCollection : List<ServiceDescriptor>, IServiceCollection
    {
    }
  }
}
```

**Comment by anurse** [comment]
This seems reasonable to me (thoughts @davidfowl @pakrym ?). I don't have a ton of context on the DI spec tests. Would you like to open a PR?

**Comment by davidfowl** [comment]
This retroactive test might fail on the other containers today (it always happens when we discover new behaviors that people rely on) so I think it makes sense to add it so we can see what happens on 3rd party containers.

**Comment by tomakita** [comment]
@peter-perot, I've just submitted a PR for this.  If you'd rather submit one yourself, that's OK too, and I can have mine deleted.

**Comment by davidfowl** [comment]
Dixed

**Comment by peter-perot** [comment]
@tomakita Thank you for setting up a PR.
