### ISSUE TITLE
Console logs timestamps in local timezone instead of UTC

### ISSUE THREAD

**Issue by danmosemsft** [aspnet/Extensions#1808]
Moved from Corefx. Issue by @tomkerkhove

When configuring the Console logger to output timestamps as following:
```csharp
Host.CreateDefaultBuilder(args)
    .ConfigureAppConfiguration((hostingContext, config) =>
    {
        config.AddEnvironmentVariables();
    })
    .ConfigureLogging((hostBuilderContext, loggingBuilder) =>
    {
        loggingBuilder.AddConsole(consoleLoggerOptions => consoleLoggerOptions.TimestampFormat = "[HH:mm:ss]");
    })
    .ConfigureServices(services =>
    {
        services.AddHostedService<OrdersQueueProcessor>();
    });
```

The generated logged message uses my local timezone rather than UTC without an option to change this.

Would be good to be able to influence this and use UTC by default.

**Comment by anurse** [comment]
It would definitely have to be an option, but I don't see this as a problem.

The simplest thing would certainly be to just add a `WriteTimestampInUtc` option that can be set to `true` to opt-in to this behavior. The main concern I have is just a possible explosion of options. I don't think this would be unreasonable though. There are more powerful logging systems out there (such as Serilog) that give you a LOT of flexibility about the log messages and we're not out to replicate their functionality.

**Comment by tomkerkhove** [comment]
I'm not saying it's a problem but indeed suggesting that we should be able to use UTC.
Having this as a property is fine for me!

Other logging systems provide more robust features indeed but those do not require to be in here, however, I think timestamps are essential.

**Comment by tomkerkhove** [comment]
This one should be done

**Comment by anurse** [comment]
Yep, thanks for the reminder!
