### ISSUE TITLE
BackgroundService TaskStatus

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Extensions#1855]
IMHO the BackgroundService should expose the _executingTask TaskStatus so that a developer may inspect the property and determin if the service task is running and/or has been cancelled, faulted etc. 

It would also be good if the _execuringTask should also be wrapped in a try { } catch { } to capture background service expections as a additonal property with the option to rethrow the expectation or call an optional function when and expection occurs

**Comment by khellang** [comment]
I'm not sure what scenario this would enable. Do you have an example?

When you implement `ExecuteAsync` you return a `Task` that you literally control the status of. There should be no reason to expose a field for you to inspect.

**Comment by davidfowl** [comment]
Closing as dupe of https://github.com/aspnet/Extensions/issues/1857
