### ISSUE TITLE
Remove implicit EventLog filter from UseWindowsServices and move it to the template

### ISSUE THREAD

**Issue by anurse** [aspnet/Extensions#1858]
The implicit `AddFilter` call we run for your in `UseWindowsServices` is problematic because it is hidden to users and causes confusion and overrides the use of the default logging options in `appsettings.json` (https://github.com/aspnet/Extensions/issues/1839). Users *can* override this logic, but they have to add an explicit `EventLog` section to their logging config.

https://github.com/aspnet/Extensions/blob/f12d709976e382672ce100bc00381a8847f06489/src/Hosting/Hosting/src/Host.cs#L102

Instead, let's remove this and add the filtering to the Worker Service template `appsettings.json` file:

```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    },
    "EventLog": {
      "LogLevel": {
        "Default": "Warning"
      }
    }
  }
}
```

**Comment by Tratcher** [comment]
Clarification: that's not in UseWindowsServices.

**Comment by anurse** [comment]
Right, but I believe that line is only in `Host` to get the filter in place before logging config is read. `UseWindowsServices` is the only one that registers *the provider itself*, so only that template would need to be adjusted here. We should double check that of course.

**Comment by anurse** [comment]
Feh, looks like it is also registered here: https://github.com/aspnet/Extensions/blob/ef5d488c054c3aa850c29c10d851fcdc8a004eed/src/Hosting/Hosting/src/Host.cs#L113

**Comment by anurse** [comment]
Given that, we probably don't also need it in `UseWindowsServices`... This is also a little more complicated :(

**Comment by Tratcher** [comment]
Also, UseWindowsServices is not in the worker template, it requires an additional dependency.

**Comment by davidfowl** [comment]
@anurse Is there any equivalent issue in ASP.NET Core?

**Comment by anurse** [comment]
Not at the moment. Have we figured out how we're going to do it? @Tratcher 's comment indicates this is going to be more difficult than just updating the template.

**Comment by anurse** [comment]
In re-thinking this, I actually think we could just leave this as-is. The issue is that **previously** when you enabled `UseWindowsServices`, you got `Information` logs in the Event Log. I'd contend that's too noisy and it's by-design that we only want to send Warnings/Errors to EventLog. You can always override it directly (https://github.com/aspnet/Extensions/issues/1839#issuecomment-501771268).

I'd think that a Windows Service should be logging things `Info` and below to things like log files rather than the EventLog, but that's just my impression.

**Comment by anurse** [comment]
Closing as per my above comment (and hearing no disagreement 😄)
