### ISSUE TITLE
Improve LogValues performance by making them visitable

### ISSUE THREAD

**Issue by Scooletz** [aspnet/Extensions#1868]
### Is your feature request related to a problem? Please describe.

Currently, for high performance logging the encouraged API is to use `LoggerMessage` that underneath creates LogValues structs to pass the value to the logger implemenetation (https://github.com/aspnet/Extensions/blob/master/src/Logging/Logging.Abstractions/src/LoggerMessage.cs#L305-L351). It'd be great if LogValues would be _visitable_ (Visitor pattern) that would potentially enable to do not call the `formatter` by the logger implementation.

### Describe the solution you'd like
Add two public interfaces to visit log values, something like

```csharp
public interface ILogValues
{
   string OriginalFormat { get; }
   void VisitValues<TVisitor> (ref TVisitor v) where TVisitor : ILogValueVisitor;
}

public interface ILogValueVisitor
{
   void OnValue<T>(string fieldName, T value);
}

// or even simpler as names can be derived from the format


public interface ILogValueVisitor
{
   void OnValue<T>(T value);
}

```

### Describe alternatives you've considered

One of the alternatives that I considered, would be making log values serializable, but then, being serializable can be different for different serializers, and also, could box values.

### Additional context

A somewhat similar issue to this is https://github.com/aspnet/Extensions/issues/646

**Comment by Scooletz** [comment]
Just a note: I can implement it. I just need to know what maintainers of this repo think about it.

**Comment by gfoidl** [comment]
> it's worth to provide this option for loggers aimed at writing logs fast

Can you provide a sample which shows the usage, please?

**Comment by Scooletz** [comment]
Sure @gfoidl My aim was to enable loggers, that are provide generic methods for logging, like `Serilog`

https://github.com/serilog/serilog/blob/dev/src/Serilog/ILogger.cs#L99-L121

But now I see, that this proposal would fail, as it'd be not able to capture the generic type for the previously visited value. I'll close this issue and work on the PR mentioned in here.
