### ISSUE TITLE
Microsoft.Extensions.HealthCheck nuget package missing

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Extensions#1875]
I'm looking at creating a library of healthcheck extensions; however the Microsoft.Extensions.HealthChecks nuget package is missing when in visual studio; and marked as removed when trying to access this via the nuget website.  I've noticed that the project GitHub link list on the nuget site is not pointing to this project? Is the healthcheck library available under someother link or nuget name?

**Comment by PinpointTownes** [comment]
Did you mean [`Microsoft.Extensions.Diagnostics.HealthChecks`](https://www.nuget.org/packages/Microsoft.Extensions.Diagnostics.HealthChecks/)? 😄

**Comment by grahamehorner** [comment]
Thanks, looking at nuget there seems to be a few package that have Microsoft.Extension.HealthChecks and namespace that are from Microsoft which is a little confusing when looking for the correct package.  Thanks again

**Comment by rynowak** [comment]
Closing since this has been answered. Thanks @PinpointTownes
