### ISSUE TITLE
Support for a YAML configuration provider

### ISSUE THREAD

**Issue by tomkerkhove** [aspnet/Extensions#1904]
In container land, YAML is used in favor of JSON which is not supported in .NET Core OOTB. Would be good to have a YAML configuration provider.

This is already available via https://github.com/andrewlock/NetEscapades.Configuration but would be good to have official support for this OOTB.

**Comment by hishamco** [comment]
If I'm not wrong this issue is already logged from 1.0, but it closed, coz there's no plan to support it

**Comment by tomkerkhove** [comment]
Thanks for the update @hishamco 	but 1.0 is a long time ago, time to see if we can revise that decision!

**Comment by ichensky** [comment]
Duplicate of https://github.com/aspnet/AspNetCore/issues/60 , https://github.com/dotnet/corefx/issues/34578

**Comment by davidfowl** [comment]
> This is already available via https://github.com/andrewlock/NetEscapades.Configuration but would be good to have official support for this OOTB.

Why should it be in the box?

**Comment by tomkerkhove** [comment]
Because YAML is used more and more + .NET is always mentioned to be a good candidate for microservices.

However, microservices are often shipped via containers wherein the container space YAML is used for configuration over JSON.

**Comment by davidfowl** [comment]
We're not going to change the default from JSON to Yaml, I'd suggest using the above library if you want yaml based configuration files.

**Comment by tomkerkhove** [comment]
I'm not saying that it should be the new default, I'm just wondering why YAML is not supported OOTB.

Anyhow, I could only ask.

**Comment by davidfowl** [comment]
Several reasons:
 - It requires a dependency on a Yaml parser.
 - It wasn't deemed important to ship OOTB by the team.
 - There are various 3rd party implementations that do a good job.

**Comment by tomkerkhove** [comment]
A pity but fair enough
