### ISSUE TITLE
Extract tools from the ASP.NET stack

### ISSUE THREAD

**Issue by weitzhandler** [aspnet/Extensions#1942]
Hi,

It would be nice to extract some essential tools from this repo and make it officially available for other .NET tools, or clarify its performance hit and whether it's suitable to be used in apps other than ASP.NET Core.
For instance, the `HttpClientFactory`, could be very useful in mobile client apps, but the [package](https://www.nuget.org/packages/Microsoft.Extensions.Http/) has some ASP.NET Core biased dependencies, and it's not clear if it would be a good idea to have them in your mobile app.

My request is that you extract all those classes and make them .NET Core rather than ASP.NET Core.

Thank you!

**Comment by rynowak** [comment]
Hi @weitzhandler - these are all netstandard 2.0 libraries and don't depend on any ASP.NET Core types. We intend for them to be used in *any* .NET project. 

Here's an example: https://montemagno.com/add-asp-net-cores-dependency-injection-into-xamarin-apps-with-hostbuilder/

/cc @glennc @jamesmontemagno @terrajobst

Is there something in particular that's bothering you? Is it the aspnet github org?

**Comment by weitzhandler** [comment]
That's a great article!

> Is it the aspnet github org?

Yes kinda. It 'feels' that this functionality is server-only and would be too much of a hit on mobile apps, but that article resolves that fear. It would be nice to have this bit of info on the package description / docs.

Thank you.
