### ISSUE TITLE
Feature request: Make it possible to add a X509Certificate2 to a HttpClient instance using the IHttpClientFactory 

### ISSUE THREAD

**Issue by damienbod** [aspnet/Extensions#1949]
When using the IHttpClientFactory , it is not possible to add a X509Certificate2 to the returned HttpClient. At present, I can only do this by using the ConfigurePrimaryHttpMessageHandler or creating a new HttpRequestMessage and adding the certificate as a header.

**Comment by myFirstway** [comment]
> @rynowak just realized this makes no sense, using a named HttpClient with ConfigurePrimaryHttpMessageHandler can do exactly this. (unless we need dynamic clients, ie each client certificate is read from a database)
Now how do you solve this problem

**Comment by myFirstway** [comment]
> @rynowak just realized this makes no sense, using a named HttpClient with ConfigurePrimaryHttpMessageHandler can do exactly this. (unless we need dynamic clients, ie each client certificate is read from a database)

Now how do you solve this problem？
