### ISSUE TITLE
Using MemoryStream on JsonConfigurationExtensions.AddJsonStream throws StreamNotReadable due to casting

### ISSUE THREAD

**Issue by sport-monkey** [aspnet/Extensions#1979]
### Describe the bug
When attempting to use a MemoryStream of a JSON file for config a `System.ArgumentException: Stream was not readable` is received. This is because the AddJsonStream extension [https://github.com/aspnet/Extensions/blob/release/3.0-preview7/src/Configuration/Config.Json/src/JsonConfigurationExtensions.cs.AddJsonStream](https://github.com/aspnet/Extensions/blob/0db848f9c0091be8980db79c0b88c519910c4c3b/src/Configuration/Config.Json/src/JsonConfigurationExtensions.cs#L101) uses the following [https://github.com/aspnet/Extensions/blob/release/3.0-preview7/src/Configuration/Config.Json/src/JsonConfigurationSource.cs](https://github.com/aspnet/Extensions/blob/release/3.0-preview7/src/Configuration/Config.Json/src/JsonConfigurationSource.cs) that implements FileConfigurationProvider.

### To Reproduce
1. Using version 'dotnet/packs/Microsoft.AspNetCore.App.Ref/3.0.0-preview6.19307.2/ref/netcoreapp3.0/Microsoft.Extensions.Configuration.Json.dll'
2. Run this code
```
            var builder = new WebHostBuilder()
                .UseContentRoot("../../../../WorkingCode")
                .UseEnvironment("Development")
                .UseUrls("http://localhost:0")
                .ConfigureAppConfiguration((_, config) =>
                { config.AddJsonStream(new MemoryStream(Encoding.UTF8.GetBytes("{ \"SomeKey\": \"SomeValue\" }"))); Configuration = config.Build(); }).UseStartup<Startup>();
```
3. ~With these arguments '....'~
4. See error "System.ArgumentException: Stream was not readable"

### Expected behavior
Either I would expect:
i. the configuration to be read for 
or
ii. AddJsonStream to only take a FileStream

### ~Screenshots~
~If applicable, add screenshots to help explain your problem.~

### ~Additional context~
~Add any other context about the problem here.
Include the output of `dotnet --info`~

**Comment by HaoK** [comment]
I'm unable to reproduce this using a clean app, created a new dotnet core web app and added the same code as above, and it was able to run fine and I was able to interact with the Config and lookup the SomeValue
```
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder
                    .ConfigureAppConfiguration((_, config) =>
                    {
                        config.AddJsonStream(new MemoryStream(Encoding.UTF8.GetBytes("{ \"SomeKey\": \"SomeValue\" }")));
                    })
                    .UseStartup<Startup>();
                });

```

**Comment by sport-monkey** [comment]
Here's a full example, it's caused by building the configuration for reuse inside tests
```
namespace JsonConfigurationFailure
{
    public class Examples
    {
        [Fact]
        public void Failure()
        {
            const string configString = "{\"PointlessValue\": \"hello\"}";

            IConfigurationRoot configuration = null;
            var webFolder = Path.GetFullPath("../../../../JsonConfigurationExtensionsTest");
            
            var builder = new WebHostBuilder()
                .UseContentRoot(webFolder)
                .UseEnvironment("Development")
                .UseUrls("http://localhost:0")
                .ConfigureAppConfiguration((_, config) =>
                {
                    config.AddJsonStream(new MemoryStream(Encoding.UTF8.GetBytes(configString)));
                    configuration = config.Build();
                }).UseStartup<Startup>();

            Assert.Throws<ArgumentException>(() => new TestServer(builder));
        }
        
        [Fact]
        public async Task Success()
        {
            const string configString = "{\"PointlessValue\": \"hello\"}";

            var webFolder = Path.GetFullPath("../../../../JsonConfigurationExtensionsTest");
            
            var builder = new WebHostBuilder()
                .UseContentRoot(webFolder)
                .UseEnvironment("Development")
                .UseUrls("http://localhost:0")
                .ConfigureAppConfiguration((_, config) =>
                {
                    config.AddJsonStream(new MemoryStream(Encoding.UTF8.GetBytes(configString)));
                }).UseStartup<Startup>();

            var testServer = new TestServer(builder);
            
            var client = testServer.CreateClient();
            var response = await client.GetAsync("/api/values/1");
            var content = await response.Content.ReadAsStringAsync();
            
            Assert.Equal("hello", content);
        }
    }
}
```
