### ISSUE TITLE
Enable HttpClient configuration inheritance with HttpClientFactory registration

### ISSUE THREAD

**Issue by weitzhandler** [aspnet/Extensions#1988]
## Problem

The `IHttpClientFactory` interface only exposes a single overload of getting a named client.
Per the [code](https://github.com/aspnet/Extensions/blob/master/src/HttpClientFactory/Http/src/DependencyInjection/HttpClientFactoryServiceCollectionExtensions.cs#L205-L207), any typed client is also registered by its name.
In certain scenarios, it's important to acquire a typed-client on demand, not via constructor injection (e.g. in a singleton class).

For example:

```c#
public class MyClient
{
  readonly HttpClient _HttpClient;
  public MyClient(HttpClient httpClient)
  {
    httpClient.BaseAddress = "https://mywebsite.com";
    _HttpClient = httpClient;    
  }

  public Task<string> GetMyValueAsync() => _HttpClient.GetStringAsync("route/action");  
}

public class MySingletonService : IMySingletonService
{
  readonly IHttpClientFactory _HttpClientFactory;
  public MySingletonService(IHttpClientFactory httpClientFactory)
  {
    _HttpClientFactory = httpClientFactory;
  }  
  
  public async Task DoStuffAsync()
  {
    var client = _HttpClientFactory.CreateClient<MyClient>();
    var myWebValue = await client.GetMyValueAsync();
    ...
  }
}
```

## Solution

Add a `CreateClient<TClient>` extension method on either `IHttpClientFactory` (preferred) or `IServiceProvider`, that returns a `TClient` with an injected `HttpClient`.

## Update
Read from [this](https://github.com/aspnet/Extensions/issues/1988#issuecomment-509836890) comment and on, prior to that is irrelevant.

**Comment by rynowak** [comment]
You can already get your typed client from `IServiceProvider`. Use `GetService()` or `GetRequiredService<>()`.

**Comment by weitzhandler** [comment]
Thanks.

Can we have a subclass of `HttpClient` instead of configuring clients?

**Comment by rynowak** [comment]
You can do that if you want, but there's no feature of the factory that will understand it.

**Comment by weitzhandler** [comment]
Shame. `TClient` as `class` can be redundant when u just need a `HttpClient` with one or two settings modified. And named clients are ugly lol...

Thanks for the info!

**Comment by weitzhandler** [comment]
I wish there was `THttpClient CreateClient<THttpClient>(this IHttpClientFactory factory) where THttpClient : HttpClient`.
I reckon the injected `IHttpClientFactory` only takes care of the type `HttpClient`, not subclasses of it, is that true?

**Comment by weitzhandler** [comment]
I wish there was `THttpClient CreateClient<THttpClient>(this IHttpClientFactory factory) where THttpClient : HttpClient`.
I reckon the injected `IHttpClientFactory` only takes care of the type `HttpClient`, not subclasses of it, is that true?

Would you ever considering support for subclasses of `HttpClient` as well?

**Comment by rynowak** [comment]
Sure, it seems like we could add something like that, I'm curious about the scenario what is your reason for subclassing HttpClient?

**Comment by weitzhandler** [comment]
The most simple example would be setting the base address in a client app, to interact with the server.

```
public class GlobalClient : HttpClient
{
  public GlobalClient(HttpHandler handler, bool dispose) : base(hander, dispose)
  {
    BaseAddress = "https://backend.myserver.com/";
  }
}
```

Than you can choose to add other clients inheriting from the global one.
Sometimes, it's easier inheriting than wrapping, because when you wrap everything gets more verbose, so unless you solely need to expose specific get etc. methods, it's easier inheriting and still benefiting from all `HttpClient` properties and ex. methods directly.

My suggestion is there should be another set of `AddHttpClient<TClient> where TClient : HttpClient` ex. methods, and then another method/ex. method on `IHttpClientFactory` of CreateClient<TClient> where TClient : HttpClient`.

**Comment by rynowak** [comment]
You can easily use the factory to configure things like base address already. I'm not totally sold on this based on this scenario.....

```C#
services.AddHttpClient("foo" c => c.BaseAddress = ...);
```

The reason I'm pushing back is that we add a feature we need to provide clear guidance about when and why you'd use it. I don't see that here because it overlaps with a feature we already have.

**Comment by weitzhandler** [comment]
I just like subclassing rather than named clients. I prefer using the type as the client identifier rather than strings.
Additionally, with named clients, there is no "based on" or inheritance. Allowing `TClient : HttpClient`, would open a door to add a `GlobalClient`, then allowing taking this `GlobalClient` and diverging it into various subtypes each adding its own functionality.

**Comment by weitzhandler** [comment]
My ugly solution meanwhile:

```c#
public static class GlobalHttpClientExtensions
{
  public static IHttpClientBuilder AddGlobalHttpClient(this IServiceCollection services) =>
    services.AddHttpClient<GlobalHttpClient>();

  public static HttpClient CreateGlobalClient(this IServiceProvider serviceProvider) =>
    serviceProvider.GetService<GlobalHttpClient>().HttpClient;

  class GlobalHttpClient
  {
    public GlobalHttpClient(IUriProvider uriProvider, HttpClient client)
    {                         
      client.BaseAddress = uriProvider.TenantUrl;
      HttpClient = client;
    }

    public HttpClient HttpClient { get; }
  }
}
```

**Comment by rynowak** [comment]
You can do this in a much simpler way with [this method](https://github.com/aspnet/Extensions/blob/17b28e83aa85612289e00fa250ec4647cf26bba5/src/HttpClientFactory/Http/src/DependencyInjection/HttpClientFactoryServiceCollectionExtensions.cs#L149)

```C#
services.AddHttpClient("foo", (services, client) =>
{
    var uriProvider = services.GetRequiredService<IUriProvider>();
    client.BaseAddress = uriProvider.TenantUrl;
})

public static class TenantHttpClientExtensions
{
    public static HttpClient CreateTenantHttpClient(this IServiceProvider serviceProvider) =>
    serviceProvider.GetService<IHttpClientFactory>().CreateClient("foo");
}
```

> should I close this issue and open a new one?

This issue is suitably descriptive, but I have no plans to add a feature like this without seeing more scenarios. It's really not clear to me why inheritance is important for your use case. 

I'm willing to hear you out, but I want to repeat my perspective. We already have features, guidance, and documentation around an existing pattern (typed clients that wrap `HttpClient`). I'm not keen on offering an alternative because that makes the overall story less clear. 

What would change my mind is seeing examples, from real apps, of things that **have to** use inheritance, instead of it simply being a preference.

**Comment by weitzhandler** [comment]
@rynowak 

> You can do this in a much simpler way with [this method](https://github.com/aspnet/Extensions/blob/17b28e83aa85612289e00fa250ec4647cf26bba5/src/HttpClientFactory/Http/src/DependencyInjection/HttpClientFactoryServiceCollectionExtensions.cs#L149)

Nice.
Still, client keyed by their names are ugly, compared to those keyed by their type.
How about publicizing the [`TypeNameHelper`](https://github.com/aspnet/Extensions/blob/master/src/Shared/src/TypeNameHelper/TypeNameHelper.cs) instead, to allow devs use types instead of strings?

> I'm willing to hear you out, but I want to repeat my perspective. We already have features, guidance, and documentation around an existing pattern (typed clients that wrap HttpClient). I'm not keen on offering an alternative because that makes the overall story less clear.

I always used to use subclasses of `HttpClient` in my apps, I guess I'll take some more time to get used to wrapper classes

**Comment by weitzhandler** [comment]
@rynowak 

After working with it for a while, I find it pretty frustrating that we can't chain settings and base them one on the other.

I have the `BaseAddress` and some other certificates I'd like to base all my clients on.

**Comment by weitzhandler** [comment]
For instance I need a `HttpClient` (not a wrapper), that encapsulates token-header attachment.
Why do I have to pollute all dependent classes with a stringed client key or dedicate a property to crawl into `MyService.MyHttpClient`. I find it totally frustrating.
And I use Refit, which makes it even harder to globalize, categorize and reuse my clients based on type rather than string.

**Comment by weitzhandler** [comment]
Another solution that could work just well, is introducing a `IHttpClientConfiguration`, something like this pseudo:

```c#
public interface IHttpClientConfiguration
{
    public void Configure(HttpClient client);
}
```

Then:

```c#
services.AddHttpClient<MyHttpClientConfiguration>();

factory.CreateHttpClient<MyHttpClientConfiguration>();
```

This would allow chaining/combining typed http-clients easily:

```c#
class MyOtherHttpClientConfiguration : MyHttpClientConfiguration
{
  public override Configure(HttpClient client)
  {
    base.Configure(client);
    // more config
  }
}
```

But a combination of both would be best:

```c#
services.AddHttpClient<MyHttpClientType>()
    .WithConfig<MyConfig1>()
    .WithConfig<MyConfig2>();

//usage - gets a HttpClient tunnelled into MyConfig1 and MyConfig2
HttpClient myConfiguredClient = factory.CreateHttpClient<MyHttpClientType>();
```

**Comment by weitzhandler** [comment]
Closing this issue for the sake of #2038.
