### ISSUE TITLE
[Feature request] Add a way to combine and reuse HttpClientFactory configurations

### ISSUE THREAD

**Issue by weitzhandler** [aspnet/Extensions#2038]
## Problem

The HTTP client factory methods offer either registering a configured `HttpClient` by a string key, or creating a "typed client", which is a wrapper class that accepts a `HttpClient` by its constructor.

The issues with it are:
- In order to resolve a configured `HttpClient`, you'll need to use a stringed key
- If you need a configured typed `HttpClient`, you have to create a wrapper then exposing the `HttpClient` via a property and getting it from the wrapper
- No way to save typed configurations and apply them to clients by type, only by string, or via the wrapper client

## Example
For instance, you have a category of `HttpClient`s that you want their `BaseAddress` to be set by an external DI service that resolves the address based on current tenant/user.
Additionally, some other or the same `HttpClient`s, require authentication and attachment of tokens or other headers.
Some need a combination. 
There should be a way to register `HttpClient` configurations and reuse or combine them, plus a way to resolve configured `HttpClient` instances with another means (not a string).

## Solution

Introduce a way to configure a `HttpClient` using a `Type` as key, and in addition, allow registering configurations.

One not well thought example is:

```c#
public interface IHttpClientConfiguration
{
    public void Configure(HttpClient client, IServiceProvider serviceProvider);
}
```

Registration
```c#
// registration
services.AddHttpClient<MyType>()
  .AddConfiguration<MyHttpClientConfiguration1> //MyHttpC.. implements IHttpClientConfig
  .AddConfiguration<MyHttpClientConfiguration2>();

// resolution
HttpClient myConfiguredClient = httpClientFactory.CreateClient<MyType>();
```

**Comment by rynowak** [comment]
How is something like this:

```C#
// registration
services.AddHttpClient<MyType>()
  .AddConfiguration<MyHttpClientConfiguration1> //MyHttpC.. implements IHttpClientConfig
  .AddConfiguration<MyHttpClientConfiguration2>();
```

Much different than this:

```C#
// registration
services.AddHttpClient<MyType>((client, services) =>
{
    services.GetRequiredService<MyHttpClientConfiguration1>().Configure(client);
    services.GetRequiredService<MyHttpClientConfiguration1>().Configure(client);
})
```

It seems like you can already accomplish what you want with an extension method.

**Comment by weitzhandler** [comment]
This is enough.
So it's only the that we can't resolve the `HttpClient` directly, but the wrapper.
Using string keys or ex. methods is a bad idea.

There should be a way to inject a `HttpClient` that has already been configured.

**Comment by weitzhandler** [comment]
I added this extension method, but would be really nice to have it built-in, and in addition, there should be away to explicitly access the `HttpClient. Ideally, another extension method over `IHttpClientFactory` that accepts a type/generic-type, and resolves the string name for it.

```c#
public static class HttpClientFactoryExtensions 
{
  public static HttpClient CreateClient<TClient>(this IHttpClientFactory factory) =>
      factory.CreateClient(typeof(TClient).Name); //should use TypeNameHelper instead
}
```

**Comment by weitzhandler** [comment]
I can live with that.

I use this:

```c#
public interface IHttpClientConfigurator
{
  void Configure(IServiceProvider serviceProvider, HttpClient client);
}

/*****/

public static IHttpClientBuilder ConfigureHttpClient<TConfigurator>(
    this IHttpClientBuilder builder)
  where TConfigurator : IHttpClientConfigurator
{
  return builder.ConfigureHttpClient((serviceProvider, httpClient) =>
  {
    var configurator = serviceProvider.GetRequiredService<TConfigurator>();
    configurator.Configure(serviceProvider, httpClient);
  });
}
```

Usage:
```c#
public class TenantBaseAddressConfigurator : IHttpClientConfigurator
{
  public void Configure(IServiceProvider serviceProvider, HttpClient httpClient)
  {
    var uriProvider = serviceProvider.GetRequiredService<IUriProvider>();
    httpClient.BaseAddress = uriProvider.TenantUrl;
  }
}

// registration
services.AddHttpClient<MyType>()
  .ConfigureHttpClient<TenantBaseAddressConfigurator>()
  .ConfigureHttpClient<MyHttpClientConfiguration2>();
```

I would appreciate though if another few ex. methods for that were provided out the box.

Anyway, so it's only the that we can't resolve the `HttpClient` directly, only through a wrapper, this is kinda annoying.
Using string keys or ex. methods is a bad idea.
There should be a way to inject a `HttpClient` that has already been configured.

I added this extension method, but would be really nice to have it built-in, and in addition, there should be a way to explicitly access the `HttpClient`. Ideally, another extension method over `IHttpClientFactory` that accepts a type/generic-type, and resolves the string name for it.

```c#
public static class HttpClientFactoryExtensions 
{
  public static HttpClient CreateClient<TClient>(this IHttpClientFactory factory) =>
      factory.CreateClient(typeof(TClient).Name); //should use TypeNameHelper instead
}
```

**Comment by rynowak** [comment]
Closing this. No plans to add more concepts here.
