### ISSUE TITLE
Describe implementation factory with TImplementation

### ISSUE THREAD

**Issue by deanmarcussen** [aspnet/Extensions#2039]
### Problem
I am trying to register multiple services with a service descriptor and implementation factory like 
```
ServiceDescription.Scoped<ITestDiModel, TestDiModel1>(
    implementationFactory => new TestDiModel1());
ServiceDescription.Scoped<ITestDiModel, TestDiModel2>(
    implementationFactory => new TestDiModel2());
```

and I want to be able to identify the ServiceDescriptor so that I can (optionally) remove or replace them later with something like 

```
services.Remove(services.FirstOrDefault(x => x.ServiceType == typeof(ITestDiModel) &&
    x.Lifetime == ServiceLifetime.Scoped &&
    x.ImplementationType == typeof(TestDiModel2)));
```

but the implementation for
```
        public static ServiceDescriptor Scoped<TService, TImplementation>(
            Func<IServiceProvider, TImplementation> implementationFactory)
```
ignores `TImplementation` when it calls `Describe` and the `ServiceDescription` constrcutor does not have an overload that will take `TService, TImplementation` and `implementationFactory` 

It seems odd to me that the static factory methods would support TImplementation but do nothing with it?

### Solution

A constructor overload 
```
public ServiceDescriptor(Type serviceType, Type implementationType, Func<IServiceProvider, object> factory, ServiceLifetime lifetime)
```

and an update to the Static Factory Methods to support this

### Alternatives

I can remove the service by examining the implementationFactory
```
            services.Remove(services.FirstOrDefault(x => x.ServiceType == typeof(ITestDiModel) && 
                x.Lifetime == ServiceLifetime.Scoped &&
                x.ImplementationFactory.Method.ReturnType == typeof(TestDiModel2)));
```

**Comment by anurse** [comment]
> It seems odd to me that the static factory methods would support TImplementation but do nothing with it?

I believe this is just to help ensure that `TImplementation` is assignable to a variable of type `TService`. Note the generic constraint:

https://github.com/aspnet/Extensions/blob/aa92cf6056ee998e6718b780070d65f9029ea9ac/src/DependencyInjection/DI.Abstractions/src/ServiceDescriptor.cs#L295

In general, the `ServiceDescriptor` is only ever expected to have **one of** `ImplementationInstance`, `ImplementationType` and `ImplementationFactory` set. Setting both `ImplementationFactory` and `ImplementationType` would require not only us to change our implementation to ensure we use the factory and **not** the type, but would also require third-party containers (like Autofac) to do so.

That's a pretty breaking change and I don't think the value of it would outweigh the pretty high cost to the ecosystem.

> I want to be able to identify the ServiceDescriptor so that I can (optionally) remove or replace them later

Can you expand a bit on why you want to do this? It might help to understand the underlying scenario you're trying to achieve.

**Comment by deanmarcussen** [comment]
> In general, the `ServiceDescriptor` is only ever expected to have **one of** `ImplementationInstance`, `ImplementationType` and `ImplementationFactory` set. Setting both `ImplementationFactory` and `ImplementationType` would require not only us to change our implementation to ensure we use the factory and **not** the type, but would also require third-party containers (like Autofac) to do so.
> 
> That's a pretty breaking change and I don't think the value of it would outweigh the pretty high cost to the ecosystem.

Ok, so that makes sense, and if this suggestion would be such a breaking change, then it is unlikely to be worth while.

> Can you expand a bit on why you want to do this? It might help to understand the underlying scenario you're trying to achieve.

With a modular app, which has third party libraries, and modules, there are some modules that when enabled, will want to remove some of the services that other default modules have registered, with multiple Service Descriptors, of the same 'ServiceType', with the Service Provider.

Depending on how they are registered (which as some are third parties I have less control over) these services are either easily identifiable, or harder to identify.

For example if you register
```
services.TryAddEnumerable(ServiceDescriptor.Scoped<ITestDiModel, TestDiModel1>(x => new TestDiModel1()));
services.TryAddEnumerable(ServiceDescriptor.Scoped<ITestDiModel, TestDiModel2>(x => new TestDiModel2()));
```

then you can examine the return type of the implementation factory to choose which service to remove

but there is nothing that stops a registration like this occuring
```
services.AddScoped<ITestDiModel>(x => new TestDiModel1());
services.AddScoped<ITestDiModel>(x => new TestDiModel2());
```

which leaves the return type of the factory as `ITestDiModel`, meaning if you want to remove `TestDiModel2` you can only guess which one it will be (based on the index I suppose)

This is a pretty minor issue for me though, so if there's nothing to be done about it, more than happy to close

**Comment by anurse** [comment]
And in this case you are resolving `IEnumerable<ITestDiModel>`? I ask because if you just resolve `ITestDiModel`, the *last* registration will be used (allowing services to override each other).

I think you're right that there just isn't a great solution for handling this when registering `IEnumerable` DI services. Adding a new API to `IServiceCollection` or modifying `ServiceDescriptor` would be a pretty heavy breaking change, so the pattern you're using is probably the best way forward.

I'll close this for now then.

**Comment by deanmarcussen** [comment]
> And in this case you are resolving `IEnumerable<ITestDiModel>`? 

Yes, in this scenario.

Cool

**Comment by anurse** [comment]
Yeah, if you're using `IEnumerable` you are kinda stuck here. 😦
