### ISSUE TITLE
IHostApplicationLifetime cannot be replaced

### ISSUE THREAD

**Issue by davidmatson** [aspnet/Extensions#2044]
### Describe the bug
The IHostApplicationLifetime interface is not replaceable.

### To Reproduce

Program.cs:
```c#
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Hosting.Internal;
using Microsoft.Extensions.Logging;
using System.Threading;

class Program
{
    static void Main()
    {
        IHostBuilder builder = new HostBuilder()
            .ConfigureLogging(logging =>
            {
                logging.AddConsole();
            })
            .ConfigureServices(services =>
            {
                services.AddSingleton<IHostApplicationLifetime, CustomHostApplicationLifetime>();
            });

        using (IHost host = builder.Build())
        {
            host.Start();
            host.WaitForShutdown();
        }
    }

    class CustomHostApplicationLifetime : IHostApplicationLifetime
    {
        readonly ApplicationLifetime inner;

        public CustomHostApplicationLifetime(ILogger<ApplicationLifetime> logger)
        {
            inner = new ApplicationLifetime(logger);
        }

        public CancellationToken ApplicationStarted => inner.ApplicationStarted;

        public CancellationToken ApplicationStopping => inner.ApplicationStopping;

        public CancellationToken ApplicationStopped => inner.ApplicationStopped;

        public void StopApplication()
        {
            inner.StopApplication();
        }
    }
}
```

App.csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="3.0.0-preview6.19304.6" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="3.0.0-preview6.19304.6" />
  </ItemGroup>
</Project>
```

Run App.exe.

### Expected behavior
The program starts.

### Actual behavior
The program fails at startup with a NullReferenceException.

### Additional context
This part may have been missed when #966 was implemented - the fix might be as simple as removing the following cast in the constructor of Host:

https://github.com/aspnet/Extensions/blob/69a5445f14c81fd200a28c374a1d62bebadb36a3/src/Hosting/Hosting/src/Internal/Host.cs#L30

(and having the field be of type IHostApplicationLifetime rather than ApplicationLifetime).

Note also that if the example above is changed to register/implement IApplicationLifetime instead of IHostApplicationLifetime, it does not throw though that class does not get used, which I suspect is intended based on HostBuilder:
https://github.com/aspnet/Extensions/blob/69a5445f14c81fd200a28c374a1d62bebadb36a3/src/Hosting/Hosting/src/HostBuilder.cs#L213

Though a possibly better option might be to add an during registration if an existing IApplicationLifetime is registered to turn it into an IHostApplicationLifetime so that existing custom implementations continue to work.

**Comment by Tratcher** [comment]
This is by design. Can you describe your scenario for replacing IHostApplicationLifetime ?

The main design issue here is that the host needs to call methods that aren't on the interface in order to trigger the events.
https://github.com/aspnet/Extensions/blob/69a5445f14c81fd200a28c374a1d62bebadb36a3/src/Hosting/Hosting/src/Internal/Host.cs#L57
They're not the interface because nobody but the host should be calling them.

**Comment by davidmatson** [comment]
No particular scenario; I just noticed it trying to understand some related problems. I thought the overall principle was that anything public interface registered in the container was intended to be user-replaceable, but understood if that's not the case here.

Is there any way to tell from the code/docs what interfaces are intended to be replaceable vs. just accessible as dependencies?

**Comment by Tratcher** [comment]
That's the hardest one to replace. IHostingEnvironment and IConfiguration should be replaceable so long as nobody captured them from the HostBuilderContext.
https://github.com/aspnet/Extensions/blob/69a5445f14c81fd200a28c374a1d62bebadb36a3/src/Hosting/Hosting/src/HostBuilder.cs#L206-L215

**Comment by davidmatson** [comment]
OK, if we could somehow document any cases that aren't inteded to be user-replaceable, that would be great. Maybe register them both as an interface as well as as a contrete type, and then access them as the concrete type from constructors that need that implementation? Or just a comment in the code/official docs?

**Comment by Tratcher** [comment]
Do you have a suggestion for where in the docs or code a comment about this would be discoverable?

**Comment by davidmatson** [comment]
An XML doc comment <remarks>This interface is not intended to be user-replaceable.</remarks> or something like that on the interface itself would probably be ideal. In the code, either where the services.AddSingleton call is or even the constructor where it's consumed could work. Thanks!

**Comment by anurse** [comment]
Remarks don't show up in IntelliSense, but I'll bash out a quick PR to update this doc comment.

**Comment by ThomasTosik** [comment]
Good that i found someone with the same issue :). We used a replaced IApplicationLiftime in 2.2 to guarantee that some shutdown work will be done first. But it seems we are stuck in a thought loop about app shutdown. Does anyone has a better solution other than guaranteeing that your service does not care about internal shutdown order of components? Or maybe we are misinterpreting something.

**Comment by Pilchie** [comment]
@Tratcher - looks like you've been involved here, and there is an open PR.  Can you rebase it, and we'll consider trying to take this for GA to get it done/

**Comment by Tratcher** [comment]
@Pilchie does a doc comment update meet the bar for 3.x at this point? Merging to master seems adequate.

**Comment by Tratcher** [comment]
> to guarantee that some shutdown work will be done first. 

What kind of shutdown work?

**Comment by Pilchie** [comment]
You're right - master seems fine for this.
