### ISSUE TITLE
Multi-target packages for netcoreapp3.0 and remove corefx dependencies if possible

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Extensions#2056]
The projects in this repo should be updated to cross-compile for their current TFM and netcoreapp3.0. For the netcoreapp3.0 TFM, we can remove dependencies such as System.Memory and System.Runtime.CompilerServices.Unsafe.

cc @davidfowl

**Comment by JunTaoLuo** [comment]
cc @mkArtakMSFT @anurse @ajcvickers @Pilchie any concerns with this plan? Reducing unnecessary dependencies would be a good thing to do in general and it also ends up helping source build by reducing the number of external dependencies.

**Comment by anurse** [comment]
So it reduces source-build dependencies because we only source-build the netstandard2.1 target?

**Comment by JunTaoLuo** [comment]
Yes in source build we would only be building the netstandard 2.1 target.

**Comment by anurse** [comment]
Ok, then it sounds like it will be useful in 3.0. If it weren't for that I'd probably lean towards saying "Cool, but let's do that later" since the old targets will still have the dependency. Source build makes it worth doing now though.

**Comment by ajcvickers** [comment]
Sounds okay to me. /cc @bricelam

**Comment by JunTaoLuo** [comment]
FYI it turns out that we'll likely need to cross-target to netcoreapp3.0 instead of netstandard2.1. I don't think this affects anyone any differently though.

**Comment by JunTaoLuo** [comment]
Also this will mean we need to react in AspNetCore to cross-target as well.

**Comment by JunTaoLuo** [comment]
Changes are made in Extensions. There's no change required in AspNetCore-Tooling and the AspNetCore changes are in progress in https://github.com/aspnet/AspNetCore/pull/12936

**Comment by dleeapho** [comment]
@JunTaoLuo so can this issue be closed?
