### ISSUE TITLE
Consider patching #2060 for 2.2

### ISSUE THREAD

**Issue by rynowak** [aspnet/Extensions#2064]
#2060 is a significant performance regression from 2.1->2.2 in a mainline usage scenario of the client factory with a safe and simple fix.

**Comment by anurse** [comment]
Is it still important for us to port this patch to 2.2 given that 3.0 is out now and 2.2 [EOLs in December](https://dotnet.microsoft.com/platform/support/policy/dotnet-core)?

**Comment by rynowak** [comment]
I still want to. EOL means we stop patching in december, not that we stop patching randomly a few months before.

 We know that customers don't port apps **IMMEDIATELY** there's some lag.

**Comment by anurse** [comment]
Closing as we don't have a patch vehicle for this before 2.2 EOLs.
