### ISSUE TITLE
Default expiration of cached items and how to cache an item forever (so that it never expires)

### ISSUE THREAD

**Issue by EnricoMassoneDeltatre** [aspnet/Extensions#2067]
Hi, 

I'm using the [MemoryCache class](https://github.com/aspnet/Extensions/blob/master/src/Caching/Memory/src/MemoryCache.cs).

Based on my understanding **if no size limit is set on the cache instance and no expiration is specified when an item is added to the cache**, then **the item will stay in the cache forever**. Put another way, **by default each item added to the cache will stay in the cache indefinitely without expiring**. 

Is my understanding correct ?

I'm actually using the extension method `GetOrCreateAsync` in order to add items to my cache; even in this case the default behavior is caching an item forever ? If my need is **caching items indefinitely** can I **avoid** tricks like adding items having a huge absolute expiration (e.g: 1 year) ?

Thanks for helping !

**Comment by Tratcher** [comment]
There's also a public [Compact](https://github.com/aspnet/Extensions/blob/0040eaca278f18962e982b7e3d25cd7dc957e745/src/Caching/Memory/src/MemoryCache.cs#L389) API, but it's not widely used.

You can use CacheItemPriority.NeverRemove to override all evictions except an items own expiration.
https://github.com/aspnet/Extensions/blob/0040eaca278f18962e982b7e3d25cd7dc957e745/src/Caching/Abstractions/src/CacheItemPriority.cs#L15

**Comment by EnricoMassoneDeltatre** [comment]
@Tratcher,

to summarize the rule for infinite caching of an item is: 

"don't set explicitly an expiration and specify CacheItemPriority.NeverRemove (which is used in case of an explicit call to the Compact api by the programmer)". 

Thanks for claryfing
