### ISSUE TITLE
Strange DI behaviour with ASPNETCORE_ENVIRONMENT

### ISSUE THREAD

**Issue by DenisPimenov** [aspnet/Extensions#2113]
### Describe the bug 
I have aspnetcore application, where singleton type has a dependency on scoped type. When a variable is defined ASPNETCORE_ENVIRONMENT=Development, I get an InvalidOperationException: Cannot consume scoped service 'B' from singleton 'A', but when the ASPNETCORE_ENVIRONMENT='Anything', an exception is not raised and application started.

### To Reproduce
1. Using this version of ASP.NET Core '2.2.6'
2. Run this code https://gist.github.com/DenisPimenov/fbde9d1f91170d2423cee1089a29028c
3. With these arguments ASPNETCORE_ENVIRONMENT="Production"
4. Application started without exceptions

### Expected behavior
Application should be terminated with InvalidOperationException

### Additional context
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.301
 Commit:    70d6be0814

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.301/

**Comment by rynowak** [comment]
In development mode we run some extra validations as the container is built. The fact that you're seeing an error means that something is wrong. 

In this case you're using a scoped service from a singleton - meaning that you're creating a long-lived instance of something that you expect to be scoped.

We don't run this validation at startup time in production scenarios because it's slow.

**Comment by DenisPimenov** [comment]
This validations has public api?

**Comment by rynowak** [comment]
@pakrym

**Comment by pakrym** [comment]
You can use `UseDefaultServiceProvider` method to configure the scope validation to always be on:

``` C#
  public static IWebHostBuilder CreateHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseDefaultServiceProvider(options => options.ValidateScopes = true)
                .UseStartup<Startup>();

```

**Comment by DenisPimenov** [comment]
Thank you for your comments.
