### ISSUE TITLE
ConsoleLifetime doesn't do graceful on closing Console Window

### ISSUE THREAD

**Issue by lg2de** [aspnet/Extensions#2179]
### Describe the bug
Running host with hosted service very slow on shutdown (stop) will not be shutdown gracefully when Console Window (on Windows) is closed, even `ShutdownTimeout` is already configured.
It is shutting down gracefully as expected when pressing CTRL-C.

The host is reporting "Application is shutting down..." but after a timeout of around 5 seconds the process is terminated without further notice.
Because of this output I think it is a bug.

There is the issue dotnet/coreclr#8565 discussing such issue.
Maybe it must be fixed there, but the discussion does not get progress (anymore).
So, it may be work-arounded in aspnet?

### To Reproduce
```cs
    class Program
    {
        static async Task Main(string[] args)
        {
            try
            {
                await Host.CreateDefaultBuilder()
                    .ConfigureServices(delegate(HostBuilderContext context, IServiceCollection services)
                    {
                        services.AddHostedService<ShowController>();
                        services.Configure<HostOptions>(o => o.ShutdownTimeout = TimeSpan.FromSeconds(30));
                    }).RunConsoleAsync();

                Console.WriteLine("done");
                Thread.Sleep(TimeSpan.FromSeconds(1));
            }
            catch (OperationCanceledException)
            {
                Console.WriteLine("#### aborted ####");
                Thread.Sleep(TimeSpan.FromSeconds(1));
            }
        }
    }

    public class ShowController : IHostedService
    {
        public Task StartAsync(CancellationToken cancellationToken)
        {
            return Task.CompletedTask;
        }

        public async Task StopAsync(CancellationToken cancellationToken)
        {
            await Task.Delay(TimeSpan.FromSeconds(10));
            Console.WriteLine("stopped");
        }
    }
```

### Expected behavior
When closing the console application by closing the console window, all services should be shut down completely before the process ends.

### Additional context
```
C:\>dotnet --info
.NET Core SDK (gemäß "global.json"):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\

Host (useful for support):
  Version: 3.0.0-preview6-27804-01
  Commit:  fdf81c6faf

.NET Core SDKs installed:
[...]
  3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
[...]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
[...]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by anurse** [comment]
My understanding is that the 5 second timeout [comes from the OS itself](https://docs.microsoft.com/en-us/windows/console/handlerroutine?redirectedfrom=MSDN) on receiving the CTRL_CLOSE_EVENT (which is triggered when the window is closed and eventually triggers OnProcessExit). I don't think we can do anything to affect this in ASP.NET Core. You can apparently adjust this timeout at the machine level (details in the doc linked earlier) but there's no process-level control over it.

To be clear, the timeout **is** working correctly if you terminate with Ctrl-C? That's what I see.

I'm closing this as I don't believe we can do anything to suppress the Console Window Close timeout in ASP.NET Core.
