### ISSUE TITLE
How to match .gitignore files using PhysicalFileProvider.Watch?

### ISSUE THREAD

**Issue by natenho** [aspnet/Extensions#2215]
The PhysicalFileProvider is not watching the pattern ` /**/.gitignore`
I think it may be a bug, but I want to confirm if I'm not doing something wrong.

The globbing pattern provided by this class seems to lack some common glob pattern features.

Try creating/change a ".gitignore" file in the folder of the application bellow. It doesn't detect any change:

```csharp
class Program
    {
        static void Main(string[] args)
        {
            var fileProvider = new PhysicalFileProvider(Directory.GetCurrentDirectory());
            var changeToken = fileProvider.Watch($"/**/.gitignore");
            changeToken.RegisterChangeCallback((o) => Console.WriteLine("Change detected!"), null);

            Console.Read();  
        }
    }
```

Removing the "." from the filename works.

**Comment by pranavkm** [comment]
You'll need to set up a `PhysicalFileProvider` with an [`ExclusionFilters`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.fileproviders.physical.exclusionfilters?view=aspnetcore-2.2) setting that allows folders with dot prefix. The default is to exclude these files.
