### ISSUE TITLE
[Feature Request] Add Config.NewtonsoftUserSecrets

### ISSUE THREAD

**Issue by Kahbazi** [aspnet/Extensions#2280]
Since `Config.UserSecrets` is using `Config.Json` and `Config.Json` used to work with `Newtonsoft.Json`, is it a good idea to also have a user secrets config which is working with `Newtonsoft.Json`?

**Comment by Eilon** [comment]
I would consider UserSecrets' usage of JSON to be an implementation detail. I think the only supported way to read/write from that file is using the `dotnet user-secrets` command line tool and using the Configuration APIs. Whether it's stored in a JSON file, a database, the Windows registry, or somewhere else, is all hidden (but not very well hidden :smile: )
