### ISSUE TITLE
Dependency injection and ServiceDescriptor equivalency

### ISSUE THREAD

**Issue by MV10** [aspnet/Extensions#2364]
Should a DI service registered using `ServiceDescriptor.Singleton<T,U>` be indistinguishable from a service registered with `AddSingleton<T,U>`? I was helping someone troubleshoot an experimental Core 3.0 RC1 migration of a web app that used a custom `IDistributedCache` implementation, and what we were seeing is that the default in-memory cache was always being used (which is added somewhere in the MVC / RazorPages stack, I think as part of the tag helpers).

I don't know why they were using this syntax (it's an ongoing port of a much older app, so I'm guessing this was more common at some point?), but the app registered his custom cache this way, and apparently this worked at some point in the past:

```csharp
services.Add(ServiceDescriptor.Singleton<IDistributedCache, CacheService>());
```

When we changed the service registration to this, it started working as expected:

```csharp
services.AddSingleton<IDistributedCache, CacheService>();
```

Even though the first method is a bit more wordy (and I suspect old and perhaps semi-obsolete), shouldn't they be equivalent?

**Comment by brandondahler** [comment]
Looks 100% equivalent to me.  Both are equivalent to:
``` C#
services.Add(new ServiceDescriptor(typeof(IDistributedCache), typeof(CacheService), ServiceLifetime.Singleton))
```
___
For
``` C#
services.Add(ServiceDescriptor.Singleton<IDistributedCache, CacheService>());
```
via
https://github.com/aspnet/Extensions/blob/master/src/DependencyInjection/DI.Abstractions/src/ServiceDescriptor.cs#L355-L360
https://github.com/aspnet/Extensions/blob/master/src/DependencyInjection/DI.Abstractions/src/ServiceDescriptor.cs#L496-L504
https://github.com/aspnet/Extensions/blob/master/src/DependencyInjection/DI.Abstractions/src/ServiceDescriptor.cs#L515-L518
___
For
``` C# 
services.AddSingleton<IDistributedCache, CacheService>();
```
via
https://github.com/aspnet/Extensions/blob/master/src/DependencyInjection/DI.Abstractions/src/ServiceCollectionServiceExtensions.cs#L474-L484
https://github.com/aspnet/Extensions/blob/master/src/DependencyInjection/DI.Abstractions/src/ServiceCollectionServiceExtensions.cs#L408-L429
https://github.com/aspnet/Extensions/blob/master/src/DependencyInjection/DI.Abstractions/src/ServiceCollectionServiceExtensions.cs#L651-L660

**Comment by davidfowl** [comment]
Yes that’s surprising as one calls the other

**Comment by MV10** [comment]
I'll close this, I'm back in the office today and we could not reproduce it.

I'm not sure if this would be a problem (don't really have time to try it myself) but I suspect he did `AddSingleton` with a `ServiceDescriptor` instead of just `Add` -- but since he was actively coding the thing, whatever it was didn't get checked into source control before I suggested the simlified syntax.
