### ISSUE TITLE
How to create a Host instance?

### ISSUE THREAD

**Issue by DaemonWalker** [aspnet/Extensions#2387]
I'm trying to make an ioc container by myself,but having problems with creating an instance of Microsoft.Extensions.Hosting.Internal.Host .
I can't create an instance of OptionsFactory<ConsoleLifetimeOptions>

Here's the call chain `IHost->Host->IHostLifetime->ConsoleLifetime->IOptions<ConsoleLifetimeOptions>->OptionsManager<ConsoleLifetimeOptions>->IOptionsFactory<ConsoleLifetimeOptions>->OptionsFactory<ConsoleLifetimeOptions>`.
But there's no ImplementationType for params in OptionFactory's constructor(like `IConfigureOptions<ConsoleLifetimeOptions>`),I tried using null to  replace params but it doesn't work:(

So how to solve it?
Thanks a lot~

**Comment by Tratcher** [comment]
See 
https://github.com/aspnet/Extensions/blob/f0bbe1da7dcd1fe28ac1bfbb6cfb89fb99e18f60/src/Options/Options/src/OptionsServiceCollectionExtensions.cs#L33
https://github.com/aspnet/Extensions/blob/f0bbe1da7dcd1fe28ac1bfbb6cfb89fb99e18f60/src/Options/Options/src/OptionsFactory.cs

Does your container handle open generics?

**Comment by DaemonWalker** [comment]
> See
> https://github.com/aspnet/Extensions/blob/f0bbe1da7dcd1fe28ac1bfbb6cfb89fb99e18f60/src/Options/Options/src/OptionsServiceCollectionExtensions.cs#L33
> 
> 
> https://github.com/aspnet/Extensions/blob/f0bbe1da7dcd1fe28ac1bfbb6cfb89fb99e18f60/src/Options/Options/src/OptionsFactory.cs
> Does your container handle open generics?

I handled `IOptionsFactory<>` to `OptionsFactory<>`.
The problem is that I can't create a instance of  `OptionsFactory<ConsoleLifetimeOptions>`.
Like
https://github.com/aspnet/Extensions/blob/f0bbe1da7dcd1fe28ac1bfbb6cfb89fb99e18f60/src/Options/Options/src/OptionsFactory.cs#L24
or
https://github.com/aspnet/Extensions/blob/f0bbe1da7dcd1fe28ac1bfbb6cfb89fb99e18f60/src/Options/Options/src/OptionsFactory.cs#L33
They both need a `IEnumerable<IConfigureOptions<TOptions>>` and I try to make it `List<IConfigureOptions<TOptions>>` but there's no ImplementationType for `IConfigureOptions<TOptions>` is `serviceDescriptors.`

**Comment by Tratcher** [comment]
https://github.com/aspnet/Extensions/blob/f0bbe1da7dcd1fe28ac1bfbb6cfb89fb99e18f60/src/Options/Options/src/OptionsServiceCollectionExtensions.cs#L72

**Comment by DaemonWalker** [comment]
> https://github.com/aspnet/Extensions/blob/f0bbe1da7dcd1fe28ac1bfbb6cfb89fb99e18f60/src/Options/Options/src/OptionsServiceCollectionExtensions.cs#L72
> 
> 
> https://github.com/aspnet/Extensions/blob/256db1159910527cbe5d7e72623953fb5f6258b0/src/Options/Options/src/OptionsBuilder.cs#L56
> 
> 
> https://github.com/aspnet/Extensions/blob/256db1159910527cbe5d7e72623953fb5f6258b0/src/Options/Options/src/ConfigureOptions.cs#L12

I call them manually and it finally works...
I checked Extenssion.DependcyInjection and Autofac but neither of them call those extenssion methods so I thought it was called automatically :(

How does Asp.Net Core DependencyInjection handle this?

**Comment by Tratcher** [comment]
Are you running a full web app or a minimal console app? It may just be a coincidence that these are always called by web app components or CreateDefaultBuilder.
https://github.com/aspnet/Extensions/blob/026865e0bd62db73dc71fc72ec8cc91904cd1995/src/Hosting/Hosting/src/Host.cs#L56

**Comment by DaemonWalker** [comment]
> Are you running a full web app or a minimal console app? It may just be a coincidence that these are always called by web app components or CreateDefaultBuilder.
> https://github.com/aspnet/Extensions/blob/026865e0bd62db73dc71fc72ec8cc91904cd1995/src/Hosting/Hosting/src/Host.cs#L56

I'm using asp.net core web api demo created by visual studio(WeatherForecast).
Here is my Program.cs(I added list line UseServiceProviderFactory)
```cs
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                }).UseServiceProviderFactory(new ServiceProviderFactory());
    }
```

Here's my Startup.cs (I didn't change it)
```cs
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }
        public IConfiguration Configuration { get; }
        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
        }
        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            app.UseRouting();
            app.UseAuthorization();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
    }
```
 `.UseServiceProviderFactory(new ServiceProviderFactory())` is my container,if I remove this line, app works perfectly,if I replace it with .UseServiceProviderFactory(new Autofac.Extensions.DependencyInjection.AutofacServiceProviderFactory()),it alse works(I only add this line when I'm using Autofac)
But when I use my container,I can't find a ImplementationType  for `IConfigureOptions<ConsoleLifetimeOptions>` or 'IPostConfigureOptions<ConsoleLifetimeOptions>'  in the ServiceCollection passed by
https://github.com/aspnet/Extensions/blob/026865e0bd62db73dc71fc72ec8cc91904cd1995/src/Hosting/Hosting/src/HostBuilder.cs#L226
I output them to a txt file https://github.com/DaemonWalker/Daem0n/blob/master/Daem0n.SimIoc/ServicedDescriptors.txt

I  modified Startup.ConfigureServices like this and it worked
```cs
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();

            services.Configure<ConsoleLifetimeOptions>(_ => { });
            services.PostConfigure<ConsoleLifetimeOptions>(_ => { });
            services.Configure<HostOptions>(_ => { });
            services.PostConfigure<HostOptions>(_ => { });
            services.Configure<SocketTransportOptions>(_ => { });
            services.PostConfigure<SocketTransportOptions>(_ => { }); 
            services.Configure<KestrelServerOptions>(_ => { });
            services.PostConfigure<KestrelServerOptions>(_ => { });
            services.Configure<FormOptions>(_ => { });
            services.PostConfigure<FormOptions>(_ => { });
        }
```

Do I miss some functions to call? I don't think this is a good way to get ImplementationTypes😂

**Comment by Tratcher** [comment]
It sounds like your open generics implementation isn't working right. @halter73 may have more context on that.

**Comment by halter73** [comment]
> They both need a `IEnumerable<IConfigureOptions<ConsoleLifetimeOptions>>` and I try to make it `List<IConfigureOptions<ConsoleLifetimeOptions>>` but there's no ImplementationType for `IConfigureOptions<ConsoleLifetimeOptions>` in `serviceDescriptors`.

I think this is your main issue. IoC Containers used by ASP.NET Core are expected to return an empty IEnumerable if there is no service definition for the contained type. So in this case, if theres no definition for `IConfigureOptions<ConsoleLifetimeOptions>` or `IConfigureOptions<>` , the container should simply inject an empty `IEnumerable<IConfigureOptions<ConsoleLifetimeOptions>>`.

We have specification tests that verify IoC containers meet the minimum requirements for ASP.NET Core. The specific test to verify this behavior is called [NonexistentServiceCanBeIEnumerableResolved](https://github.com/aspnet/Extensions/blob/026865e0bd62db73dc71fc72ec8cc91904cd1995/src/DependencyInjection/DI.Specification.Tests/src/DependencyInjectionSpecificationTests.cs#L611-L623). You can test your own container by deriving from the DependencyInjectionSpecificationTests test class and overriding the [CreateServiceProvider](https://github.com/aspnet/Extensions/blob/026865e0bd62db73dc71fc72ec8cc91904cd1995/src/DependencyInjection/DI.Specification.Tests/src/DependencyInjectionSpecificationTests.cs#L15).

**Comment by DaemonWalker** [comment]
> > They both need a `IEnumerable<IConfigureOptions<ConsoleLifetimeOptions>>` and I try to make it `List<IConfigureOptions<ConsoleLifetimeOptions>>` but there's no ImplementationType for `IConfigureOptions<ConsoleLifetimeOptions>` in `serviceDescriptors`.
> 
> I think this is your main issue. IoC Containers used by ASP.NET Core are expected to return an empty IEnumerable if there is no service definition for the contained type. So in this case, if theres no definition for `IConfigureOptions<ConsoleLifetimeOptions>` or `IConfigureOptions<>` , the container should simply inject an empty `IEnumerable<IConfigureOptions<ConsoleLifetimeOptions>>`.
> 
> We have specification tests that verify IoC containers meet the minimum requirements for ASP.NET Core. The specific test to verify this behavior is called [NonexistentServiceCanBeIEnumerableResolved](https://github.com/aspnet/Extensions/blob/026865e0bd62db73dc71fc72ec8cc91904cd1995/src/DependencyInjection/DI.Specification.Tests/src/DependencyInjectionSpecificationTests.cs#L611-L623). You can test your own container by deriving from the DependencyInjectionSpecificationTests test class and overriding the [CreateServiceProvider](https://github.com/aspnet/Extensions/blob/026865e0bd62db73dc71fc72ec8cc91904cd1995/src/DependencyInjection/DI.Specification.Tests/src/DependencyInjectionSpecificationTests.cs#L15).

Uh, I get it~
Appreciate to you and @Tratcher's help~

**Comment by halter73** [comment]
@DaemonWalker BTW, if you want to add the specification tests to your own test project, you can reference the [Microsoft.Extensions.DependencyInjection.Specification.Tests NuGet Package](https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection.Specification.Tests/). This package includes the DependencyInjectionSpecificationTests abstract base class that your own test project can derive from. These are xUnit tests FWIW.
