### ISSUE TITLE
Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.Azure.Functions.Extensions.DependencyInjection.IFunctionsHostBuilder.get_Services()' after upgrading .net core 3.0

### ISSUE THREAD

**Issue by toanxyz** [aspnet/Extensions#2388]
### Describe the bug
It seems like there is a breaking change with Microsoft.Extensions.DependencyInjection library. When we upgrade the Azure Function to .net core 3.0 and use Microsoft.Extensions.Http 3.0.0, there is an error as the attached image below.

### Expected behavior
The azure function should run normally.

### To Reproduce

Used packages:

- Microsoft.NET.Sdk.Functions version 1.0.29
- Microsoft.Azure.Functions.Extensions version 1.0.0
- Microsoft.Extensions.Http version 3.0.0

```csharp
public class Startup : FunctionsStartup
{
    public override void Configure(IFunctionsHostBuilder builder)
    {
        builder.Services.AddHttpClient();
    }
}
```

### Screenshots
![Console Error](https://user-images.githubusercontent.com/6207857/65506594-207e9b00-def6-11e9-83f7-fff8b7d0e5c7.png)

![csproj format](https://user-images.githubusercontent.com/6207857/65506598-24aab880-def6-11e9-8ce4-3dce02c1c563.PNG)

**Comment by davidfowl** [comment]
That missing method exception is coming from the functions runtime, not this library. The missing member is `IFunctionsHostBuilder.Services`.

The issue should be moved here https://github.com/Azure/azure-functions-host/. 

PS: The functions runtime hasn't been updated to .NET Core 3.0 so this likely isn't supported at the moment anyways.

**Comment by davidfowl** [comment]
cc @fabiocav

**Comment by fabiocav** [comment]
Indeed. This should be in the repo you've linked to above.

Currently, there's no version of the CLI or the runtime that supports .NET Core 3.0. That will be available within the next couple of weeks (https://github.com/Azure/app-service-announcements/issues/200)

we should be able to close this issue here. 

@toanxyz feel free to open an issue against the host if you'd like to track this there.
