### ISSUE TITLE
.NET CORE HttpClientFactory  Alternative universal library?

### ISSUE THREAD

**Issue by JHeLiu** [aspnet/Extensions#2417]
Can I use HttpClientFactory in a packaged generic library?Is it ok to use the new object in.net without the need for an explicit injection?I've seen a lot of documentation, including Microsoft's official documentation, on dependency injection under.net CORE.However, there is now a requirement that you do not use summary injection, because the public method often has only the request address and request parameters, and the timeout time is adjusted appropriately

```
  // .net framework 
        public string Post(string url, string parm)
        {
            using (var http = new HttpClient())
            {

                return http.PostAsync(url, new StringContent(parm))
                    .Result.Content.ReadAsStringAsync().Result;
            }
        }
```
```

//.net core
        public string Post(string url, string parm)
        {
            var http = HttpClientFactory.Create();
            //???  Is that how you write it?
        }
```
As I said, a universal library can make callers do as little as possible, and I'd like to have an example,
So can you help me out?

**Comment by davidfowl** [comment]
There's no static API so to use it you'd need to create a `ServiceCollection`. Why are you using the HttpClientFactory? What features are you trying to use?

**Comment by JHeLiu** [comment]
@davidfowl 
You need a universal library, but the caller doesn't need to know some parameters. It's as simple as possible. Maybe just a url and request parameters.Do not use dependency injection because this library can be used in many places.For example, MS services, MS desktop applications, MS website applications and so on, I know how to use.net,.net CORE should do?Better have an example.The documents I found on the official website are not ideal, including a lot of materials I found these days, but I prefer an official solution.

**Comment by davidfowl** [comment]
That’s not what i was asking though. I was asking what features you’re using and why http client doesn’t suffice?

**Comment by JHeLiu** [comment]
I'm using less functionality, normal HTTP requests, including certificates, custom request headers,
But I found that it had this problem,A timeout may be set
https://nima-ara-blog.azurewebsites.net/beware-of-the-net-httpclient/
I would like to ask, is it resolved in the new version?Can I also use **using** to release connections as before?

**Comment by rynowak** [comment]
If you want to have a reasonably behaving HttpClient without using the factory, I'd suggest setting [this property](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.pooledconnectionlifetime?view=netcore-3.0#System_Net_Http_SocketsHttpHandler_PooledConnectionLifetime) to something reasonable for your scenario.

```C#
new HttpClient(new SocketsHttpHandler() { PooledConnectionLifetime = ... });
```

HttpClient Factory is an opinionated library with DI at it's core. We have no immediate plans to change that.
