### ISSUE TITLE
HttpClientFactoryServiceCollectionExtensions.AddHttpClient<TClient>(...) Method Documentation

### ISSUE THREAD

**Issue by jshunia** [aspnet/Extensions#2418]
The `HttpClientFactoryServiceCollectionExtensions.AddHttpClient<TClient>(...)` method documentation claims that:

> The client name will be set to the full name of <typeparamref name="TClient"/>.

However, it is actually set to the short name.

**Comment by brandondahler** [comment]
Appears to have already been addressed in #2177.

**Comment by rynowak** [comment]
Indeed
