### ISSUE TITLE
Q: DependencyInjection callee

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Extensions#2422]
Is there anyway to identify the constructor that required the injection of a given instant/creation of the object? and/or access metadata/attributes on the constructor parameter that is to be injected at runtime?

**Comment by davidfowl** [comment]
No there isn't. We don't provide that context.

**Comment by grahamehorner** [comment]
thank for your quick reply, do you think this is possible? If so what area should I look into with regards to providing some contextual information to the DI created object(s)

**Comment by davidfowl** [comment]
Nope, as part of the abstraction its hard to provide this sort of information. I'd recommend using another container that does provide this context.

**Comment by grahamehorner** [comment]
Thanks, will look to research other DI systems for this
