### ISSUE TITLE
Question: GetConnectionString in Microsoft.Extensions.Configuration.ConfigurationExtensions

### ISSUE THREAD

**Issue by Legends** [aspnet/Extensions#2425]
**Asp.NET Core v3.0**

In VS2019 I press F12 while method `GetConnectionString ` is in focus and a metadata file opens, where it shows the location of the source code:

_// C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\3.0.0\ref\netcoreapp3.0\Microsoft.Extensions.Configuration.Abstractions.dll_

Now when I open the above `dll`, my Decompiler shows 

`
public static string GetConnectionString(this IConfiguration configuration, string name)
        {
            throw null;
        }
`

But this is not the implementation. 
So I searched for it in this repo and found this `ref` branch which depicts this code above and a `src` branch which shows the actual implementation:

`public static string GetConnectionString(this IConfiguration configuration, string name)
        {
            return configuration?.GetSection("ConnectionStrings")?[name];
        }`

<h2>What is the `ref` branch? Or better, why do I not see the real implementation when using my decompiler</h2>

**Ref branch:** src/Configuration/Config.Abstractions/**ref**/Microsoft.Extensions.Configuration.Abstractions.netstandard2.0.cs

**Src branch:** src/Configuration/Config.Abstractions/**src**/ConfigurationExtensions.cs

**Comment by gfoidl** [comment]
In short: it is better for tooling (Visual Studio).

Further infos:
* [Reference assemblies](https://github.com/aspnet/Extensions/blob/master/docs/ReferenceAssemblies.md#reference-assemblies)
* [What are reference assemblies?](https://github.com/dotnet/docs/issues/2638)
* [evolution-of-design-time-assemblies](https://github.com/dotnet/standard/blob/master/docs/history/evolution-of-design-time-assemblies.md)

**Comment by Legends** [comment]
@gfoidl 
Thanks for the links posted!

How do you do it, if you want to examine the source code of a .net core method?
Do you go the respective git repo and search for it?
This `ref` stuff makes my Decompiler obsolete, cause there is no implementation, but `throw null` ;-)

**Comment by gfoidl** [comment]
Try https://source.dot.net/

**Comment by Legends** [comment]
Just tried `Directory.EnumerateFiles` or just `EnumerateFiles` but no luck.

**Comment by Legends** [comment]
This one is better: https://referencesource.microsoft.com

**Comment by MSDN-WhiteKnight** [comment]
It does not make decompiler obsolete, you just have to supply actual implementation assembly as input for it. It is contained in [Microsoft.Extensions.Configuration.Abstractions](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.Abstractions/) in `lib` subdirectory. It should be cached somewhere on your local disk if you were recently building something targeting it; or you can load it from NuGet Gallery yourself it it's not.

No idea why source.dot.net currently works so horribly and fails to find half of BCL types, though. Hope that's just a temporary issue.

**Comment by Legends** [comment]
@MSDN-WhiteKnight 

Earlier I was used to just click on the assembly under dependencies and my decompiler opens up the assembly, it was very comfortable.

**Offtopic:**
I also tried using symbol server and enabled all the options under `Tools->Options->Debugging` but it doesn't work.

For example when setting a breakpoint at `Directory.EnumerateFiles` it gives me this when I hit `F11`:

> ...
> 'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.2.1\System.IO.FileSystem.dll'. Symbols loaded.
> ...

**SRCSRV: The module 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.2.1\System.IO.FileSystem.dll' does not contain source server information**
