### ISSUE TITLE
For EventLog logging the default source is ".NET Runtime" and not "Application"

### ISSUE THREAD

**Issue by amgdy** [aspnet/Extensions#2446]
### Describe the bug
For EventLog logging the default source is ".NET Runtime" and not "Application". In the documentations it's writtern Application but the actual is .NET Runtime

### To Reproduce
1. Add `loggingBuilder.AddEventLog();` to the logging configuration
2. Start log using any level like `_logger.LogCritical(ex,...`
3. Check the Event Views and you will find it logged under `.NET Runtime` Source

**Comment by davidfowl** [comment]
That's by design. We need to update the docs (this changed in 3.0)

**Comment by davidfowl** [comment]
Fixed in #2400
