### ISSUE TITLE
HttpclientFactory closes connection immediately with express.js server

### ISSUE THREAD

**Issue by kedarkdr** [aspnet/Extensions#2451]
HttpclientFactory of .net core doesn't seem to keep the connection or handler in established mode of the request is made to express js server, however if the request is made to a .net server then the connection remains in established state for default 2 mins.

I have a very simple express web app, which has below route, and server is listening on port 3000

```javascript
app.get('/text', (req, res) => res.json('Sample text.'));
```

and from .net application the call is made as below

```C#
var httpClient = _httpClientFactory.CreateClient();
var request = new HttpRequestMessage(
                HttpMethod.Get,
                "http://localhost:3000/text");
request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
using (var response = await httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead))
{
                var stream = await response.Content.ReadAsStreamAsync();
                response.EnsureSuccessStatusCode();
}
```
when connection status is checked using netstat -a, the connection goes into close_wait mode immediately after the call.

any inputs are appreciated

**Comment by rynowak** [comment]
Does this reproduce with a normal `HttpClient` (ie: not using the factory)?

**Comment by kedarkdr** [comment]
Yes, the issue happens with normal `HttpClient`  too

**Comment by davidfowl** [comment]
Can you use a network tracing tool like tcpdump or wireshark or fiddler to compare response from the ASP.NET Core application and expressjs. It's possible the request isn't a keep alive or something is setting a connection-close header.

**Comment by rynowak** [comment]
If you're still looking for help with this I'd suggest asking on dotnet/corefx. Any problem that reproduces with plain HttpClient is not a client factory bug.
