### ISSUE TITLE
Support for HTTP/2 DefaultRequestVersion

### ISSUE THREAD

**Issue by theezak** [aspnet/Extensions#2455]
For HTTP client extensions: It appears that the HttpClient version that supports HTTP/2 is not being pulled into a project that targets netstandard2.1/netcoreapp3.0 . Am I missing something or is that not (yet) supported?

**Comment by Pilchie** [comment]
@rynowak ?

**Comment by theezak** [comment]
got it, new HttpClient not available under netstandard2.1, only available when using net core app 3.x.
