### ISSUE TITLE
Windows service start error 1053 : The service did not respond to the start or control request in timely fashion while starting simple worker service template

### ISSUE THREAD

**Issue by cahitbeyaz** [aspnet/Extensions#2496]
### Describe the bug
Problem occurs after publishing  and creating simple worker service template. Windows service gives Error 1053 : The service did not respond to the start or control request in timely fashion when starting service. 
Problem occurs only if publishing with target WinX86,WinX64 modes. Problem does no occur if publishing made using Portable mode.
I have not tried with linux deamons

### To Reproduce
1. Using simple worker service template for .net core 3.0.0
2. It also occurs after adding Microsoft.Extensions.Hosting.WindowsServices:3.0.0
3. Publish using  target mode either winx64 or winx86
4. register service using sc create command. For instance 
sc.exe create WorkerService3 binPath=C:\Users\cahit.beyaz\source\repos\WorkerService1\WorkerService1\bin\Release\netcoreapp3.0\publish\WorkerService1.exe

### Expected behavior
Windows service should start service normally for both targetruntime portable, x86,x64 when using simple Worker Service Template

### Screenshots
![image](https://user-images.githubusercontent.com/4445261/66656803-5be3ce00-ec47-11e9-984b-385a5d7baeda.png)

### Additional context
Include the output of `dotnet --info`

C:\Users\cahit.beyaz>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  2.2.301 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by Tratcher** [comment]
Is there a crash log in event viewer? If not, please turn on application logging and see what the application is doing.

**Comment by gerardo-lijs** [comment]
I'm getting exactly the same using the dotnet new worker template. Also tried creating a project from scratch and the same. Extensions.Hosting preview v3.1.0-preview1.19506.1 same error 1053.

**Comment by cahitbeyaz** [comment]
@gerardo-lijs adding 
<PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="3.0.0" />
package 

and changing host builder as 
`  public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureLogging((hostingContext,config) =>
                {
                    config.AddLog4Net();
                    
                })
                .UseWindowsService()
                .ConfigureServices((hostContext, services) =>
                {
                    services.AddHostedService<Worker>();
                });`

solves the issue. We can close the issue. I will after you verify.

**Comment by gerardo-lijs** [comment]
Thanks!! Sorry for the delay, I just got two minutes to test this. Your solution works perfectly.

Just need to add Microsoft.Extensions.Hosting.WindowsServices package and add .UseWindowsService()  in my case, not using Log4Net.

Would be great if they modify the dotnet new worker  template to include this reference and the .UseWindowsService. I imagine they left it out because of running this in a linux probably. But at least add some comment lines or something so you can pick which platform you are using.

**Comment by Tratcher** [comment]
@gerardo-lijs the biggest catch is that it requires an extra package dependency.

**Comment by cahitbeyaz** [comment]
@gerardo-lijs happy seeing things work
