### ISSUE TITLE
Build Failed Extensions from Source !

### ISSUE THREAD

**Issue by taomylife521** [aspnet/Extensions#2502]
### Describe the bug
Build Failed Extensions from Source !

### Screenshots
![image](https://user-images.githubusercontent.com/9649318/66696602-0fa89480-ed00-11e9-805a-ce53c7817419.png)
![image](https://user-images.githubusercontent.com/9649318/66696606-1a632980-ed00-11e9-844b-e3c50026c8e5.png)
![image](https://user-images.githubusercontent.com/9649318/66696610-2222ce00-ed00-11e9-8174-6a3f348ab078.png)
![image](https://user-images.githubusercontent.com/9649318/66696622-2c44cc80-ed00-11e9-9e4a-7fe655967eb8.png)
![image](https://user-images.githubusercontent.com/9649318/66696626-336bda80-ed00-11e9-9fc3-739d59c9a926.png)

######################Build Log Start###########################

[buildlog.txt](https://github.com/aspnet/Extensions/files/3720286/buildlog.txt)

######################Build Log ENDStart###########################

### Additional context
Include the output of `dotnet --info`
![image](https://user-images.githubusercontent.com/9649318/66696648-644c0f80-ed00-11e9-9c0f-0c8fac64255f.png)

**Comment by brandondahler** [comment]
Try running `restore.cmd` then try `build.cmd` again and see if you get the same error. 

Generally you should run restore.cmd any time you pull an updated master in case the sdk reference has updated — this project generally uses the latest preview release available (or newer technically).

**Comment by pranavkm** [comment]
@taomylife521 the package that it's failing to restore is available on NuGet.org: https://www.nuget.org/packages/Microsoft.SourceLink.GitHub/1.0.0-beta2-19367-01. Generally running `build[cmd|sh]` should resolve it correctly, however it might fail if you have the NuGet.org feed disabled. If you continue seeing this error with the restore, I'll recommend filing an issue in  https://github.com/nuget/home/issues
