### ISSUE TITLE
Microsoft.Extensions.Http.Polly 3.0.0 breaks Function App binding.

### ISSUE THREAD

**Issue by Merurino** [aspnet/Extensions#2505]
### Describe the bug
If I install the package Microsoft.Extensions.Http.Polly 3.0.0 in my Function app (or if it is installed in any other referenced project) the ILogger binding stops working. Version 2.2.0 works fine though.

### To Reproduce
1. Using Vs 2019 create a new function app project using the template.
2. Add a TimerTrigger:
```
    public static class Function1
    {
        [FunctionName("Function1")]
        public static void Run([TimerTrigger("0 */5 * * * *")]TimerInfo myTimer, ILogger log)
        {
            log.LogInformation($"C# Timer trigger function executed at: {DateTime.Now}");
        }
    }
```
3. Add the `Microsoft.Extensions.Http.Polly:3.0.0` Nuget package.
4. Try to run it.

You'll get this error:
```
Error indexing method 'Function1'
Microsoft.Azure.WebJobs.Host: Error indexing method 'Function1'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'log' to type ILogger. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
```

### Expected behavior
For the binding to happen.

### Screenshots
This is the differences between v2.2.0 and V3.0.0, I believe one of these dependencies is what is actually breaking it.
![image](https://user-images.githubusercontent.com/11574755/66731325-8e3d3780-eea2-11e9-9c4d-77f85c5f154a.png)

### Additional context
```
Azure Functions Core Tools (2.7.1704 Commit hash: fbab3b9c1de5ab95e3b4b6a471ead62c4f37e89c)
Function Runtime Version: 2.0.12742.0
```

**Comment by davidfowl** [comment]
File this on https://github.com/Azure/azure-functions-host

**Comment by Merurino** [comment]
Will do. Thanks
