### ISSUE TITLE
Why are some extensions under ASPNET whene they dont need to be?

### ISSUE THREAD

**Issue by mgwalm** [aspnet/Extensions#2546]
Eg, Microsoft.Extensions.Configuration, DependencyInjection, Logging, etc need to be used by all project types, not just ASPNET.

**Comment by khellang** [comment]
These will be moved under the new `dotnet/runtime` monorepo. See [this announcement](https://github.com/dotnet/coreclr/issues/27096).

**Comment by mgwalm** [comment]
ok, thanks

**Comment by Pilchie** [comment]
Closing as answered.
