### ISSUE TITLE
Switch to label.N form for pre-release label

### ISSUE THREAD

**Issue by mmitche** [aspnet/Extensions#2560]
In order to facilitate better preview sorting, switch to label.N form for the pre-release label.

Requires a recent version of arcade, so filing an issue rather than opening a PR. See dotnet/windowsdesktop#104 for an example of how this is done.

**Comment by mmitche** [comment]
Requires: https://github.com/aspnet/AspNetCore-Tooling/pull/1258

**Comment by wtgodbe** [comment]
https://github.com/aspnet/Extensions/pull/2786
