### ISSUE TITLE
Socket errors in a reverse proxy

### ISSUE THREAD

**Issue by colutti** [aspnet/Extensions#2573]
We have developed a reverse proxy to send requests to different endpoints. It has been working so far, but we see a lot of socket errors with timeout exceptions. We are using a singleton instance of httpclient but the issue still happens. 

The code with the repro steps can be found here:

https://github.com/colutti/tr-reverse-proxy

**Comment by Pilchie** [comment]
@rynowak ?

**Comment by Pilchie** [comment]
@rynowak told me this isn't  client factory, it repros with just `httpclient`.  Moving to Corefx.

**Comment by Pilchie** [comment]
This issue was moved to dotnet/corefx#42275
