### ISSUE TITLE
Resolving singleton dependencies with multi-thread cause a deadlock.

### ISSUE THREAD

**Issue by mayuki** [aspnet/Extensions#2588]
### Question
When I try to resolve Singleton `A` and also resolve Singleton `B` while building an instance of `A`, it causes a deadlock. Is this behavior by design?

By the way, I found the comment "fork resolution process on another thread" in [CallSiteRuntimeResolver.cs](https://github.com/aspnet/Extensions/blob/fc2a7eadfedd88f951eaecd45ecac6989b0f897f/src/DependencyInjection/DI/src/ServiceLookup/CallSiteRuntimeResolver.cs#L76-L83). What do you expect the scenario for that? 

### To Reproduce
```csharp
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;

namespace ConsoleApp16
{
    class Program
    {
        static void Main(string[] args)
        {
            var services = new ServiceCollection();
            services.AddSingleton<A>(sp =>
            {
                Task.Run(() => sp.GetService<B>()).GetAwaiter().GetResult(); // <-- deadlock
                return new A();
            });
            services.AddSingleton<B>();

            var serviceProvider = services.BuildServiceProvider();
            serviceProvider.GetService<A>();
        }
    }

    class A { }
    class B { }
}
```

### Screenshots
![image](https://user-images.githubusercontent.com/9012/67998107-7b947200-fc9a-11e9-9608-86d238923b2a.png)

**Comment by davidfowl** [comment]
Yes it does result in a dead lock. This is one of those gotchas and we don't have any plans to fix it.

**Comment by mayuki** [comment]
OK, I will change the application code. Thank you.
