### ISSUE TITLE
UseConsoleLifetime collides with UseWindowsService - it cannot start properly as NT Service

### ISSUE THREAD

**Issue by JiriZidek** [aspnet/Extensions#2673]
### Description
When UseConsoleLifetime and UseWindowsService are used together (in app that is supposed to run both as NT Service and as console), then the app is unable to start as NT Service - it always failes on timeout (Service failed to respond to start command in timely manner. Error 1053)

### Repro steps
1. Using version 3.0.100 .NET Core + Microsoft.Extensions.Hosting.WindowsServices 3.0.0
2. Create the very default "Worker" project (the one that makes 1 second outputs to logger)
3. In Program.CreateHostBuilder make use of both 

``` C#
public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
            .UseWindowsService()
            .UseConsoleLifetime()
                .ConfigureServices((hostContext, services) => {
                    services.AddHostedService<Worker>();
                });
```

4. Compile, register as service, e.g. 
`sc create WP binPath="C:\Users\USER\OneDrive\Dokumenty\Visual Studio 2019\Projects\WorkerService2\bin\Debug\netcoreapp3.0\WorkerService2.exe"`
5. Open Service manager in Windows, find the service, press Start button - Error 1053 (see snapshot below)
6. Remove `.UseConsoleLifetime()` call, recompile, try again - NT Service Starts/Stops well

### Expected behavior
The UseConsoleLifetime() should detect if the running environment is really a console, or at least that UseWindowsService() has not seized yet the services (since it has proper detection - but then the order of invocation would play role).

### Prinscreen
Starting NT Service failure:
![image](https://user-images.githubusercontent.com/8578952/68984930-47c95880-0813-11ea-93c2-0f4b1db71a23.png)

### Additional context
I guess that the same collision would be with UseSystemd()

**Comment by JiriZidek** [comment]
My mitigation...
``` C#
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Hosting.WindowsServices;
using Microsoft.Extensions.Hosting.Systemd;

namespace Worker
{
    public static class HostingHostBuilderExtensions
    {
        public static IHostBuilder UseConsoleLifetimeWithCkeck(this IHostBuilder hostBuilder) {
            if(!WindowsServiceHelpers.IsWindowsService() && !SystemdHelpers.IsSystemdService()) {
                hostBuilder.UseConsoleLifetime();
            }
            return hostBuilder;
        }

    }
}
```

**Comment by Tratcher** [comment]
Mitigation: the call to UseConsoleLifetime is never needed, console lifetime is always the default. I don't remember why we even shipped UseConsoleLifetime.

UseWindowsService has the correct light up detection to only add itself when running in a service.

**Comment by JiriZidek** [comment]
Right. Works.
