### ISSUE TITLE
IHostApplicationLifetime not notified of shutdown

### ISSUE THREAD

**Issue by peval27** [aspnet/Extensions#2699]
### Describe the bug
When running the application as a Windows Service, if I shutdown the PC, the app is not notified of the shutdown or of the stop. IHostApplicationLifetime.ApplicationStopping or ApplicationStopped are not fired (and it's where I log about app stopping/stopped)

### To Reproduce
1. Using version '3.0.1' of package 'Microsoft.Extensions.Hosting.WindowsServices'
2. Create a Windows Service following instructions [here ](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-3.0&tabs=visual-studio). In particular make sure you call .UseWindowsService

### Expected behavior
App notified of system shutdown, so it can stop in a graceful manner.

**Comment by peval27** [comment]
I had a look at the source code and it looks like WindowsServiceLifetime.cs doesn't override OnShutdown

**Comment by peval27** [comment]
I can confirm the bug, since I've downloaded the source code and added 
```
protected override void OnShutdown()
{
     ApplicationLifetime.StopApplication();
     base.OnShutdown();                
}
```

and the app is now notified as expected during machine shutdown/restart.

**Comment by anurse** [comment]
@peval27 that code seems good to us. Would be you up for turning it in to a PR?

**Comment by Tratcher** [comment]
From the docs it sounds like you'd have to set CanShutdown as well?
https://docs.microsoft.com/en-us/dotnet/api/system.serviceprocess.servicebase.onshutdown?redirectedfrom=MSDN&view=netcore-3.0#System_ServiceProcess_ServiceBase_OnShutdown

**Comment by peval27** [comment]
> 
> 
> From the docs it sounds like you'd have to set CanShutdown as well?
> https://docs.microsoft.com/en-us/dotnet/api/system.serviceprocess.servicebase.onshutdown?redirectedfrom=MSDN&view=netcore-3.0#System_ServiceProcess_ServiceBase_OnShutdown

not sure why it's being called then. happy to add to the constructor.

**Comment by peval27** [comment]
> 
> 
> @peval27 that code seems good to us. Would be you up for turning it in to a PR?

will give it a go!
