### ISSUE TITLE
Configuring HttpClient from HttpClientFactory

### ISSUE THREAD

**Issue by msft-mw** [aspnet/Extensions#2722]
I'm looking into moving some of my team's code from framework to core, and one of the things that I'm looking at is the `HttpClientFactory`. I think I have a handle on how to use it for typed clients, but I had a question about how to properly use it.

In this example:

```csharp
serviceCollection.AddHttpClient<IClient, Client>((services, client) => 
{
    // do some heavy stuff here
});
```
I noticed that the "heavy stuff" gets hit every time a client is resolved (so per controller instantiation) for this web api). Is there a way to "re-use" the heavy stuff so I don't hit that every time a client gets injected?

**Comment by rynowak** [comment]
There's a few different patterns for the "heavy stuff" - which one I'd recommend will depend on what you're trying to do. Care to elaborate and I can make some suggestions?

**Comment by msft-mw** [comment]
Sure! One example is we make an off-box call to a token server with a certificate and some other collateral to get an encrypted json web token which we then attach as an authorization header. Actually speaking of, I don't even know if the "heavy stuff" can be async at all.

**Comment by rynowak** [comment]
So if you need to make a call to a token server (or do anything else async), I'd recommend writing a `DelegatingHandler` and wiring that up with `AddMessageHandler<>`.

That will be cached across the times you resolve an `HttpClient` instance. 

Depending on the specifics of what you're doing there might already be some handler implementations out there that do what you want.

**Comment by msft-mw** [comment]
Thanks @rynowak! I'll give that a shot next week. My current solution was to inject a helper class from the DI container which was long-lived and had the token cached, but I think I like this better :)
