### ISSUE TITLE
Dispose `_stoppingCts` in BackgroundService.cs?

### ISSUE THREAD

**Issue by nopara73** [aspnet/Extensions#2725]
https://github.com/aspnet/Extensions/blob/master/src/Hosting/Abstractions/src/BackgroundService.cs#L70

Is there a reason why `_stoppingCts` is not disposed?

**Comment by Tratcher** [comment]
Disposing a token source is dangerous if there's any possibility that it's still in use, it could cause ObjectDisposedExceptions.

A cancelled token source doesn't really need to be disposed, Cancel did all of the same cleanup.
