### ISSUE TITLE
User secrets are not loaded into IConfiguration in a worker service on .NET Core 3.1

### ISSUE THREAD

**Issue by sethjackson** [aspnet/Extensions#2743]
### Describe the bug

In a .NET Core 3.1 worker service user secrets are no longer load from `IConfiguration`.

Downgrading to `netcoreapp3.0` and running with the .NET Core 3.0 SDK brings back the expected behavior.

The user secrets are successfully loaded on `netcoreapp3.1` in an ASP.NET Core project just not in a worker service.

### To Reproduce

1. `dotnet new worker`
4. `dotnet user-secrets set Test:Item Example`
5. Add `_logger.LogInformation("{Item}", configuration["Test:Item"]);` to the `Worker` class as shown below
6. `dotnet run`

```csharp
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

public class Worker : BackgroundService
{
    private readonly ILogger<Worker> _logger;

    public Worker(ILogger<Worker> logger, IConfiguration configuration)
    {
        _logger = logger;
        _logger.LogInformation("{Item}", configuration["Test:Item"]);
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        while (!stoppingToken.IsCancellationRequested)
        {
            _logger.LogInformation("Worker running at: {time}", DateTimeOffset.Now);
            await Task.Delay(1000, stoppingToken);
        }
    }
}
```

### Expected behavior

The user secrets should be available from `IConfiguration`.

### Additional context

`dotnet --info`

```console
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\<snipped>

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db
```

**Comment by sethjackson** [comment]
I've been investigating this a bit more.

In [UserSecretsConfigurationExtensions](https://github.com/aspnet/Extensions/blob/release/3.1/src/Configuration/Config.UserSecrets/src/UserSecretsConfigurationExtensions.cs#L131) the user secrets ID gets loaded from the assembly.

I added this to `ConfigureServices`:

```csharp
var env = hostContext.HostingEnvironment;
var assembly = Assembly.Load(new AssemblyName(env.ApplicationName));
                    
if (assembly != null)
{
    Console.WriteLine(assembly);
                        
    var attribute = assembly.GetCustomAttribute<UserSecretsIdAttribute>();
                    
    if (attribute != null)
    {
        Console.WriteLine(attribute.UserSecretsId);
    }
}
```

With the .NET 3.0 SDK this outputs the ID with the .NET 3.1 SDK it does not.

Digging further it turns out that the `UserSecretsIdAttribute` does not exist in `AssemblyInfo.cs` with the .NET 3.1 SDK.

With the .NET 3.0 SDK the attribute exists in `AssemblyInfo.cs`:

```
[assembly: Microsoft.Extensions.Configuration.UserSecrets.UserSecretsIdAttribute("dotnet-test-E8F6F7FB-5F63-43EB-A338-41EC275E5892")]
```

**Comment by Tratcher** [comment]
@anurse was anybody working on the Worker SDK or UserSecrets in 3.1? I'm not aware of any changes here. Regardless this looks like a regression.

**Comment by anurse** [comment]
There was a change to user secrets in the .NET SDK: https://github.com/dotnet/sdk/pull/3673

@sethjackson can you post your full `csproj` file?

I think this is an issue that comes up when you transitively reference `Microsoft.Extensions.Configuration.UserSecrets` but **not** via the ASP.NET Core framework. @sethjackson does it work if you directly reference this package (if you aren't already)?

**Comment by anurse** [comment]
cc @dsplaisted who may have context on the original change

**Comment by sethjackson** [comment]
If I add a package reference to `Microsoft.Extensions.Configuration.UserSecrets` then the secrets get loaded.

However out of the box the `csproj` generated via `dotnet new worker` does not include `Microsoft.Extensions.Configuration.UserSecrets` in 3.0 or 3.1 so this appears to be a regression to me.

Here is my `csproj`:

```xml
<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UserSecretsId>dotnet-test-E8F6F7FB-5F63-43EB-A338-41EC275E5892</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="3.1.0" />
  </ItemGroup>
</Project>

```

**Comment by anurse** [comment]
Ok yeah, I think I see the problem then. [Right now, the user secrets injection only appears to work when you directly reference either `Microsoft.Extensions.Configuration.UserSecrets` or `Microsoft.AspNetCore.App` (in a Web app)](https://github.com/dotnet/sdk/blob/f98197d56b051f8c5078e9017de1ef7046125205/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets#L359). It doesn't seem to support transitive reference.

Today, the best workaround will be adding the direct reference. Since it already comes transitively through `Microsoft.Extensions.Hosting` you don't get any other code, it just fixes the incorrect detection.

I'll file an issue on dotnet/sdk to look at solving the underlying problem (which is in that logic).

**Comment by sethjackson** [comment]
Ok thanks!

**Comment by anurse** [comment]
Filed https://github.com/dotnet/sdk/issues/4007
