### ISSUE TITLE
Policy Injection for HttpClientFactory?

### ISSUE THREAD

**Issue by kayhustle** [aspnet/Extensions#2745]
Is there any way to add OnRequest and OnResponse handlers to the HttpClientFactory?

**Comment by rynowak** [comment]
Can you be more specific? I don't know what those terms refer to.... have a link?

**Comment by kayhustle** [comment]
FlurlHttp has a feature where you can attach delegates to be invoked before a request and after a request.
```
  FlurlHttp.Configure(async i =>
            {
                 i.BeforeCallAsync = httpcall=> Task.Factory.StartNew(()=>Console.WriteLine("Before request"));
                i.AfterCallAsync = httpcall => Task.Factory.StartNew(() => Console.WriteLine("After response"));
            });
```
This makes it easy to inject policies.  I guess I could imitate something like this by creating a DelegatingHandler that allows me to attach delegates to it.  Which was answered in my other question.
