### ISSUE TITLE
Har Logging for HttpClientFactory

### ISSUE THREAD

**Issue by kayhustle** [aspnet/Extensions#2746]
Is there any way to log the HttpClientFactory requests and responses to the Har format for viewing in Fiddler logs?

**Comment by rynowak** [comment]
We don't provide a feature like this in the box. I'd suggest writing a `DelegatingHandler` and using `AddMessageHandler<T>` to wire it up.

**Comment by kayhustle** [comment]
FlurlHttp has a feature where you can attach delegates to be invoked before a request and after a request.
```
  FlurlHttp.Configure(async i =>
            {
                 i.BeforeCallAsync = httpcall=> Task.Factory.StartNew(()=>Console.WriteLine("Before request"));
                i.AfterCallAsync = httpcall => Task.Factory.StartNew(() => Console.WriteLine("After response"));
            });
```
This makes it easy to inject policies.  I guess I could mock something like this by creating a DelegatingHandler that allows me to attach delegates to it.  Which was answered in my other question.

**Comment by kayhustle** [comment]
Thanks
