### ISSUE TITLE
Named parameters in logger message template not working correctly

### ISSUE THREAD

**Issue by mikernet** [aspnet/Extensions#2757]
I don't know if this is a library bug or a documentation mistake. The docs in the [Log Message Template](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#log-message-template) section indicate that you can pass in parameters out of order and it will still output them in the correct order based on the names in the string template and the passed in variables. I've been scouring the source code to figure out how the heck you managed to make that work given that the parameters are passed in via an `object[]` array as I was interested in utilizing similar behavior if this was possible but I can't find anything to indicate that's what is happening. I then tried to run the sample code in the docs that supposedly demonstrates this capability and it outputs the parameters in the wrong order.

### To Reproduce
1. Using version 3.1.0 of packages Microsoft.Extensions.Logging/Abstractions/Debug
2. Run this code:

```c#
var loggerFactory = LoggerFactory.Create(builder =>
    builder.AddDebug());

var logger = loggerFactory.CreateLogger<Program>();
string p1 = "parm1";
int p2 = 2;
logger.LogInformation("Parameter values: p2: {p2}, p1: {p1}", p1, p2);
```
3. See output:
```
Information: Parameter values: p2: parm1, p1: 2
```

I thought that maybe the sample code had a mistake and it should have been like this, which would make more sense as to how it worked:
```c#
logger.LogInformation("Parameter values: p2: {p2}, p1: {p1}", new { p1, p2 });
```
But alas that throws an exception.

### Expected behavior
Output should be:
```
Information: Parameter values: p2: 2, p1: parm1
```

**Comment by Kahbazi** [comment]
Hi @mikernet. The document actually states that the names of placeholders has nothing to do with values.

> The order of placeholders, _not their names_, determines which parameters are used to provide their values.

**Comment by mikernet** [comment]
Oh boy, I read that wrong...my bad :)
