### ISSUE TITLE
UseSystemd for IWebHostBuilder

### ISSUE THREAD

**Issue by eitanhs** [aspnet/Extensions#2773]
I'm am trying to register my web application as systemd service.
There's an extension method for `IHostBuilder` called `UseSystemd` that does that, but unfortunately there's no implementation for `IWebHostBuilder`.

If possible, please add an extension method to `IWebHostBuilder` that provides the same behavior.

Currently I copied the body of the extension method from: https://github.com/aspnet/Extensions/blob/89b048b5de1cf54a89c35e3a32da49833c56a2a6/src/Hosting/Systemd/src/SystemdHostBuilderExtensions.cs#L32 and it might be working (It's hard for me to test so I'm not sure yet)

**Comment by Tratcher** [comment]
IWebHostBuilder is replaced by IHostBuilder, we're no longer adding new features to IWebHostBuilder.

Is there a reason you can't use IHostBuilder?

**Comment by eitanhs** [comment]
I wasn't aware of that. Thanks for the feedback. Closing issue..
