### ISSUE TITLE
AspNetCore 3.1 Dependency Injection

### ISSUE THREAD

**Issue by okanlodos** [aspnet/Extensions#2800]
AspNetCore 3.1 DependencyInjection

I register a service and I delete it then register a new service

`

            services.AddDbContext<IDbContext, DbContext>(options =>
                options.UseSqlServer(
                    configuration.GetConnectionString("DefaultConnection"),
                    b => b.MigrationsAssembly(typeof(DbContext).Assembly.FullName)));

            var serviceDesc = services.FirstOrDefault(x=> x.ServiceType == typeof(IDbContext));
            services.Remove(serviceDesc);

            services.AddDbContext<IDbContext, DbContext>(options =>
                    {
                        options.UseInMemoryDatabase("InMemoryDbForTesting");
                        options.UseInternalServiceProvider(serviceProvider);
                    });

            var sp = services.BuildServiceProvider();
            using var scope = sp.CreateScope();
            var scopedServices = scope.ServiceProvider;
            var context = scopedServices.GetRequiredService<IDbContext>();
            Console.WriteLine(context.Database.IsInMemory());`

Output: false

Expected Output: true

Is this a bug?

**Comment by davidfowl** [comment]
Unlikey, you need to look at the implementation of `AddDbContext` and remove all of the relevant services. It's likely removing the IDbContext isn't enough

**Comment by okanlodos** [comment]
@davidfowl thank you for answer. I've solved this thread by change the ServiceType.
`                    var serviceDesc = services.FirstOrDefault(x => x.ServiceType ==    typeof(DbContextOptions<DbContext>));
`
