### ISSUE TITLE
BackgroundService should provide a linked token to ExecuteAsync

### ISSUE THREAD

**Issue by klettier** [aspnet/Extensions#2811]
# Describe the bug

To allow cancellation occurring on start to flow through [ExecuteAsync](https://github.com/aspnet/Extensions/blob/master/src/Hosting/Abstractions/src/BackgroundService.cs#L33), ```BackgroundService``` should provide a linked token to ```ExecuteAsync```

### To Reproduce
1. Put ```await Task.Delay(Timeout.Infinite, stoppingToken);``` inside ```ExecuteAsync```
2. Do ```Ctrl+C```
3. App will wait indefinitely

### Expected behavior

* Cancel occurred

### Solution

```csharp
_stoppingCts  = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
_executingTask = ExecuteAsync(_stoppingCts.Token);
```

I can do a PR if needed

**Comment by Tratcher** [comment]
That doesn't work, you wouldn't be able to unlink the tokens once StartAsync finished.

**Comment by klettier** [comment]
> That doesn't work, you wouldn't be able to unlink the tokens once StartAsync finished.

* Why do we need to unlink it ?
* Is there something that will cancel the token provided to StartAsync ? 
  * why ?

**Comment by klettier** [comment]
As I can see in the [host](https://github.com/aspnet/Extensions/blob/ecc4d9fe9381ac65848968b672eb6098ec2a2cae/src/Hosting/Hosting/src/Internal/Host.cs#L50) there seems to have no issue to link the token to the one in ```BackgroundService```.

Even **disposing the token** will not cancel the linked one.

@Tratcher Any case in mind where the ```StartAsync``` token would be wrongly cancelled ?

**Comment by anurse** [comment]
Triage: This does make some sense, we should tie the tokens together. Would definitely review an external PR for this!
