### ISSUE TITLE
How to release the objects inside the defaultobjectpool?

### ISSUE THREAD

**Issue by 1448376744** [aspnet/Extensions#2821]
``` C#
var policy = new MyPolicy();
var pool = new DefaultObjectPool<Connection>(policy,2);
var connection1 =  pool.Get();
var connection2 = pool.Get();
var connection3 = pool.Get();
pool.Return(connection1);
var connection4 = pool.Get();
```
The overflowing connections are not released

**Comment by 1448376744** [comment]
This code does not release the elements removed from the array
``` C#
//DisposableObjectPool.cs
 private bool ReturnCore(T obj)
 {
     bool returnedTooPool = false;

     if (_isDefaultPolicy || (_fastPolicy?.Return(obj) ?? _policy.Return(obj)))
     {
         if (_firstItem == null && Interlocked.CompareExchange(ref _firstItem, obj, null) == null)
         {
             returnedTooPool = true;
         }
         else
         {
             var items = _items;
             for (var i = 0; i < items.Length && !(returnedTooPool = Interlocked.CompareExchange(ref items[i].Element, obj, null) == null); i++)
             {
             }
         }
     }

     return returnedTooPool;
 }

````

**Comment by gfoidl** [comment]
You create the object-pool with `var pool = new DefaultObjectPool<Connection>(policy,2);` directly.
It's better to use 
```c#
var poolProvider = new DefaultObjectPoolProvider { MaximumRetained = 2 };
var pool = poolProvider.Create<Connection>(policy);
```
as this checks if `Connection` is an `IDisposable` (see [code here](https://github.com/aspnet/Extensions/blob/582427c350fe8842553a8c33b4015662f95c1c78/src/ObjectPool/src/DefaultObjectPoolProvider.cs#L26-L29)) and then uses the correct pool-implementation.

Even better would be to use ASP.NET Core DI facilities.

**Comment by 1448376744** [comment]
> 您`var pool = new DefaultObjectPool<Connection>(policy,2);`直接使用创建对象池。
> 最好用
> 
> ```cs
> var  poolProvider  =  new  DefaultObjectPoolProvider { MaximumRetained  =  2 };
> var  pool  =  poolProvider。创建 < 连接 >（策略）;
> ```
> 
> 因为这会检查if `Connection`是否为`IDisposable`（请参阅[此处的代码](https://github.com/aspnet/Extensions/blob/582427c350fe8842553a8c33b4015662f95c1c78/src/ObjectPool/src/DefaultObjectPoolProvider.cs#L26-L29)），然后使用正确的池实现。
> 
> 更好的办法是使用ASP.NET Core DI工具。
What about the overflowing objects? I have seen the source code. Even if maximumretained = 2 is set, it will overflow, resulting in memory leakage

**Comment by 1448376744** [comment]
However, I have written a new version with reference to the source code. If the maximum retained value is exceeded, object pool will wait for the return of the object

**Comment by gfoidl** [comment]
What's in your `MyPolicy`-class? This one is responsible for `Create` and `Return`. The pool ifself just delegates to the policy.

Also in you initial example (first comment here) you are just returning one item, so this one will get to the pool and there is no reason to release / dispose it.

Look at the following example, and you'll see that `connection2` gets disposed.

<details>
  <summary>Example with dispose</summary>

```c#
using System;
using Microsoft.Extensions.ObjectPool;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var poolProvider = new DefaultObjectPoolProvider { MaximumRetained = 2 };
            ObjectPool<Connection> pool = poolProvider.Create<Connection>();

            var connection0 = pool.Get();
            var connection1 = pool.Get();
            var connection2 = pool.Get();
            pool.Return(connection0);
            pool.Return(connection1);
            pool.Return(connection2);
            var connection3 = pool.Get();
        }
    }

    public class Connection : IDisposable
    {
        private static int s_instanceId = 0;

        public int InstanceId { get; } = s_instanceId++;

        public Connection()
        {
            Console.WriteLine($"Instance {this.InstanceId} created");
        }

        public void Dispose()
        {
            Console.WriteLine($"Instance {this.InstanceId} disposed");
        }
    }
}
```
</details>

**Comment by gfoidl** [comment]
> object pool will wait for the return of the object

Why should it need to wait? That's counterproductive. 
If the pool is full and one item gets returned, so it should / can be released -- and in case of the disposable-pool disposed.
Same thing the other way round: if the pool is empty and one item `Get`, then an item has to be created.
With `MaximumRetained` on the provider you can tweak this to your needs.

> I suggest that the next version can add the objectpool that cannot overflow.

I can't follow. Can you eloberate this suggestion?

**Comment by 1448376744** [comment]
Yes, I read the source code yesterday. Open source is so exciting. It's hard for me to decide whether the object pool should control the maximum number of TCP connection objects (limited resources). The current version is handled like overflow, which means lost connections and uncontrolled growth.

**Comment by 1448376744** [comment]
> > 对象池将等待对象的返回
> 
> 为什么需要等待？这适得其反。
> 如果水池已满，并且有一件物品退回，那么应该/可以放开-如果处置了一次性水池。
> 反之亦然：如果池为空且有一个item `Get`，则必须创建一个item。
> 随着`MaximumRetained`对供应商，你可以调整这个您的需求。
> 
> > 我建议下一个版本可以添加不会溢出的对象池。
> 
> 我听不懂 你能大声说出这个建议吗？

The current version assumes "maximum retained = 2" and the container will still create a fourth or more

**Comment by 1448376744** [comment]
``` C#
namespace Microsoft.Extensions.ObjectPool
{
    public class ObjectPool<T> : IObjectPool<T>, IDisposable where T : class
    {
        private protected readonly T[] _items = null;
        private protected T _firstItem = null;
        //Cumulative number of elements
        private protected long _itemtotal = 0;
        private protected int _timeout = 0;
        private protected readonly IPooledObjectPolicy<T> _policy = null;
        public ObjectPool(IPooledObjectPolicy<T> policy)
            : this(policy, Environment.ProcessorCount * 2)
        {

        }
        public ObjectPool(IPooledObjectPolicy<T> policy, int maximumRetained, int timeout = 180_000)
        {
            _policy = policy;
            _items = new T[maximumRetained - 1];
            _timeout = timeout;
        }
        public T Get()
        {
            var item = _firstItem;
            if (item == null || Interlocked.CompareExchange(ref _firstItem, null, item) != item)
            {
                var items = _items;
                for (var i = 0; i < items.Length; i++)
                {
                    item = items[i];
                    if (item != null && Interlocked.CompareExchange(ref items[i], null, item) == item)
                    {
                        return item;
                    }
                }
                if (_itemtotal <= _items.Length && Interlocked.Increment(ref _itemtotal) <= _items.Length + 1)
                {
                    item = Create();
                }
                else
                {
                    var task = Task.Run(() =>
                    {
                        while (true)
                        {
                            //Overflow waiting
                            item = _firstItem;
                            if (Interlocked.CompareExchange(ref _firstItem, null, item) == item)
                            {
                                break;
                            }
                        }
                        return item;
                    });

                    if (!task.Wait(_timeout))
                    {
                        throw new TimeoutException($"Timeout in getting {typeof(T).Name} instance, please expand the capacity appropriately");
                    }
                    return task.Result;
                }
            }
            return item;
        }
    
        private T Create()
        {
            return _policy.Create();
        }
      
        public void Return(T obj)
        {
            if (_policy.Return(obj))
            {
                if (_firstItem != null || Interlocked.CompareExchange(ref _firstItem, obj, null) != null)
                {
                    var items = _items;
                    for (var i = 0; i < items.Length && Interlocked.CompareExchange(ref items[i], obj, null) != null; ++i)
                    {

                    }
                }
            }
        }
      
        public void Dispose()
        {
            if (typeof(IDisposable).IsAssignableFrom(typeof(T)))
            {
                (_firstItem as IDisposable)?.Dispose();
                foreach (var item in _items)
                {
                    (item as IDisposable)?.Dispose();
                }
            }
        }
    }
}
```

**Comment by 1448376744** [comment]
> > 对象池将等待对象的返回
> 
> 为什么需要等待？这适得其反。
> 如果水池已满，并且有一件物品退回，那么应该/可以放开-如果处置了一次性水池。
> 反之亦然：如果池为空且有一个item `Get`，则必须创建一个item。
> 随着`MaximumRetained`对供应商，你可以调整这个您的需求。
> 
> > 我建议下一个版本可以添加不会溢出的对象池。
> 
> 我听不懂 你能大声说出这个建议吗？

I wonder if I need to wait. I think you thought about it when you started designing. I mainly consider that when the objects are not returned for a long time, the container will create new objects uncontrollably

**Comment by gfoidl** [comment]
`MaximumRetained` defines the pool-size, so what is wrong with 

> The current version assumes "maximum retained = 2" and the container will still create a fourth or more

? It the expected (default) behavior of object-pools.
When you return all four object, two of the will be kept in the pool, the other two will be released.

Please don't put this code into the `Microsoft.Extensions.ObjectPool`-namespace, as it's -- sorry to say -- a mess. `Task.Run` and blocking via `Wait` shouldn't (never ever) be in the pool. It is not the responsibility of the pool, and it breaks all performance measures.

It would be easier if you define your goal and state this, then we can see to find a solution therefore.
Is it something like this:
"I want the object pool to create a maximum of `MaximumRetained` items and no more. Then it should return `null`, throw an expection whatever."

> I'm also thinking about whether I need to wait.

You should not wait. Design the rest of you application that way that there is no need to wait (synchronosly).

> I mainly consider that when the objects are not returned for a long time, the container will create new objects uncontrollably

That's how pools work in general. When no objects are returned, so the pool acts as a factory.
In general the intended use case for pools is rent and almost immediate return. It is not designed / intended for long-term rent. In such case just use a factory or create the object directly.

---

PS: please keep in mind that englisch is used here :wink:

**Comment by 1448376744** [comment]
If i control the wait, will have new problems, such as timeout

> `MaximumRetained` 定义了池的大小，所以什么地方出了问题
> 
> > 当前版本假定“最大保留数= 2”，并且容器仍将创建第四个或更多
> 
> ？它是对象池的预期（默认）行为。
> 当您返回所有四个对象时，其中两个将保留在池中，另外两个将被释放。
> 
> 请不要将此代码放入`Microsoft.Extensions.ObjectPool`-namespace中，因为-不好意思-乱七八糟。`Task.Run`并禁止`Wait`（永远不要）进入游泳池。这不是池的责任，它破坏了所有性能指标。
> 
> 如果您定义目标并陈述这一点会更容易，那么我们可以看到找到一个解决方案。
> 是否是这样的：
> “我希望对象池创建最多`MaximumRetained`项目，并且不再创建其他项目。然后它应该返回`null`，并抛出任何期望。”
> 
> > 我也在考虑是否需要等待。
> 
> 你不应该等待。通过这种方式设计应用程序的其余部分，而无需等待（同步）。
> 
> > 我主要考虑的是，当长时间不返回对象时，容器将无法控制地创建新对象
> 
> 这就是池通常的工作方式。当没有对象返回时，池将充当工厂。
> 通常，池的预期用例是租金和几乎立即的回报。它不是为长期出租而设计的。在这种情况下，只需使用工厂或直接创建对象即可。
> 
> PS：请记住，这里使用英语 😉

Thank you very much. I'm thinking

**Comment by 1448376744** [comment]
I didn't read this code.
It will release the overflow object.
That's enough for me,
Thank you for your answer
``` C#
public override void Return(T obj)
{
    // When the pool is disposed or the obj is not returned to the pool, dispose it
    if (_isDisposed || !ReturnCore(obj))
    {
        DisposeItem(obj);
    }
}


```

**Comment by gfoidl** [comment]
@1448376744 is this issue hereby resolved? If so, please close it.
