### ISSUE TITLE
Use new capability API to determine what ServiceProviderMode to use by default

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Extensions#422]
Use new capability API to detect if reflection or dynamic code generation should be used.

https://github.com/dotnet/corefx/issues/29258

cc: @pakrym

**Comment by muratg** [comment]
@davidfowl @pakrym CoreFX change seems done. Do we expect we'll do this in 3.0?

**Comment by pakrym** [comment]
This is quick and easy let's do it.

**Comment by davidfowl** [comment]
Yep! Once we have that change it'll be easy to add.
