### ISSUE TITLE
MinimumOSVersion attribute cannot load registry entries on Windows Server 2012 R2

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Extensions#423]
### Describe the bug
Many of our Kestrel HTTP/2 tests require >Win8.1 to run and we use the MinimumOSVersion attribute to filter for this. However, the registry keys are empty on some Windows platforms like Windows Server 2012 R2. This means some of our HTTP/2 tests are not getting the coverage we expect.

### To Reproduce
Using a small repro at https://gist.github.com/JunTaoLuo/158b1b9284daf84afbe3e8cb9988fc48, I see the results:
```
.
Microsoft Windows NT 6.2.9200.0
```
Which means the attribute would fallback to using the Environment.OSVersion that categorize the OS as Win8

### Expected behavior
Kestrel HTTP/2 tests run on Windows Server 2012

**Comment by Tratcher** [comment]
Example: 
https://github.com/aspnet/KestrelHttpServer/blob/2a610ee1b8d00eed8afe77252c966ecc1e695272/test/Kestrel.H2Spec.FunctionalTests/H2SpecTests.cs#L22
http://aspnetci/project.html?projectId=XPlat&testNameId=-8370042059100246461&tab=testDetails

It's running on Win10, but not Win8.1 or 2012R2.

**Comment by Tratcher** [comment]
Reg key fallback:
Win10: CurrentMajorVersionNumber, CurrentMinorVersionNumber
Win8.1: CurrentVersion
