### ISSUE TITLE
Unexpected registration behaviour

### ISSUE THREAD

**Issue by godrose** [aspnet/Extensions#450]
### Describe the bug
The `AddSingleton` behaves in an unexpected way when instance is supplied.

### To Reproduce
1. Using version '2.1.1' of package 'DependencyInjection'
2. Run this code 
```
            var configurationBuilder = new ConfigurationBuilder();
            configurationBuilder.AddJsonFile("LocalSettings.json");
            var configuration = configurationBuilder.Build();
            serviceCollection..AddSingleton<IConfigurationProvider>(r => new ConfigurationProvider(configuration));
//few lines later...
public class SomeService
{
public SomeService(IConfigurationProvider configurationProvider)
{
}
}
```
3. See error

### Expected behavior
Expected: `SomeService` is resolved correctly
Actual: Dependency resolution exception is thrown

**Comment by poke** [comment]
Do you get an error for `SomeService` or for `IConfigurationProvider`? If it's the former, then it's because you didn't register the service. You need to register `SomeService` as well if you want to resolve it.

**Comment by Tratcher** [comment]
What's the exception?

**Comment by pakrym** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
