### ISSUE TITLE
Properly Implement StringSegment and StringSegmentComparer GetHashCode

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Extensions#457]
_From @Tratcher on Monday, May 22, 2017 3:41:08 AM_

https://github.com/aspnet/Common/issues/213
StringSegment.GetHashCode and StringSegmentComparer.GetHashCode(StringSegment) both substring and then string.GetHashCode() which defeats the purpose of using StringSegment.

Note that .NET Core strings use randomized hash codes to mitigate issues like dictionary hash collision attacks.

The header parsers in HttpAbstractions call both of these methods the header value types GetHashCode implementations, but I'm not aware of any instances where those header value types are used as keys into hashed collections.

_Copied from original issue: aspnet/Common#232_

**Comment by rynowak** [comment]
This is no longer blocked 👍 See: https://github.com/dotnet/coreclr/pull/20422/files#diff-3f06377a79f6009a753e2864e9bdaab6R774

We should look for other places we can use this new functionality - possibly `ModelStateDictionary` or anywhere else that `StringSegment` is used.
