### ISSUE TITLE
[DI] Pass the requested type to the implementation factory to enable dynamic scenarios when the type isn't known statically

### ISSUE THREAD

**Issue by thomaslevesque** [aspnet/Extensions#478]
### Is your feature request related to a problem? Please describe.

I'm trying to enable lazy injection of services, i.e. if I registered a service for `IFoo`, I'd like to be able to inject a `Lazy<IFoo>` or `Func<IFoo>`. This is useful to solve circular dependency issues; [Unity](https://github.com/unitycontainer/unity) does this automatically. So I'd like to be able to do this:

```csharp
services.AddTransient(typeof(Lazy<>), provider => 
{
    ...
});
```
However, in the factory delegate, I don't have access to the requested type, so I can't dynamically create a `Lazy<T>` of the appropriate type.

### Describe the solution you'd like

Having overloads of `Add*` that accept a `Func<IServiceProvider, Type, object>` would solve this. However it looks like it would be non-trivial, since the `Func<IServiceProvider, object>` signature is used all the way down to the low-level implementation...

Alternatively, implementing lazy injection like in Unity would solve my immediate problem, but would be less extensible.

### Describe alternatives you've considered

Using a third-party container like Unity. But I'd rather keep using the built-in DI container.

### Additional context

N/A

**Comment by dotnetchris** [comment]
+1

**Comment by pakrym** [comment]
Duplicate: https://github.com/aspnet/AspNetCore/issues/3036

**Comment by dotnetchris** [comment]
@pakrym how did you close this issue citing it as a duplicate of a closed issue? This is obviously not a closed issue.

**Comment by dotnetchris** [comment]
@pakrym every single one of those is closed, one of these has to be open. Out of everything you linked aspnet/DependencyInjection#474 looks oldest.

This is clearly not a resolved issue. Unless the official answer is literally WILL NOT EVER SUPPORT, NO MATTER WHAT YOU THINK.

**Comment by pakrym** [comment]
It would require a change to https://github.com/aspnet/DependencyInjection/blob/master/src/DI.Abstractions/ServiceDescriptor.cs#L108 property type.

Which would lead to compiler error everywhere it's invoked. It's an easy change to do inside just this repo but the DependencyAbstraction.Package is used by every compatible service provider implementation out there and all of them would get broken,

**Comment by dotnetchris** [comment]
```c#
        public Func<IServiceProvider, object> ImplementationFactory { get; }

        public Func<IServiceProvider, Type, object> ImplementationFactory2 { get; }

        internal Type GetImplementationType()
        {
            if (ImplementationType != null)
            {
                return ImplementationType;
            }
            else if (ImplementationInstance != null)
            {
                return ImplementationInstance.GetType();
            }
            else if (ImplementationFactory2 != null)
            {
                var typeArguments = ImplementationFactory2 .GetType().GenericTypeArguments;

                Debug.Assert(typeArguments.Length == 3);

                return typeArguments[2];
            }
            else if (ImplementationFactory != null)
            {
                var typeArguments = ImplementationFactory.GetType().GenericTypeArguments;

                Debug.Assert(typeArguments.Length == 2);

                return typeArguments[1];
            }

            Debug.Assert(false, "ImplementationType, ImplementationInstance or ImplementationFactory must be non null");
            return null;
        }
```

etc

**Comment by pakrym** [comment]
I don't see what are you trying to say with this example.

**Comment by dotnetchris** [comment]
@pakrym  You wouldn't **have to *change*** ImplementationFactory, you could have two and then there's no compatibility issues. Not necessarily the prettiest or optimal, but better than what we have today.

**Comment by pakrym** [comment]
But every other container would *have* to support it or it just won't work with new kind of ServiceDescriptor. It's not a compilation breaking change but a breaking change nevertheless

**Comment by dotnetchris** [comment]
@pakrym then it should get slated that v+1 should break and just update the factory then.

**Comment by pakrym** [comment]
We haven't broken other service provider implementation since 1.0 and this feature is certainly not worth it. What it's trying to accomplish already exists in other providers

**Comment by dotnetchris** [comment]
@pakrym this is literally one of the most critical features of a container

**Comment by mravko** [comment]
Much needed feature. Please consider to implement it.

**Comment by thomaslevesque** [comment]
> Much needed feature. Please consider to implement it.

As much as I'd like it, I don't think it will ever be implemented. The team's position is quite clear: they don't want to introduce a breaking change, and it's already possible to do it by using a different container.

In the meantime, I have a solution for my initial problem (lazily resolved service):

```csharp
public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddLazyResolution(this IServiceCollection services)
    {
        return services.AddTransient(typeof(LazyService<>));
    }
}

public class LazyService<T>
{
    private readonly Lazy<T> _service;
    
    public LazyService(IServiceProvider serviceProvider)
    {
        _service = new Lazy<T>(() => serviceProvider.GetRequiredService<T>());
    }
    
    public T Value => _service.Value;
}
```

Usage:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddLazyResolution();
    services.AddSingleton<Foo>();
    services.AddSingleton<Bar>();
}

class Foo
{
    public Foo(Bar bar)
    {
        Bar = bar;
    }
    
    public Bar Bar { get; }
}

class Bar
{
    private readonly LazyService<Foo> _foo;
    
    public Bar(LazyService<Foo> foo)
    {
        _foo = foo;
    }
    
    public Foo Foo => _foo.Value;
}

```
