### ISSUE TITLE
GetDirectoryContents does not accept globbing patterns in path

### ISSUE THREAD

**Issue by AceTheWiz** [aspnet/Extensions#486]
### Describe the bug
GetDirectoryContents does not accept globbing patterns in path
https://github.com/aspnet/Extensions/blob/4bf38407a001d194dab94196aafd237d536ef230/src/FileProviders/Physical/src/PhysicalFileProvider.cs#L275

### To Reproduce
1. Using version '2.2.0-preview2-35157' of package 'Microsoft.Extensions.FileProviders.Physical.'
2. Run this code 
```C#
var dirContents = _env.ContentRootFileProvider.GetDirectoryContents("Content/Systems/**/System.json");
```

### Expected behavior
The function to return a list of files matching the path which contains a glob pattern.

### Debugging
After debugging it was found that the ```PathUtils.HasInvalidPathChars(subpath)``` is true hence the function returns a ```NotFoundDirectoryContents.Singleton```

**Comment by muratg** [comment]
I don't expect we'll make changes here.
