### ISSUE TITLE
Possibility to save configurations.

### ISSUE THREAD

**Issue by FSharpCSharp** [aspnet/Extensions#489]
So far a powerful configuration framework is offered in this repository. Unfortunately there is no possibility to serialize any changes within this framework. Here (unfortunately) even the old standard System.Configuration Framework could do more. It would be desirable to have the possibility to save the changes somehow. This can vary depending on the configuration. According to the repository description everything is independent from any framework and can be used everywhere.

[here](https://github.com/aspnet/Configuration/issues/386) is the link to the original issue in the archived repository.

**Comment by ajcvickers** [comment]
Triage: we have discussed this at length several time and while arguments can be made on both sides we're taking an approach of trying to keep config simple, which means we're not going to add the complexity of persistence.

**Comment by FSharpCSharp** [comment]
That's too bad. What good is an independent configuration framework if it can only be used read-only? On the one hand I understand that this adds complexity, but on the other hand I don't understand it, because deserializing requires a logic, which has already been implemented. So only the "other" side is missing.

**Comment by mysticfall** [comment]
I understand the need to prioritize issues or that some of them may require significant development resources which may better be spent elsewhere. So it'd make sense if the devs decided not to do anything to implement persistence for the time being.

However, closing the issue as 'wontfix' is something different, as it means the devs think that the feature is outside the scope of the project and will never be needed by its users, but is that so really?

Maybe it'd make more sense for web applications, but if I'm not mistaken this project is now a part of .NET standard which can be used for building non web applications as well (even README for this repository explicitly says that).

Without persistence, I believe the usefulness of this API would be significantly hampered for such projects like desktop applications or games, for instance.

Of course, the maintainers have full rights to decide whatever they think the best for their own project. But as a user, I believe it'd have been better if they could at least leave the issue open, so in future someone may take the task to implement the feature.

**Comment by FSharpCSharp** [comment]
Yes, I'm already aware of that. I didn't want to attack anyone with it either. But the topic itself is nothing new, and it already existed in the existing repository. At that time, there was still a discussion about whether it didn't make sense. I am also of the opinion that it is bad to close the topic. Since the development originally even comes from ASP.NET, I understand the approach. In a web application it is also enough to manually configure things in the file. But I also see it that now that the project is independent of ASP.NET, it has relatively limited uses.

Sure, ultimately, the repository owners must decide what they implement and how. But I wonder what happens if someone delivers a pull request with exactly this requirement. Is this also rejected because the topic is not planned, or is it not desired that the topic is solved by the community? I think it would be nice if at least the community could contribute a solution to address the issue. Then it would only be half closed.
