### ISSUE TITLE
Build failure: (was 4631)- failed to publish

### ISSUE THREAD

**Issue by robertborr** [aspnet/Extensions#495]
Copying from $4631 dotnet/core-eng.

Build : 2.1 - 20181113.01 (Product Build)
Failing configurations:

DotNet-Orchestrated-Full-Product-PipeBuild-Release-2.1
Mission Control Build Info

from: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2205006&view=logs

For pipeline 'AspNet-Extensions-Build' with status 'Failed', build 'AspNet-Extensions-CI - https://dnceng.visualstudio.com//internal/_build?_a=summary&buildId=43492 [ (Global)'PB_AZURECLIENTID' = 'cc086027-5579-403a-9e19-5cc2b16b993e'(Global)'PB_FEEDBASEURL' = 'https://dotnetfeed.blob.core.windows.net/orchestrated-release-2-1'(Global)'PB_ISSTABLE' = 'false'(Global)'PB_LoggingSwitch' = '-l'(Global)'PB_PIPELINEFILE' = 'pipelines.orchestrated-release-2.1.json'(Global)'PB_PIPELINEROOTS' = 'aspnet-extensions'(Global)'PB_PublishType' = 'blob'(Global)'PB_SignType' = 'real'(Global)'PB_SkipTests' = 'false'(Global)'PB_VERSIONSREPOPATH' = 'build-info/dotnet/product/cli/release/2.1'(Global)'PB_VERSIONSTAMP' = 'servicing'(Global)'ProductBuildId' = '20181113-01'(Global)'VSTS_OVERWRITE_TEMP' = 'True''SourceBranch' = 'release/2.1''TelemetryBranchName' = 'release/2.1''PB_PublishBlobFeedUrl' = '$(PB_FeedBaseUrl)/$(ProductBuildId)/aspnet-extensions/index.json''PB_PackageVersionPropsUrl' = '$(PB_FeedBaseUrl)/$(ProductBuildId)/aspnet-extensions-inputs/orchestration-metadata/PackageVersions.props''PB_RestoreSource' = '$(PB_FeedBaseUrl)/$(ProductBuildId)/aspnet-extensions-inputs/index.json''PB_AssetRootUrl' = '$(PB_FeedBaseUrl)/$(ProductBuildId)/aspnet-extensions-inputs/assets/''PB_IsFinalBuild' = '$(PB_IsStable)' ]' failed with status 'Failed'.
2018-11-13T18:25:23.5652174Z A total of 1 builds failed.

pipebuild failed with "F:\vsagent-containerSas\12\s.nuget\packages\microsoft.dotnet.build.tasks.feed\2.2.0-preview1-03124-01\build\Microsoft.DotNet.Build.Tasks.Feed.targets(77,5): error : No packages to push. [F:\vsagent-containerSas\12\s\eng\ProdConPublish.csproj]"

**Comment by Eilon** [comment]
Closing because it is not clear what this is in regard to.
