### ISSUE TITLE
Refactor things so data format of the provider is not tied to File based providers

### ISSUE THREAD

**Issue by HaoK** [aspnet/Extensions#496]
For example, JSON/XML format with streams.

**Comment by ajcvickers** [comment]
Moved here from config repo. See old PR: https://github.com/aspnet/Configuration/pull/822

**Comment by ThreeSevenths** [comment]
I would also like to see the JsonConfigurationFileParser made public. I am launching subprocesses and use anonymous pipes to push a json configuration document to the child process for configuration. I would like to be able to use the parser to take the stream from the pipe and turn it into config that I can then use with the configuration lib. Right now, I've simply taken a copy of your parser into my project; it would feel less dirty just calling in from the package.

**Comment by glennc** [comment]
Adding my +1 so that we can use the parsing for things like getting config from an embedded resource in an assembly (A scenario that come up last week for me).

**Comment by HaoK** [comment]
Merged via https://github.com/aspnet/Extensions/pull/1630
