### ISSUE TITLE
Different casing in variables causes exception

### ISSUE THREAD

**Issue by rasmus** [aspnet/Extensions#507]
### Case
Add the same configuration key value pair to from different configuration sources using different casing.

### Expected result
Configuration value from last configuration source is the value present in the final configuration.

The [documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?tabs=basicconfiguration#configuration-by-environment) states that 

> Configuration keys are not case-sensitive

and

> Configuration sources are read in the order that they're specified. In the preceding code, the environment variables are read last. Any configuration values set through the environment replace those set in the two previous providers.

### Actual result
`ArgumentException` with the message `An item with the same key has already been added` is thrown.

![image](https://user-images.githubusercontent.com/18956/36139019-3046a4f8-109c-11e8-9d28-fea346771d03.png)

### Sample program
```csharp
var configurationRoot = new ConfigurationBuilder()
    .AddInMemoryCollection(new Dictionary<string, string>
        {
            {"CASE:PROBLEM", "black magic"}
        })
    .AddInMemoryCollection(new Dictionary<string, string>
        {
            {"case:PROBLEM", "white magic"}
        })
    .Build();

var newconfigurationRoot = new ConfigurationBuilder()
    .AddInMemoryCollection(configurationRoot.AsEnumerable())
    .Build();
```

**Comment by ajcvickers** [comment]
Fixed by https://github.com/aspnet/Extensions/pull/503
