### ISSUE TITLE
Question: AddOptions<T>() vs. Multiple Configure<T>(…)

### ISSUE THREAD

**Issue by smarts** [aspnet/Extensions#514]
I've been writing code like the following in my projects in `Startup.cs`:
```csharp
// this is from ConfigureServices, so services is an instance of IServiceCollection
// assume Configuration is an instance of IConfiguration and was injected via the constructor
services.AddOptions()
  .Configure<MyOptions>(Configuration.GetSection("mySection"))
  .Configure<MyOptions>(x => x.SomeProperty = "foo");
```
and i'm wondering if I should expect this to continue working, or if it is just coincidence and I should switch to the following:
```csharp
services.AddOptions()
  .AddOptions<MyOptions>()
  .Bind(Configuration.GetSection("mySection"))
  .Configure(x => x.SomeProperty = "foo");
```

Some more context: the reason i'm asking this is because i see that in the first example both of those `Configure<TOptions>(…)` methods use `services.AddSingleton<IConfigureOptions<TOptions>>(…)` under the hood, and -- although each uses a different type for the implementation instance -- i was under the impression that the number of registrations for a service type is restricted to one, either by `ServiceCollection` or `ServiceProvider`

**Comment by poke** [comment]
[`Configure<TOptions>(Action<TOptions> configureOptions)`](https://github.com/aspnet/Extensions/blob/master/src/Options/Options/src/OptionsServiceCollectionExtensions.cs#L72) and [`OptionsBuilder<TOptions>.Configure(Action<TOptions> configureOptions)`](https://github.com/aspnet/Extensions/blob/master/src/Options/Options/src/OptionsBuilder.cs#L54) will both end up doing the same thing:

```
services.AddSingleton<IConfigureOptions<TOptions>>(
    new ConfigureNamedOptions<TOptions>(name, configureOptions));
```

And [`OptionsBuilder<TOptions>.Bind(IConfiguration config)`](https://github.com/aspnet/Extensions/blob/master/src/Options/ConfigurationExtensions/src/OptionsBuilderConfigurationExtensions.cs#L40) will actually call [`Configure<TOptions>(IConfiguration config)`](https://github.com/aspnet/Extensions/blob/master/src/Options/ConfigurationExtensions/src/OptionsConfigurationServiceCollectionExtensions.cs#L71-L72) directly, so they are also equivalent.

So both APIs are interchangeable. And you can expect the `services.Configure` calls to continue to work. The options builder API came later to allow for a bit more control with various utility methods. But it’s not a replacement for the direct `services.Configure` API.

**Comment by smarts** [comment]
Doesn't resolving `IEnumerable<T>` require using `[Try]AddEnumerable<T>(…)` when registering? (And this doesn't, because it uses `AddSingleton<T>(…)`)

**Comment by poke** [comment]
The only special thing `TryAddEnumerable` does is that it ensures that you are not accidentally adding the same implementation type multiple times. So when adding something, it checks the collection first.

But no, resolving with `IEnumerable<T>` will give you all implementations that were registered as `T` regardless of how that happened. So if you have multiple `AdsSingleton<T>` calls, you will be able to get all those instances by injecting the enumerable.

If you just inject `T`, then you will only get the implementation that was registered _last_.

**Comment by smarts** [comment]
Thanks! That explanation was very helpful. One last question: I assume the "you will only get the implementation that was registered _last_" behavior is dependent on the `IServiceProvider` implementation, yes?

**Comment by poke** [comment]
Hmm, I’m not too sure about other implementations and how much of that behavior is required by `IServiceProvider`. I think what is true for all DI containers is that the last registration wins. So when you inject `T`, then the last registration for `T` will be what you get. This is to allow overwriting registrations.

Some containers may then choose not to make multiple registrations for `T` available as `IEnumerable<T>`. I think SimpleInjector does not do this; there, you have to register the collection individually.

But since ASP.NET Core requires this behavior for some of the things to work, I would assume that you can expect this to work for all DI containers that integrate with ASP.NET Core.
