### ISSUE TITLE
Are HttpMessageHandlers scoped per Typed HttpClient or a the internal HttpClient?

### ISSUE THREAD

**Issue by abjrcode** [aspnet/Extensions#519]
I have the following scenario:
* I have two different typed `HttpClient`s
* I have a customer `HttpMessageHandler` called `MyCustomHandler`
* I Configure them like this:
```
services
     .AddHttpClient<TeamCity.Client>()
     .AddHttpMessageHandler(() => new MyCustomHandler())

services
     .AddHttpClient<GitHub.Client>()
     .AddHttpMessageHandler(() => new MyCustomHandler())
```
* I notice that the handler attached to `TeamCity.Client` is actually intercepting requests made through `GitHub.Client` ?

I don't understand what is happening here?
1. Are those handlers attached and registered by type and thus they monitor every outgoing request even if it is not made through their typed http client?
1. If the answer to previous question is yes, then why you can ONLY configure handlers when you register (`AddHttpClient<>()`) named or typed clients?

**Comment by rynowak** [comment]
Fixed by https://github.com/aspnet/Extensions/pull/1563
