### ISSUE TITLE
Intercepting resolved services

### ISSUE THREAD

**Issue by andrew-laughlin** [aspnet/Extensions#535]
Is it possible to modify or replace an object after it's created by the container (IServiceProvider), but before it's returned to the caller?

I see IServiceProviderEngineCallback, but it doesn't appear settable.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
