### ISSUE TITLE
Redis cache configuration not working when provided with ConfigurationOptions

### ISSUE THREAD

**Issue by coderookie1994** [aspnet/Extensions#539]
### Describe the bug
I am trying to use the extended options for the AddDistributedRedisCache extension in my ConfigureServices method.
If I use the ConfigurationOptions to setup my Redis configuration, and try to use it in my controller,
I get a Redis connection exception, but if I instead just use the Configuration property, with the url and port, it works as expected.

### To Reproduce
1. Using version '2.2.0-preview3-35497' of package Microsoft.Extensions.Caching.Redis

`
            
            services.AddDistributedRedisCache(setup =>
            {

                setup.InstanceName = "Redis";

                setup.ConfigurationOptions = new ConfigurationOptions()
                {

                    EndPoints = { "redis-url.com", "7000" },
                    Password = "",
                    ClientName = "SafeRedisConnection",
                    ConnectTimeout = 100000,
                    KeepAlive = 30,
                    SyncTimeout = 10000,
                    AbortOnConnectFail = true,
                    AllowAdmin = false,

                };
            });`

### Expected behavior
Should be able to connect to Redis, then create and get value from cache.

### Additional context
dotnet version 2.1.403

**Comment by himalpatel81** [comment]
I'm facing the same issue. what was the solution ?

**Comment by coderookie1994** [comment]
> I'm facing the same issue. what was the solution ?

I was giving the configuration in the wrong way, you can give the configuration as follows :-

`builder.Services.AddDistributedRedisCache(setup =>
            {
                setup.ConfigurationOptions = new ConfigurationOptions();

                setup.ConfigurationOptions.EndPoints.Add(redisCacheHost.Endpoint, Convert.ToInt32(redisCacheHost.Port));
                setup.ConfigurationOptions.Password = "";
                setup.ConfigurationOptions.ClientName = "SafeRedisConnection";
                setup.ConfigurationOptions.ConnectTimeout = 100000;
                setup.ConfigurationOptions.KeepAlive = 30;
                setup.ConfigurationOptions.SyncTimeout = redisCacheHost.ClusterOperationTimeout;
                setup.ConfigurationOptions.AbortOnConnectFail = false;
                setup.ConfigurationOptions.AllowAdmin = false;
            });`
