### ISSUE TITLE
Replace DI event source formatter with JsonWriter when availible

### ISSUE THREAD

**Issue by pakrym** [aspnet/Extensions#541]
See https://github.com/aspnet/Extensions/pull/534#issuecomment-440017922

**Comment by muratg** [comment]
@davidfowl @pakrym Do we expect we'll do this in 3.0?

**Comment by pakrym** [comment]
We'll have some implementation of JsonWriter in Extension in 3.0 timeframe but this issue is "nice to have" and not customer facing.
