### ISSUE TITLE
UserSecrets reloadOnChange

### ISSUE THREAD

**Issue by hansmbakker** [aspnet/Extensions#551]
With `AddJsonFile(...)`, the `reloadOnChange` option is very convenient. Can this be made available for `AddUserSecrets<T>()` as well?

I see that it can be added in `UserSecretsConfigurationExtensions.cs`, but is there a reason for leaving it out from there?

**Comment by natemcmaster** [comment]
Resolved by @Kahbazi in https://github.com/aspnet/Extensions/pull/549. Thanks for the PR!
