### ISSUE TITLE
Mocking A HttpClientFactory

### ISSUE THREAD

**Issue by DinoSourcesRex** [aspnet/Extensions#555]
So I have recently seen [this](https://blogs.msdn.microsoft.com/webdev/2018/02/28/asp-net-core-2-1-preview1-introducing-httpclient-factory/) article and I was wondering what the suggested way to mock this class would be, since it is not an interface?

Failing that how could I utilise an interface with this method that would allow me to mock it? I see that the extension method `.AddHttpClient` takes in an interface, but then I would have to use either `.AddTransient` or `.AddSingleton` and at that point I feel I'm probably over complicating matters and may as well not use `.AddHttpClient` at all.

I often time utilise the method found [here](https://www.davidbreyer.com/programming/2014/10/11/create-fake-responses-to-rest-service-calls-in-c/) for mocking HttpClient currently, however this will mean I will need to mock the entire Client I have created.

---

I'm sure I've missed something basic here so any advice is welcome.

**Comment by stevejgordon** [comment]
Hi @DinoSourcesRex 

For tests involving a dependency on HttpClient, rather than try to mock HttpClient itself, you can create an instance of one, passing in a mocked or stubbed handler.

```csharp
[Fact]
public async Task My Test()
{
  var httpClient = new HttpClient(new ExceptionHandler())
  {
    BaseAddress = new Uri("http://localhost")
  };
	
  ...
	
  await sut.DoSomething(httpClient);
	
  ...
}
	
private class ExceptionHandler : DelegatingHandler
{
  protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,
    CancellationToken cancellationToken) => throw new HttpRequestException("Test");
}
```

Just create a class derived from DelegatingHandler and override the SendAsync method with the response you want. Here I return an exception, but you could build and return a HttpResponseMessage also...

```csharp
private class ClusterHealthyHandler : DelegatingHandler
{
  protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,
    CancellationToken cancellationToken)
  {
    var response = request.RequestUri.ToString().Contains("cluster-health")
      ? new HttpResponseMessage {
        StatusCode = HttpStatusCode.OK,
        Content = new StringContent("{isClusterHealthy:true}", Encoding.UTF8, "application/json")
      }
      : new HttpResponseMessage { StatusCode = HttpStatusCode.OK };

      return Task.FromResult(response);
  }
}
```

**Comment by DinoSourcesRex** [comment]
@stevejgordon Thanks for the response, Steve.

I actually came across [this](https://www.davidbreyer.com/programming/2014/10/11/create-fake-responses-to-rest-service-calls-in-c/) article and ended up using the method described there, which seems to be exactly what you have described here

Appreciate the response.

**Comment by rynowak** [comment]
Closing since it seems like there's nothing for us to do here. Thanks @stevejgordon
