### ISSUE TITLE
Remove all Console.WriteLine messages by default from the ConsoleLifetime impl

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Extensions#557]
https://github.com/aspnet/Hosting/blob/f9d145887773e0c650e66165e0c61886153bcc0b/src/Microsoft.Extensions.Hosting/Internal/ConsoleLifetime.cs#L37-L39

We should just use the logger instead.

**Comment by davidfowl** [comment]
@glennc @Tratcher side effect of this change is the following:

![image](https://user-images.githubusercontent.com/95136/50721194-431f0a00-1070-11e9-950e-bf0eded5ee63.png)

This is release mode in the default template. There's no output by default since we only log warning.

**Comment by Tratcher** [comment]
By design?

**Comment by davidfowl** [comment]
I'm not sure it's good though, at least not by default. You can't really tell what's going on.

**Comment by Tratcher** [comment]
"Listening on..." isn't a warning level event, and people explicitly asked us to turn it off in production.

Is there some other signal we could give to indicate the server has started besides console output? E.g. Updating Console.Title? Though that would be the next thing people ask to opt-out of.
