### ISSUE TITLE
ChangeToken.OnChange() firing twice in quick succession.

### ISSUE THREAD

**Issue by dazinator** [aspnet/Extensions#564]
### Describe the bug
as per #2542 - `ChangeToken.OnChange` appears to fire twice in quick succession when consuming IFileProvider.Watch(). The issue seemed to result in some discussion for how to workaround the issue for `IOptionsMonitor` (and config files), which as much as it is good there is a workaround for that scenario, there are other times (other then IOptionsMonitor) that you may consume `IFileProvider.Watch` and in those cases you are left to deal with this quirk, which is unexpected and undocumented, and problematic. 

In my case, I have developed a browser refresh mechanism, that triggers a refresh (using signalr) as a result of watching particular files for changes using IFileProvider.Watch(). When a file changes, I don't want to have to re-hash a whole files contents each time, as if the file is large (like bundled js file for example) it might result in too much of a delay between an edit and a browser refresh. Given this problem is surfaced from IFileProvider's watch API, it would be good to have some documentation, or suggested, in-built, mechanism for dealing with these duplicate OnChange() invocations in the general case..

For example, it would be good to have some in built mechanism, than, on invocation of a change token, can delay for x period of time, and within that x period of time, if a duplicate change token invocation occurs, exit from the first invocation without doing anything further, and allow the duplicate invocation to go through that same process, i.e delay for a bit, etc, until eventually processing only continues when no duplicate change token has been signalled within the delay window of time.

### To Reproduce
1. You can see code here that watches a bunch of files on a file provider, if you then save a change to a file, the OnChange is invoked twice in quick succession (atleast on my windows 10 machine that appears to be the case): https://github.com/dazinator/NetPack/blob/develop/src/NetPack.BrowserReload/BrowserReloadHostedService.cs#L66

### Expected behavior
When watching a file, if the file changes, I'd expect the change token to be signalled once, or have some common mechanism for consolidating duplicate signals sent via IFileProvider.Watch (which is the implementation that is causing the problem).

**Comment by Tratcher** [comment]
Duplicate / FAQ, see https://github.com/aspnet/AspNetCore/issues/2542
