### ISSUE TITLE
Remove dependency on Newtonsoft.Json from Config.Json

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Extensions#568]
cref https://github.com/dotnet/announcements/issues/90

Let's remove our dependency on Newtonsoft.Json from the Json configuration provider and use System.Text.Json. This will unblock https://github.com/aspnet/AspNetCore/issues/4260.

**Comment by ajcvickers** [comment]
@natemcmaster @DamianEdwards @Eilon 

@HaoK and I discussed this yesterday and we don't believe it is possible to implement under the current plan. Specifically, since Config is in Extensions, and Extensions must still target .netstandard2.0, and the new JSON APIs will not be available on .netstandard2.0, there's no way to use it.

**Comment by Eilon** [comment]
Should we get in a room to discuss?

**Comment by natemcmaster** [comment]
Yes, I think we should.

**Comment by ajcvickers** [comment]
@Eilon Yep. But I think the discussion is wider than just this. There are other packages where we are saying we want to both support new features and .NET Framework. /cc @divega

**Comment by Eilon** [comment]
Yup agreed.

**Comment by HaoK** [comment]
Due to some differences in the new json stack and Json.Net for back compat, we are going to add another package that continues to use Json.NET see: https://github.com/aspnet/Extensions/issues/1075

The main difference between the two is loss of support for single quotes:

```C#
            var json = @"{
                'setting': {
                    'hello': 'a',
                    'bob': 'b',
                    '42': 'c',
                    '4':'d',
                    '10': 'e',
                    '1text': 'f',
                }
```

**Comment by HaoK** [comment]
Added via https://github.com/aspnet/Extensions/pull/1028
