### ISSUE TITLE
BachLoggingProvider: There's no need to use async methods inside a dedicated thread 

### ISSUE THREAD

**Issue by BBGONE** [aspnet/Extensions#571]
If there will be a real asynchronous operation, then its continuation will be on a thread pool thread. After that it won't return to the dedicated thread and can potentially use one threadpool thread for the rest of application lifetime.

```
_outputTask = Task.Factory.StartNew<Task>(
    ProcessLogQueue,
    null,
    TaskCreationOptions.LongRunning);
```

https://github.com/aspnet/Extensions/blob/master/src/Logging/Logging.AzureAppServices/src/BatchingLoggerProvider.cs

This certainly  will have continuation on a threadpool thread:

```
protected virtual Task IntervalAsync(TimeSpan interval, CancellationToken cancellationToken)
{
            return Task.Delay(interval, cancellationToken);
}
```

### Describe the solution you'd like
Remove async methods. It's not a problem to block a dedicated thread. It is used only by only one task.

### Describe alternatives you've considered
Or start the task without TaskCreationOptions.LongRunning (but that was probably was meant and desirable to run the logger on dedicated thread - so it is not a good option)

### Additional context
https://github.com/andrewlock/NetEscapades.Extensions.Logging/issues/8

**Comment by pakrym** [comment]
`TaskCreationOptions.LongRunning` doesn't start a dedicated thread, it would still run on thread. Using sync methods would just mean that we are blocking a thread waiting on an async code that still would use thread pool to complete.

**Comment by BBGONE** [comment]
Do you mean that now, CoreFx has a bug and uses a threadpool thread to execute a longrunning task on it? 
In the full Net Framework it used a dedecated thread. I will try to find the code for the default TaskScheduler for CoreFx to check it.

**Comment by pakrym** [comment]
Yep, you are right. https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/src/System/Threading/Tasks/ThreadPoolTaskScheduler.cs#L42 . Let's change it to `Task.Run` then.

**Comment by pakrym** [comment]
Want to send a PR?

**Comment by BBGONE** [comment]
Yes, it will work.  But in my own implementation, i will use a dedicated thread. It is more robust and reliable in this case.

**Comment by BBGONE** [comment]
What is PR?

**Comment by pakrym** [comment]
A pool request.

**Comment by BBGONE** [comment]
No. I dont use it. I found it only because of trying to create my own LogProvider. I used it as example.
I did some optimisations
https://github.com/aspnet/Extensions/issues/572
The log provider writes XML formatted messages, but in the rest it is almost the same.

**Comment by BBGONE** [comment]
Giving it a thought - even if it will stay like it was - with TaskCreationOptions.LongRunning, it won't harm too much. The dedicated thread will be used until the first truly async task, then it will simply exits and dies. All the rest of the code will be on threadpool threads, And even that depends on the SynchronizationContext and the task scheduler associated with it.
