### ISSUE TITLE
Creating a Host that doesn't use ConsoleLifetime

### ISSUE THREAD

**Issue by tmds** [aspnet/Extensions#574]
It's not clear how to build a host that doesn't use `ConsoleLifetime`.

I tried (using Microsoft.Extensions.Hosting 2.1.0):
```cs
            CancellationTokenSource cts = new CancellationTokenSource();
            var host = new HostBuilder()
                .Build();
            await host.RunAsync(cts.Token);
```
which picks up the `ConsoleLifetime`.

**Comment by davidfowl** [comment]
What are you trying to do?

**Comment by tmds** [comment]
I'm verifying the host works when passed a token that gets cancelled on SIGINT/SIGTERM. That works.

I was then looking how to build a host that doesn't use SIGINT/SIGTERM.
[From the docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.1), it sounds like SIGINT/SIGTERM handling would only be enabled when using `UseConsoleLifetime`, `RunConsoleAsync`. It looks like it is always enabled.

**Comment by davidfowl** [comment]
I don't think we;re going to support this. You can override the lifetime if required by this will be the default behavior. I'm not sure we event need RunConsoleAsync

**Comment by tmds** [comment]
@davidfowl the Host will need to deal with `Environment.ExitCode` (https://github.com/aspnet/AspNetCore/issues/6526). In light of that, I think it makes sense for there to be two different methods, one that attaches to consolelifetime, deals with ExitCode, and returns an int. And another that doesn't do this stuff. See https://github.com/aspnet/AspNetCore/issues/5920#issuecomment-453017837 and below comments.

CC @Tratcher @halter73
