### ISSUE TITLE
AddTypeActivatedCheck overloads do not pass on args parameter

### ISSUE THREAD

**Issue by logandrews** [aspnet/Extensions#598]
I don't know if this is the correct repo to put this as the description says it is archived, but the nuget package says it was built from this repo.

I was trying out the new 2.2 release and discovered that two of the overloaded AddTypeActivatedCheck extension methods accept and args parameter, but do not pass it on.
https://github.com/aspnet/Diagnostics/blob/master/src/Microsoft.Extensions.Diagnostics.HealthChecks/DependencyInjection/HealthChecksBuilderAddCheckExtensions.cs#L104
https://github.com/aspnet/Diagnostics/blob/master/src/Microsoft.Extensions.Diagnostics.HealthChecks/DependencyInjection/HealthChecksBuilderAddCheckExtensions.cs#L135

I had an additional string parameter I wanted to pass to the constructor of my IHealthCheck and had to manually pass null for the failureStatus and tags parameters for it to work.

It appears that the tests only cover the use of the extension method that take all four parameters:
https://github.com/aspnet/Diagnostics/blob/082d505977d72c75b68935c93c21feded6928e5f/test/Microsoft.Extensions.Diagnostics.HealthChecks.Tests/DependencyInjection/HealthChecksBuilderTest.cs#L86

The fix seems pretty straight forward and I'd be interested in trying my hand at a pull request to resolve the issue if this is the correct repo to do it in.

Thanks!

**Comment by rynowak** [comment]
Yes, this is indeed a bug. Please send a PR if you have time, if not I will fix it some time in the next few days.

**Comment by rynowak** [comment]
This is fixed in 3.0-preview4

**Comment by Peter-Optiway** [comment]
Will this be fixed in 2.2 I'm having the same issue and 3.0 is still in preview
