### ISSUE TITLE
ChangeToken.OnChange ends in an endless loop

### ISSUE THREAD

**Issue by kvalev** [aspnet/Extensions#613]
### Describe the bug
This sounds ridiculous, but hear me out. I assume that due to my somewhat unusual setup, `ChangeToken.OnChange` ends up in an endless loop and at some point crashes with a StackOverflowException.
I am using the 32bit Windows 7 VM from [modern.ie](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) running on VirtualBox with the latest Visual Studio 2017 Community version to play around with the Azure Functions v2 SDK. Whenever I start the example function, the runtime only prints the runtime versions (and the logo) and that's it:
```
Azure Functions Core Tools (2.3.148 Commit hash: f9b3db04f9833b431f1b001efb3e5783a169ebfc)
Function Runtime Version: 2.0.12210.0
```

After about 25 mins, the process crashes with a StackOverflowException. Here is a snippet:
```
	System.IO.FileSystem.Watcher.dll!System.IO.FileSystemWatcher.AllocateBuffer() Line 252	C#
 	System.IO.FileSystem.Watcher.dll!System.IO.FileSystemWatcher.StartRaisingEvents() Line 49	C#
 	System.IO.FileSystem.Watcher.dll!System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed() Line 626	C#
 	System.IO.FileSystem.Watcher.dll!System.IO.FileSystemWatcher.EnableRaisingEvents.set(bool value) Line 172	C#
 	Microsoft.Extensions.FileProviders.Physical.dll!Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher() Line 328	C#
 	Microsoft.Extensions.FileProviders.Physical.dll!Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(string filter) Line 118	C#
 	Microsoft.Extensions.FileProviders.Physical.dll!Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(string filter) Line 220	C#
 	Microsoft.Extensions.Configuration.FileExtensions.dll!Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor.AnonymousMethod__0_0() Line 33	C#
 	Microsoft.Extensions.Primitives.dll!Microsoft.Extensions.Primitives.ChangeToken.OnChange.AnonymousMethod__0(object s) Line 38	C#
 	System.Private.CoreLib.dll!System.Threading.CancellationTokenSource.InternalRegister(System.Action<object> callback, object stateForCallback, System.Threading.SynchronizationContext syncContext, System.Threading.ExecutionContext executionContext) Line 546	C#
 	System.Private.CoreLib.dll!System.Threading.CancellationToken.Register(System.Action<object> callback, object state, bool useSyncContext, bool useExecutionContext) Line 236	C#
 	Microsoft.Extensions.Primitives.dll!Microsoft.Extensions.Primitives.CancellationChangeToken.RegisterChangeCallback(System.Action<object> callback, object state) Line 36	C#
```

I spend some time stepping through the WebHost, ASP.NET Code and managed to pinpoint the issue to the `ChangeToken.OnChange` invocation in the `FileConfigurationProvider` [constructor](https://github.com/aspnet/Extensions/blob/62d66dc/src/Configuration/Config.FileExtensions/src/FileConfigurationProvider.cs#L32-L37). In my case the code never continues past the ctor, instead the `OnChange` callback is being executed recursively, from what it seems.

### To Reproduce
1. Use the Windows 7 (IE 11) 32bit Virtual Box VM linked above and install Visual Studio 2017 Community with the Azure workload tools.
2. Install .NET Core 2.1 and 2.2
3. Can be reproduced with the following console application:
```
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            
            String folderWorking = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
            String folderNonWorking = System.IO.Path.GetDirectoryName(Assembly.GetEntryAssembly().Location);
            IFileProvider provider = new PhysicalFileProvider(folderNonWorking);

            var source = new JsonConfigurationSource
            {
                FileProvider = provider,
                Path = "nonexistent.json",
                Optional = true,
                ReloadOnChange = true,
                ReloadDelay = 250,
            };
            
            new JsonConfigurationProvider(source);

            Console.WriteLine("Bye World!");
            Console.ReadLine();

        }
    }
```

csproj:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <!-- also reproducible with netcoreapp2.1 -->
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <!-- also reproducible with version 2.1.6 (netcoreapp2.1) -->
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.2.0" />
  </ItemGroup>

</Project>
```
4. `Bye world` often times does not get shown.

### Expected behavior
It should not crash with a StackOverflowException.

### Additional context
In the sample above if I use the user's home folder (`folderWorking`), then the application terminates as expected - I executed it several dozen times and not even once did the sample get stuck... However if I user the `folderNonWorking`, which is the `bin` folder, then at least 50% of the times, the execution get stuck and the second print statement is not being shown.
This example works as expected on my native macOS.

**Comment by davidfowl** [comment]
I can see how it can happen from the code but we need to figure out what's going on here because the alternative would just be an infinite loop. My guess is that you're somehow in a situation where you end up getting the same token that's already fired or maybe something is triggering that many file changes.

Can you reproduce this outside of virtual box? If not, can you run something like [procmon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) to see if there's any file system activity or if there's a bug elsewhere.

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue if we're able to identify the problem.

**Comment by rlongre** [comment]
I was having the same issue on the MSEdge on Win10 (x64) Stable 1809 VirtualBox VM when running code located on a host OS volume exposed to the guest OS as a shared folder. About 8 out of 10 times starting an ASP.NET Core app would result in this loop, ending with a StackOverflowException.

I haven't experienced the problem again yet after copying the code to a drive within the VM.
