### ISSUE TITLE
[Helix] HttpClientFactory DisposesLiveHandler is flaky on OSX/Linux queues

### ISSUE THREAD

**Issue by HaoK** [aspnet/Extensions#632]
This tests fails roughly half the time on helix runs of 2.1, OSX/ubuntu queues specifically, seems reliable on Win10

@rynowak github blame says this bad boy might be yours?  Any ideas why this test might be misbehaving?

For example: https://mc.dot.net/#/user/dotnet-github-anon-kaonashi-bot/pr~2Faspnet~2Fextensions/ci/20181211.10/workItem/Microsoft.Extensions.Http.Tests~2Fnetcoreapp2.0/wilogs

```
[xUnit.net 00:00:02.57]     Microsoft.Extensions.Http.DefaultHttpClientFactoryTest.Factory_CleanupCycle_DisposesLiveHandler [FAIL]
Failed   Microsoft.Extensions.Http.DefaultHttpClientFactoryTest.Factory_CleanupCycle_DisposesLiveHandler
Error Message:
 Cleanup entry disposable
Expected: True
Actual:   False
Stack Trace:
   at Microsoft.Extensions.Http.DefaultHttpClientFactoryTest.Factory_CleanupCycle_DisposesLiveHandler() in /_/src/HttpClientFactory/Http/test/DefaultHttpClientFactoryTest.cs:line 409
```

**Comment by rynowak** [comment]
This is a super fun test. I made some improvements to this in 2.2, and I think I finally did fix the flakiness.

**Comment by rynowak** [comment]
Ah, actually that was master, not 2.2. Are we fixing flaki-wakies on 2.1?

**Comment by HaoK** [comment]
Can you backport the fixes to 2.1?  That's where we are starting with the helix runs

**Comment by rynowak** [comment]
Sure

**Comment by HaoK** [comment]
Should be fixed by https://github.com/aspnet/Extensions/pull/635#event-2022475211
