### ISSUE TITLE
Invalid exception argument

### ISSUE THREAD

**Issue by sungam3r** [aspnet/Extensions#634]
### Describe the bug
https://github.com/aspnet/Extensions/blob/master/src/HealthChecks/Abstractions/src/HealthCheckResult.cs#L73

exception: null instead of passing exception argument (maybe because of copy/paste code from `Healthy` method)

### Expected behavior
Pass `exception` parameter to `HealthCheckResult` ctor instead of `exception: null`.

**Comment by rynowak** [comment]
Closing since this is fixed. Thanks!
