### ISSUE TITLE
TryAddSingleton possible misuse in AddHealthChecks method

### ISSUE THREAD

**Issue by sungam3r** [aspnet/Extensions#639]
### Describe the bug

Maybe I'm wrong, but I think that in this line
https://github.com/aspnet/Extensions/blob/112c1a8ae1c0a921eae4490abd4ccdfcdb899574/src/HealthChecks/HealthChecks/src/DependencyInjection/HealthCheckServiceCollectionExtensions.cs#L29
there must be ``AddSingleton`` method instead of `TryAddSingleton` method, because `TryAddSingleton` will check only `ServiceType` property:
https://github.com/aspnet/Extensions/blob/3ba072c25373c19ab2cfe34483e733f3b926b2c0/src/DependencyInjection/DI.Abstractions/src/Extensions/ServiceCollectionDescriptorExtensions.cs#L88

So, if we have multiple hosted services (one is enough) which were added to `IServiceCollection` 
 (probably through `AddHostedService` extension method) **before** `AddHealthChecks` call , then the `TryAddSingleton` won`t do anything.

Also, as I see in comments, `AddHealthChecks` method is supposed to be idempotent, so maybe it is better to use `TryAddEnumerable` method explicitly? https://github.com/aspnet/Extensions/blob/3ba072c25373c19ab2cfe34483e733f3b926b2c0/src/DependencyInjection/DI.Abstractions/src/Extensions/ServiceCollectionDescriptorExtensions.cs#L585

`TryAddEnumerable` will check **both** `ServiceType` **and** `ImplementationType` properties, so `HealthCheckPublisherHostedService` ultimately will be added to `IServiceCollection` and `Host` will be able to resolve it through `Services.GetService<IEnumerable<IHostedService>>()`.

**Comment by rynowak** [comment]
Yes, you are right. This is a bug!

**Comment by sungam3r** [comment]
Will this be fixed in the next release?

**Comment by rynowak** [comment]
This will be fixed in 3.0 - is this blocking for you in 2.2? Do you need help finding a workaround?

**Comment by sungam3r** [comment]
No, now it is not critical. Just after reading the release notes about health checks in netcore 2.2, looking through the code found it. Thanks!

**Comment by NatMarchand** [comment]
For people stuck, one possible workaround is:
```csharp
services.AddHealthChecks();

// This is a hack to fix an issue with the AddApplicationInsightsPublisher() call above
services.TryAddEnumerable(ServiceDescriptor.Singleton(typeof(IHostedService), typeof(HealthCheckPublisherOptions).Assembly.GetType("Microsoft.Extensions.Diagnostics.HealthChecks.HealthCheckPublisherHostedService")));
```

**Comment by sungam3r** [comment]
@NatMarchand  I see your workaround in [docs](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-2.2) but it is written incorrectly. HealthCheckServiceAssembly should be changed to "Microsoft.Extensions.Diagnostics.HealthChecks.HealthCheckPublisherHostedService".
