### ISSUE TITLE
Ommit Category in the log message

### ISSUE THREAD

**Issue by rprimora** [aspnet/Extensions#642]
Is there a way to ommit category information from log message.

Right now if I log information 

> Requested home/index

the logger will actually log

> MyProject.Controllers.HomeController
> Requested home/index

Obviously this is no problem in most cases but for me its just cluttering the log. I am interested only in message.

Is there a way to accomplish this without writting my own implementation of ILoggerProvider?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
