### ISSUE TITLE
Log caller context in an ILogger implementation

### ISSUE THREAD

**Issue by david-jarman** [aspnet/Extensions#643]
Is it possible to log the caller context in an ILogger implementation? It would be trivial in a concrete class to log the caller context by using the CallerFilePath / CallerMemberName / CallerLineNumber attributes decorated on some default parameters, but I'm failing to come up with a way to get the same data in an ILogger implementation. 

It would be great if I could do the below:
```CSharp
public void SomeMethod()
{
    // Get my mythical logger instance that logs caller context
    ILogger logger = _loggerFactory.CreateLogger();
    logger.LogInformation("Hello World");
}

// output: [SomeMethod][Line 3] Hello World
```

Has anyone come up with a solution to this problem?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
