### ISSUE TITLE
Inability to filter EventSource categories defined by LoggingEventSource.Keywords

### ISSUE THREAD

**Issue by rymeskar** [aspnet/Extensions#645]
LoggingEventSource should be public because one needs to use the 'inside-class' defined Keywords for EventListeners. This pattern was even visible in tests before. The visibility was bent, by marking the test as a friend assembly.

LoggingEventSource should be also sealed as per this [documentation](https://github.com/Microsoft/dotnet-samples/blob/master/Microsoft.Diagnostics.Tracing/EventSource/docs/EventSource.md).  The reasoning behind is to keep the class hierarchy as trivial as possible.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
