### ISSUE TITLE
Logging perfomance concerns

### ISSUE THREAD

**Issue by Kikimora** [aspnet/Extensions#646]
I'm trying to find suitable library to log in a high-performance application. Basic requirement is being able to process 10000 requests per second while logging maybe 100 messages per request. This app doing some fancy stuff in multiple threads and having detailed traces of what has happened is crucial for debugging. 

Obviously with such requirements logging backend has to be asynchronous, and logging itself has to be very careful with memory allocations. I can implement logging backend and write messages into a file or FluentD in background thread.  But then I cannot find a way to generate log messages without generating lot of garbage. 

I hoped that `LoggerMessage` can match my requirements at least partially. But this [blog post](https://blogs.msdn.microsoft.com/fkaduk/2018/08/05/benchmarks-of-the-logging-with-loggermessage/) raises very reasonable concerns about `LoggerMessage` performance. Since `LoggerMessage` style of logging creates `LogValues` object for every message and then boxes every primitive value I maybe looking at generating few millions of temporary objects just by logging.

I also looked into `EventSource` and tracing with lttng, but it looks very immature on Linux which is my target platform. So my question boils down to this - can you recommend any way to log while at the same time keeping object allocation rate as low as possible?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
