### ISSUE TITLE
Default LogLevel configuration not taking effect

### ISSUE THREAD

**Issue by kierenj** [aspnet/Extensions#648]
I'm struggling to find where I'm making a mistake, or if I've run across a bug.  I'm having to do the following, with repeats for each provider I use (Console, Debug, and JsonFile, my own provider based on the App Insights one but which logs to disk):

```c#
"logging": {
    "Console": {
      "logLevel": {
        "Microsoft.EntityFrameworkCore.Database.Connection": "Warning",
        "Microsoft.EntityFrameworkCore.Database.Command": "Information",
        "Microsoft.EntityFrameworkCore.Database.Transaction":  "Warning" 
      }
    }
  },
```

I'd love to be able to specify without the provider level key, but it doesn't take effect at all.

Here's how I'm building my logging setup.  This is in a delegate passed to ASP.NET Core's `.ConfigureLogging()`:

```c#
builder.AddConfiguration(configuration.GetSection("Logging"));

// kind of unrelated but for completeness' sake:
var loggersSection = configuration.GetSection("Loggers");
builder.Services.Configure<JsonFileLoggerOptions>(loggersSection.GetSection("jsonFile"));
builder.Services.Configure<ConsoleLoggerOptions>(loggersSection.GetSection("console"));

var allEvents = builder.SetMinimumLevel(LogLevel.Trace);
allEvents
    .AddJsonFile()
    .AddFilter<ConsoleLoggerProvider>(l => l >= LogLevel.Information)
    .AddConsole()
    .AddFilter<DebugLoggerProvider>(l => l >= LogLevel.Debug)
    .AddDebug();
```

I will admit I feel like I don't really know what I'm doing here - the docs cover most cases, but I'm not sure 100% on how filters combine, reset filtering, etc etc.

What I'd really like to know as well is how to specify those filters I'm going for in code, but have them overridable by config, optionally not at provider level.  Is that best handled with a composite configuration, in-memory provider then file one to override, or is there another way?

**Comment by pakrym** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
