### ISSUE TITLE
Add support for systemd/syslog priority levels to the console logger

### ISSUE THREAD

**Issue by halter73** [aspnet/Extensions#650]
In order to better support [systemd app monitoring](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.0&tabs=aspnetcore2x#monitoring-the-app), we should add an option to the console logger to use systemd daemon logging prefixes as [described here](https://www.freedesktop.org/software/systemd/man/sd-daemon.html). This will allow better filtering of logs via journalctl. Basically we just need to prefix logs with `<Numeric Log Number>`. Based on the linked man page, we might also want to write to stderr instead of stdout, but I'm not sure if this is necessary.

See aspnet/KestrelHttpServer#2679 for original customer report.

**Comment by BrennanConroy** [comment]
Done via https://github.com/aspnet/Extensions/pull/1777
