### ISSUE TITLE
Inconsistent singleton constructor accessibility

### ISSUE THREAD

**Issue by halter73** [aspnet/Extensions#662]
In 2.0, the `NullLugger<T>` and `NullLoggerFactory` singletons were added to Microsoft.Extensions.Logging.Abstractions. Unlike all the previous singletons in the assembly (`NullLogger`, `NullLoggerProvider` and `NullScope`), the two new singletons have public parameterless constructors.

These constructors should be made private for consistency, easier back-compat, and so there's one right way to get an instance.

**Comment by pakrym** [comment]
We can't remove them in 3.0 without obsoleting first.

**Comment by pranavkm** [comment]
@halter73 closing this. It's unfortunate, but it's not really a breaking change with little value.
