### ISSUE TITLE
Make public property for FormattedLogValues._values 

### ISSUE THREAD

**Issue by akiander** [aspnet/Extensions#664]
I want the following field to be accessible, even it it's read-only: 

[Microsoft.Extensions.Logging.Internal.FormattedLogValues._values](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.Abstractions/Internal/FormattedLogValues.cs#L23)

I am implementing a logger that allows users to pass in objects that I flatten and add as attributes to the underlying store. But my logger can't access those objects when they are passed into logging methods like this: 

    logger.LogInformation("Some Text", MyObject1, MyObject2); 

If I can capture these objects and flatten them, then I can store them as metadata in my log storage database in such a way that they are queryable. I believe this isn't supported without the change I'm proposing here, unless you know of another way to gain access to the objects passed to logging. 

I understand that most people pass in primitives that get interpolated into the string using syntax such as: 

    logger.LogInformation("The ID is {id}", id); 

..and I also use that mechanism. I like this capability but I want to go one step further and allow my logger full access to the objects so my logger has the freedom to store them the correct way and not as string or other primitives. So if you make the FormattedLogValues._values field public (read-only) for the loggers then it doesn't break or prevent the original functionality and, as a bonus, this can also support the mechanism I mention above for capturing rich metadata from full objects passed to logging. 

Thoughts?

**Comment by muratg** [comment]
@davidfowl please triage or close this one. Thanks.

**Comment by davidfowl** [comment]
Closing this in favor of #533, We have no plans to expose this internal type.
