### ISSUE TITLE
Provide more generic Log() method

### ISSUE THREAD

**Issue by ddobric** [aspnet/Extensions#667]
Right now we have several extension methods for logging defined in LoggerExtensions (LogWarning, LogError,..). 

Additionally we have a publc more generic method in ILogger

void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter);

That one is public, but very ugly to use. Moreover, it requires as to provide a formatter instead of using default one, which is not accessible.

Suggestion:
It would be good to have a following (additional) method in LoggerExtensions,cs

 public static void Log(this ILogger logger, string message, params object[] args)

**Comment by muratg** [comment]
If folks are still interested in sending a PR, please file a new bug and link this one.
