### ISSUE TITLE
Change to IDisposable BeginScope(TState state) API

### ISSUE THREAD

**Issue by bnayae** [aspnet/Extensions#671]
You should consider to change the IDisposable BeginScope(TState state) API,
to something that return IScopedLogger (which is sub set of the logging functionality) 
this way you can encapsulate the scope and can log data to different scope simultaneously on different threads.
when encapsulating the log this way it is easier to maintain and understand logging data related to specific scope.

```

public interface IScopedLogger : IDisposable
{
    bool IsEnabled(LogLevel logLevel);
    void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter);
}
```

**Comment by muratg** [comment]
I don't expect we'll do any changes here.
