### ISSUE TITLE
Custom ILogValues objects are ignored with the LoggerExtensions

### ISSUE THREAD

**Issue by poke** [aspnet/Extensions#674]
Custom `ILogValues` types are currently ignored when producing the log output. The `ILogValues` contract suggests that you just need to expose a key/value enumerable in order to have them somewhat nicely outputted to the log.

However, because of how the Log methods [are implemented](https://github.com/aspnet/Logging/blob/98fe4f77b99dc93fb7faf0888f0430195377c0ff/src/Microsoft.Framework.Logging.Abstractions/LoggerExtensions.cs#L564) that take the `ILogValues` objects, they always pass in the default `_messageFormatter` which in the end just uses [`ILogValues.ToString()`](https://github.com/aspnet/Logging/blob/98fe4f77b99dc93fb7faf0888f0430195377c0ff/src/Microsoft.Framework.Logging.Abstractions/LoggerExtensions.cs#L601) to produce the output.

The logger implementations, for example the [ConsoleLogger](https://github.com/aspnet/Logging/blob/9aa1ab4fc4e1445e1af259de1294e9328fe039ca/src/Microsoft.Framework.Logging.Console/ConsoleLogger.cs#L40) actually checks for the `ILogValues` objects and produces a nice output, but since the logger extension passed in a [non-null formatter](https://github.com/aspnet/Logging/blob/9aa1ab4fc4e1445e1af259de1294e9328fe039ca/src/Microsoft.Framework.Logging.Console/ConsoleLogger.cs#L36), this all is for nothing.

Since the `ILogValues` interface seems to be something meant as high-level as the extensions themselves, it would probably make most sense to implement a custom handling within the MessageFormatter there. Alternatively, the `ILogValues` interface should be changed to make clear that implementing `ToString` is required in order to produce an acceptable output.

**Comment by muratg** [comment]
I don't expect we'll do any changes here.

**Comment by poke** [comment]
That’s fine with me. I don’t remember what I was going with back then anyway and totally forgot about this issue. And `ILogValues` isn’t a thing anymore anyway.
