### ISSUE TITLE
LoggerExtensions Can't Combine Exception and Format String

### ISSUE THREAD

**Issue by ardalis** [aspnet/Extensions#675]
If you want to log:
1) eventId
2) Exception
3) Formatted message

There is currently no extension method allowing this. Can we add one, or should this scenario just use the Log method? Here is the proposed signature:

```
public static LogCritical([NotNull] this ILogger logger, int eventId, string format, Exception error, params object[] args)
```

I just ran into this while trying to log an exception in a catch {} block in which I also wanted to include some details about the request:

```
_logger.LogCritical(eventId, "{eventId}: Unexpected error handling request {path}.", ex, eventId, context.Request.Path);
```

It doesn't work as desired because the exception (ex) is part of the args array for this overload (so the exception is output in place of {eventId} and the eventId is output in place of {path}).

**Comment by muratg** [comment]
I don't expect we'll do more changes here.
