### ISSUE TITLE
Include eventId as factory Add extensions filter parameter

### ISSUE THREAD

**Issue by kspearrin** [aspnet/Extensions#676]
Currently we are given the ability to filter logs for each provider based on the category/name string and log level enum when adding them to the factory like so:

```
loggerFactory.AddDebug( ( category, level ) => level >= LogLevel.Information );
```

It would be nice if the we were given the option to filter by eventId as well:

```
loggerFactory.AddDebug( ( category, level, event ) => 
    level >= LogLevel.Information
    && event != 10 );
```

I know we can easily just create our own provider that implements this extension overload (which is what I have done for now), but my suggestion is to include it with the providers that come with the library by default.

**Comment by muratg** [comment]
I don't expect we'll do this.
