### ISSUE TITLE
DependencyInjection : declare services with custom attributes

### ISSUE THREAD

**Issue by ah1508** [aspnet/Extensions#680]
### Is your feature request related to a problem? Please describe.
`AddService` (or `AddSingleton`, etc....) declaration on `ServiceCollection` is a bit cumbersome, how about providing a discovery mechanism like for `[ApiController]` ? 

### Describe the solution you'd like
A `[Component]` or `[Service]` built in custom attribute would be available, and a 

`public static IServiceCollection Scan(this IServiceCollection sc, params string[] assemblies)` 

extension method on the `IServiceCollection` type would enable the discovery mechanism and add the decorated types as services in the service collection. A type would be registered in the service collection if decorated by `[Component]` or by a subclass of `[Component]` (which opens the way to home made custom attributes).

Of course the custom attribute must provide some properties so the developer keeps control on how the type is registered. Exemple : 

```
public class ComponentAttribute : System.Attribute
{
  public ServiceLifetime Lifetime {get;private set;}
  public Type[] VisibleAs {get;set;}
  public bool VisibleAsSelf {get;set;}

  public ComponentAttribute(ServiceLifetime lifetime) => this.Lifetime = lifetime;
}
```

`VisibleAs` : under which interface(s) the implementation type is registered. A default behavior could be considered if this property is null (visible as all / none of its interfaces).
`VisibleAsSelf` : if the implementation type is registered as itself (service type = implementation type).

If a type must be exposed under multiple forms (implemented interfaces, itself), a single instance should be created and reused for every call to `AddService`.

Default behaviors for these two settings could be passed as argument to the `Scan` method

`Scan` could look like that : 

```
IDictionary<Type, ComponentAttribute> components = assemblies
 .SelectMany(a => a.GetTypes())
 .Where(t => Attribute.IsDefined(t, typeof(ComponentAttribute)))
 .ToDictionary(t => t, t => t.GetCustomAttribute<ComponentAttribute>());
         
foreach (var component in components)
{
  Type componentType = component.Key;               
  ComponentAttribute ca = component.Value;
  // call(s) to AddService on serviceCollection
}
```

**Comment by davidfowl** [comment]
Related to https://github.com/aspnet/Extensions/issues/690. Personally, I don't think scanning should be built in. I think it can be an optional feature of the DI container. I would suggest using something like [Scrutor](https://github.com/khellang/Scrutor) which has an extremely expressive way to scan for various types of components.

**Comment by ah1508** [comment]
I think scanning without custom attributes creates a mess. When you look at the service class you cannot know if it will be scanned or not. Using a marker type (like `ITransientService`) is a no go, we want to keep POCO classes and marker type don't allow to add metadata (VisibleAsSelf and VisibleAs in my suggestion).

Custom attributes would bring clarity and simplicity. Framework like Spring in Java or even Java EE CDI spec are miles ahead asp.net di and both have offered custom attributes (annotations in Java) for 10 years. I think that new .net core technologies should look at successful java frameworks and get inspiration from them.

It also open the way to new features (eager loading, conditional registration based on the environment, etc...) with only additional properties on the custom attribute. Manual registration gives the feeling that we do imperative programming for something the framework could guess by itself. The code to implement a generic `Scan` method based on custom attribute would be shorter than the boilerplate code required to register types on by one.

**Comment by davidfowl** [comment]
It’s also makes it hard to understand ordering which is important for overriding services and IEnumerable support. It also makes it extremely hard to build modular systems if the gesture to scan is implicit. That’s why if we add these attributes, scanning would be an explicit call (like scruple does)

**Comment by davidfowl** [comment]
Ah I also like to add that discovery at build time would be preferable to runtime discovery. The performance hit at startup time is non trivial which is a killer for things like azure functions and was lambda

**Comment by muratg** [comment]
I don't expect we'll be implementing this.
