### ISSUE TITLE
Organize localization repo

### ISSUE THREAD

**Issue by hishamco** [aspnet/Extensions#681]
@natemcmaster seems after you migrate the localization repo the new folder structure had been modified, I suggest the following structure:
```
Localization
      |- Localization.Abstractions
      |- Localization.Routing
      |- Localization
      |- samples
            |- LocalizationSample
      |- test
            |- LocalizationWebsite
            |- Microsoft.AspNetCore.Localization.FunctionalTests
            |- Microsoft.AspNetCore.Localization.Routing.Tests
            |- Microsoft.AspNetCore.Localization.Tests
            |- Microsoft.Extensions.Localization.Tests
            |- ResourcesClassLibraryNoAttribute
            |- ResourcesClassLibraryWithAttribute
```
If you happy with that, I can send a PR for that

**Comment by natemcmaster** [comment]
AspNetCore localization is here: 
* https://github.com/aspnet/AspNetCore/tree/master/src/Middleware/Localization
* https://github.com/aspnet/AspNetCore/tree/master/src/Middleware/Localization.Routing

This is not something I would take a PR to change. We're intentionally trying to keep this repo decoupled from aspnetcore.

**Comment by hishamco** [comment]
I'm not sure what's the different between them, second thing the structure I suggest was in the old repo, also the logging repo has similar one
