### ISSUE TITLE
Dependency Injection for Web Forms support.

### ISSUE THREAD

**Issue by TheJayMann** [aspnet/Extensions#687]
I'm not sure where I should start this discussion, but this appears to be the best place I can find.  I have recently created support for being able to use the Microsoft.Extensions.DependencyInjection ([aspnet/DependencyInjection](https://github.com/aspnet/dependencyinjection)) in a ASP.NET Web Forms project using the new HttpRuntime.WebObjectActivator property.  I have it hosted at [TheJayMann/WebFormsDi](https://github.com/TheJaymann/WebFormsDi), and I was hoping that the aspnet organization could take the project itself, either by taking the repository itself, or merging it into the [aspnet/DependencyInjection](https://github.com/aspnet/dependencyinjection) repository.

**Comment by Jehoel** [comment]
@Eilon This is something I'm interested in. What would be the process for forking @TheJayMann's work and adding it to aspnet-contrib?

I've already made my own WebObjectActivator DI for WebForms using Unity at https://github.com/Jehoel/Unity.WebForms but I recently wanted to update it to use `Microsoft.Extensions.DependencyInjection` instead (so I can use `Microsoft.Extensions.Logging` in my existing WebForms projects without making my own logging library from scratch). While googling to see if anyone has already ported MEDI to WebForms I saw this GitHub issue.

I have some ideas for improvements to @TheJayMann's repo based on my experiences with my `Unity.WebForms` library - such as providing an `IHttpContextAccessor` to allow services to get a safe `HttpContextBase` instance reference without using the concurrency-unsafe static `HttpContext.Current` property, and abstractions of `WebConfigurationManager` with support for dictionary-based configuration elements (though perhaps that's better done by extending `Microsoft.Extensions.Configuration` in a separate package).

**Comment by TheJayMann** [comment]
@Jehoel  From my side of things, if you want to make improvements to my repository, you could create a pull request and, if it looks good, I can accept it.  If, instead, you wish to take the project yourself, I would be fine with that, though I'm not sure what I would have to do to transfer the nuget access to you.

If you are looking to do the work to get the code put in to aspnet-contrib, I should be able to assist you with whatever you would need from me.

**Comment by Jehoel** [comment]
@TheJayMann I'll make a PR within the next few days.

**Comment by Jehoel** [comment]
@TheJayMann I toyed around with your fork but instead I ended up making modifications to my existing project to work with `Microsoft.Extensions.DependencyInjection` - as I saw that I'd only end-up bringing-over most of my code into your project and losing my git history.

My project is now located at https://github.com/Jehoel/AspNetDependencyInjection and is published to NuGet at https://www.nuget.org/packages/Jehoel.AspNetDependencyInjection/3.0.0 

As said before, I'm happy to let this become part of aspnet-contrib - just let me know what I need to do.

**Comment by TheJayMann** [comment]
Taking a look at what you have done, it appears to be better built than what I have, thus, I've archived my repository in favor of yours.

One thing that I would want which your project won't appear to implement is a way to also have it working with MVC for some of the projects we have which mix WebForms with MVC; however, it doesn't appear that it would be difficult to implement separately and on top of what you have done.

**Comment by Jehoel** [comment]
@TheJayMann 

> Taking a look at what you have done, it appears to be better built than what I have, thus, I've archived my repository in favor of yours.

Okay, **that's** flattery 😻

> One thing that I would want which your project won't appear to implement is a way to also have it working with MVC for some of the projects we have which mix WebForms with MVC

I think it's straightforward. I'm looking at Unity's example for ASP.NET MVC ( https://github.com/unitycontainer/aspnet-mvc/tree/master/src ) and it looks like only this needs to be done:

* Implement `Ssytem.Web.Mvc.IDependencyResolver` or subclass `IControllerFactory`.
* Register it with `DependencyResolver.SetResolver(new MyDependencyResolver(...));`
* er... that's it.

The rest of the code in that project seems pertinant to Unity's `BuildUp` ("property injection" assignment) logic which MEDI doesn't support anyway.

I'll see if I can do that right now, actually. I'll report back in a few hours.

**Comment by Jehoel** [comment]
@TheJayMann I've now implemented support for ASP.NET MVC - **though it is untested**.

https://github.com/Jehoel/AspNetDependencyInjection/tree/master/AspNetDependencyInjection.Mvc

The NuGet package is available here: https://www.nuget.org/packages/Jehoel.AspNetDependencyInjection.Mvc

Please let me know if it works for you - or if there are any problems.
