### ISSUE TITLE
How to register/inject multiple implementations of a same interface? 

### ISSUE THREAD

**Issue by broomandan** [aspnet/Extensions#688]
Hi,
Is there a simple way (like Simple Injector) to register multiple implementations for an interface and inject an specific implementation into a consumer?
I have two access layer components that are using two different NHibernate session factories. I want to be able to instruct the DI resolver, when component A is asking for IService inject implementation A of IService and when component B is asking for IService, inject implementation B of IService.
I could contribute to this repo if this is not available. 
Best,
Robert Broomandan

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
