### ISSUE TITLE
DependencyInjection Add Lifetime Attribute

### ISSUE THREAD

**Issue by benaadams** [aspnet/Extensions#690]
To prevent the service being registered as the with the wrong lifetime (Scoped registered as Singleton); or being used for the wrong lifetime (Scoped used in Middleware constructor rather than Invoke method)

e.g.
```csharp
[LifeTime(DependencyInjection.Singleton)]
public class MyHttpClient : IHttpClient
{

}

[LifeTime(DependencyInjection.Scoped)]
public class MyUser : IUser
{

}

[LifeTime(DependencyInjection.Transient)]
public class MyGuid : IGuid
{

}
```

Obviously; would also need checks the level when the DI container is built; and when pipeline is built to enforce the constraints (and throw)

**Comment by muratg** [comment]
@pakrym closing this. Please bring back if there's any more changes can realistically go in 3.0.0.
