### ISSUE TITLE
What is the design of the extension method of the IDistributedCache interface?

### ISSUE THREAD

**Issue by hjkl950217** [aspnet/Extensions#700]
hi Developers,

Our team needs to use redis,we want to have a method like `Get<T>(string key)`。There are two kinds of get and set.

but,After I wrapped this method, I found that: Unable to simulate return value in UT for “`Get<T>(string key)`”。In other words: `GetSting method` for `public static class DistributedCacheExtensions`, Business code use it,How to mock data the return value?

Question:Which method should I use?
1.Use interface inherit interface.Use a new interface to wrap “IDistributedCache ”，we use new interface。 （But this does not seem to be in line with "standards oriented"）
2.Ways to continue using the extension method.（But this will make the code using these methods difficult UT）

The serializer uses messagePack, and I did an extension design, and I can replace the serializer at the method level later.

Our code does not distinguish redis or other。only for IDistributedCache

**Comment by muriloMmtools** [comment]
Hi guys,

How can I do mock methods from DistributedCacheExtensions, like GetStringAsync or SetStringAsync? Is it possible do unit test using those methods directly, because I'm not using some custom method for this class?
