### ISSUE TITLE
Azure functions .net core 2.  Usage of rediscache in azure functions with consumption plan

### ISSUE THREAD

**Issue by krishnasingh1818** [aspnet/Extensions#702]
Am reading people having trouble with using rediscache in azure functions on consumption plan.  

please advise best practice for using caching in azure functions 2.0

my rediscache will be used by api's as well as azure functions.  since connection object is supposed to be singleton and reused in case of functions on every request it will create new connection will this create problems ?

**Comment by anurse** [comment]
We don't have any best practices, but it should work fine.
