### ISSUE TITLE
Cannot restore nuget package from nuget

### ISSUE THREAD

**Issue by xyz0822** [aspnet/Extensions#704]
System：windows 10 1809
Visual Studio: 15.8.7

after i downloaded source code from github with the releases 2.1.2，I can not restore nuget package like Microsoft .NETCore.App (2.1.2) or any other like internal.AspNetCore.Sdk(2.1.3-rtm-15802) ,NETStandard.Libary(2.0.3) and so on from the nuget,so failed to debug source code,i dont know why?

**Comment by pranavkm** [comment]
Looks like the question was answered. Closing since there's nothing further to do here.
