### ISSUE TITLE
Flaky Test: AddingReplacementWhenTotalSizeExceedsCapacityDoesNotUpdateRemovesOldEntryAndTriggersCompaction

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/Extensions#705]
On Travis https://travis-ci.org/aspnet/Caching/jobs/438771122
`Microsoft.Extensions.Caching.Memory.CapacityTests.AddingReplacementWhenTotalSizeExceedsCapacityDoesNotUpdateRemovesOldEntryAndTriggersCompaction()`

**Comment by anurse** [comment]
Travis be ded.
