### ISSUE TITLE
RedisTimeoutException in synchronous GetString

### ISSUE THREAD

**Issue by SWarnberg** [aspnet/Extensions#712]
It seems like there is an issue with the synchronous extension method **GetString**. When using it, I get a lot of **RedisTimeoutException** exceptions. The problem is that it's returned after 2ms and not 1s, which is the default timeout. Changing the connection string to "synctimeout=2000,localhost:32768" has no effect,
When changing the code to use the async method **GetStringAsync**, the exceptions doesn't happen anymore.
Hence, changing this:
```
string json = cache.GetString($"{typeof(T).Name}_{key}");
```
to this:
```
var t = Task.Run(async () => await cache.GetStringAsync($"{typeof(T).Name}_{key}"));
t.Wait();
string json = t.Result;
```
works.

**Comment by anurse** [comment]
Closing as this issue has gotten stale. If you are still having this problem, please let us know and we can re-open it and investigate further!
