### ISSUE TITLE
Using TransactionScope with SqlServerCache

### ISSUE THREAD

**Issue by Swellenator** [aspnet/Extensions#713]
I am getting these errors:

    System.Transactions.TransactionManagerCommunicationException: Network access for Distributed 
    Transaction Manager (MSDTC) has been disabled. Please enable DTC for network access in the security 
    configuration for MSDTC using the Component Services Administrative tool. 

That is because we don't want to use DTC. We have integration tests that have a TransactionScope so that you can roll back any changes made during the test. Our main code uses EF. However because SqlServerCache starts it's own different connection I'm assuming there is a conflict.

In another part of our code where we do use ADO.Net we have the following:

    using (var conn = new SqlConnection(ConfigurationSettingsDbConnection))
    using (new TransactionScope(TransactionScopeOption.Suppress, 
    TransactionScopeAsyncFlowOption.Enabled))
            {
            }

Is there any way around this issue, to modify the transaction that SqlServerCache uses? Maybe a parameter for some TransactionScopeOption? Otherwise I'll have to make a fork or similar and add it myself. 

Cheers

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
