### ISSUE TITLE
If I want to get string-type values from redis, do I need to expand by myself? I only see the hashmember method.

### ISSUE THREAD

**Issue by s952787097** [aspnet/Extensions#754]
If I want to get string-type values from redis, do I need to expand by myself? I only see the hashmember method.

**Comment by anurse** [comment]
The distributed cache returns `byte[]`, and they're intended to be UTF-8-encoded when you are storing strings. You can decode them using `System.Text.Encoding.UTF8.GetString`. Or you can use the `GetString`/`SetString` extension methods to do this for you.
