### ISSUE TITLE
Feature Request: Configuration extension that reads from app services environment variables via AzureRM

### ISSUE THREAD

**Issue by zippy1981** [aspnet/Extensions#772]
So here is the idea, lets say I want to run a local version of my app in visual studio, but configured exactly like it is on an app service.  I could pull that configuration from AzureRM with 

https://resources.azure.com/subscriptions/__SUBSCRIPTION_ID__/resourceGroups/__RESOURCE_GROUP_NAME__/providers/Microsoft.Web/sites/__APP_SERVICE_NAME__/config/appsettings/list and https://resources.azure.com/subscriptions/__SUBSCRIPTION_ID__/resourceGroups/__RESOURCE_GROUP_NAME__/providers/Microsoft.Web/sites/__APP_SERVICE_NAME__/config/connectionstrings/list

Now I could save that to a file, or write some powershell to parse that and set environment variables, but it would b real nice just to be able to have an extension method that would pull down the json and load it in for me.

I'm not sure if including HttpClient as a dependency here would be a deal breaker, so maybe this needs to become its own assembly.

At the very least a good first step would be to make changes to `Configuration.Json` to allow it to accept streams as well as files.

**Comment by ajcvickers** [comment]
Thanks for the suggestion, but this is not something we plan to implement.
