### ISSUE TITLE
ConfigurationBinder: Support [Key] attribute

### ISSUE THREAD

**Issue by stiano** [aspnet/Extensions#773]
The ConfigurationBinder should look for the KeyAttribute (or similar) on all the properties it aims to bind, and fallback to the current solution. We have legacy configuration files with long names not suited for property names.

`public class MyOptions
{
        [Key("C_CONFIG_SYSTEM_NET_MAILSETTINGS_SMTP_NETWORK_HOST_INTERNAL")]
        public string SmtpHost { get; set; }
}`

**Comment by ajcvickers** [comment]
This is not something we plan to implement. The configuration binder is intentionally simplistic. Custom binding to options can always be used instead.
