### ISSUE TITLE
UserSecrets gets odd path for secrets file under 4.7.1 in Windows

### ISSUE THREAD

**Issue by simonmurdock** [aspnet/Extensions#774]
### Functional impact
This results in the app never finding the secrets file

### Minimal repro steps
- Create a new "ASP.NET Web Application (.NET Framework)
- Choose "MVC" as the template, default settings
- Add nuget ref to "Microsoft.Configuration.ConfigurationBuilders.UserSecrets"
- update web.config so appsettings appears like this:
```csharp
 <appSettings configBuilders="Secrets">
```

### Expected result
The app to load and merge the settings in the secrets.xml file with my appsettings

### Actual result
Running the app results in it trying to read the secrets file from this location: `e:\repro\repro\repro\bin\Microsoft.Configuration.ConfigurationBuilders.UserSecrets.DLL.UserSecretsId.txt`
![image](https://user-images.githubusercontent.com/5403478/41242085-8faa5384-6d96-11e8-8a34-fba28c973ec1.png)

### Further technical details
It also does this in my main solution, I checked the code for https://github.com/aspnet/Configuration/blob/dev/src/Config.UserSecrets/PathHelper.cs and have no clue how it is resulting this path.
The EnvironmentConfigBuilder works fine, if that's any help.

I'm using this https://docs.microsoft.com/en-us/azure/key-vault/vs-secure-secret-appsettings#aspnet-and-net-applications and the secretsFile attribute also seems to have no effect. It's also not clear if the file should be json or xml.

### Resolution
It seems that specifying UserSecretsId as a folder name to nest my secrets.xml and adding dummy values into the appsettings fixed it.

**Comment by RoLYroLLs** [comment]
@simonmurdock I'm running into the same issue. I'm trying to understand how you fixed it exactly. Are you saying you added a folder named `UserSecretsId` to the solution and moved the `secret.xml` file in that folder and that's it?

**Comment by simonmurdock** [comment]
sorry @RoLYroLLs I've since switched to a newer version of .net core, and not run into any issues again

**Comment by simonmurdock** [comment]
I recall now - <user_secrets_id> is the folder name which needs to exist inside the  normal user secrets ID, once that was specified, it was ok
