### ISSUE TITLE
Add Ability to Validate Configuration

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/Extensions#777]
The configuration providers currently don't provide a way to validate that what is loaded is valid. ASP.NET Core is perfectly happy to start an app with a null connection string for example. @andrewlock has written a wonderful [blog post](https://andrewlock.net/adding-validation-to-strongly-typed-configuration-objects-in-asp-net-core/) showing how to add validation.

## Example Usage Using Attributes

This style matches very well with standard view model validation.

```
public class SlackApiSettings
{
    [Required, Url]
    public string WebhookUrl { get; set; }

    [Required]
    public string DisplayName { get; set; }
}
```

## Example Usage Using a Method

This is equivelant to what something like FluentValidation would do.

```
public class SlackApiSettings : IValidatable  
{
    public string WebhookUrl { get; set; }
    public string DisplayName { get; set; }
    public bool ShouldNotify { get; set; }

    public void Validate()
    {
        if (string.IsNullOrEmpty(WebhookUrl))
        {
            throw new Exception("SlackApiSettings.WebhookUrl must not be null or empty");
        }

        if (string.IsNullOrEmpty(DisplayName))
        {
            throw new Exception("SlackApiSettings.WebhookUrl must not be null or empty");
        }

        // throws a UriFormatException if not a valid URL
        var uri = new Uri(WebhookUrl);
    }
}
```

**Comment by ajcvickers** [comment]
We have implemented validation at the options level; we have no plans to implement at the config level.
