### ISSUE TITLE
Hosting design inconsistencies and lifetime confusion

### ISSUE THREAD

**Issue by maelgrove** [aspnet/Extensions#807]
**Edit**
Clarification, removal of misguiding issue references etc.

----

The current designs of the web- as well as the generic hosting infrastructure have several inconsistencies or misleading APIs which require awareness of the internal implementation details to fully understand their effect and behavior. This is especially problematic since the infrastructure is built around an entire DI abstraction, with endpoints like 'ConfigureServices' that give away the impression every part can be replaced (which is in fact, not true).

With the current design, I see the following problems:

### *Start* / *Stop* on `IHost`

The current `IHost` contract offers a *Start* and *Stop* method. This gives away the impression that the host can be started and stopped as many times as desired (essentially restarted), as long as it hasn't been disposed. However, the internal `IApplicationLifetime` is only resolved once, meaning that if the host is re-started, any subscribers which have startup/shutdown logic won't be called.

### 'IHostLifetime'

The purpose of the `IHostLifetime` is not really obvious. Since there is only a single `IHostLifetime` available, one might think the `IHostLifetime` abstracts the hosting environment (e.g. a console, a Windows Service). So with that in mind, I would expect them to be blocking. However all the implementations do is wire themselves up to some lifetime hooks, for telling the application what to do when it starts, and to listen for certain exit events (SIGTERM, process exit..), which can basically be done by any service that gets `IApplicationLifetime` injected. What's the point of this then?

#### Proposal

Either a) get rid of the `IHostLifetime` contract entirely. Instead, let the `HostBuilder` create a single, shared instance of `ApplicationLifetime` by itself, and offer a method to configure the lifetime. (Possibly even hooking the callbacks up into a delegate factory of the `IServiceCollection`, so that they can be configured with the awareness of an existing `IServiceProvider`.)

    IHostBuilder ConfigureLifetime(Action<HostBuilderContext, IApplicationLifetime> callback)

... or b) get rid of them and instead introduce a `IHostInitializer`, as proposed by #1401.

### `IApplicationLifetime` casting

Another problem with the `IApplicationLifetime` is the cast to `ApplicationLifetime` within the `Host` implementation. Since `IApplicationLifetime` is registered within the DI, one might expect this to be exchangeable too. However this is not the case since with any other implementation, the cancellation hooks never get triggered, which might prevent the application from properly start/stop.

#### Proposal

Don't rely on a concrete application lifetime within the `Host`. Instead, move e.g. the startup of the application services (`IHostedService`) into the application lifetime implementation (e.g. HostedServiceApplicationLifetime), so it knows when to call the tokens by itself. That way, the `IHostedService` concept would be a feature of a certain lifetime implementation.

### Consistency in service lifetimes (resolving `IHost`)

The current `IHost` contract implements `IDisposable`. In the default implementation (`Host`), the host gets a `IServiceProvider` injected (which might be the main DI container), and disposes it upon calling `Dispose` (given the current `IServiceProvider` implementation supports `IDisposable`). What's very problematic about this is, is that the `Host` itself is being registered within the DI container and resolved from there. Most application containers have the feature of disposing all registered components when they are being disposed themselves. So what exactly is expected to happen here? Host disposes container, container disposes host upon disposal? The lifetimes are not really consistent.

#### Proposal

Don't register the `IHost` within the `IServiceCollection`. Create it manually via the `HostBuilder`, and pass along an instance of the `IServiceProvider` for further resolving host lifetimes or the like. Dispose the `IServiceProvider` afterwards when disposing the `IHost`. That way, it's obvious what implementation is responsible for managing what lifetime.

I know this issue is kinda broad, so I guess it's best labeled as discussion topic.

**Comment by muratg** [comment]
We won't be making changes here.
