### ISSUE TITLE
Deadlock when using Autofac and the ConsoleLifetime on exit

### ISSUE THREAD

**Issue by abe545** [aspnet/Extensions#808]
I'm trying to use `Autofac` as my service provider in a console application. Here is a minimal program to repro this:

```cs
using System.Threading.Tasks;
using Autofac.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

public class Program
{
    public static async Task Main(string[] args) => await new HostBuilder()
        .UseServiceProviderFactory(new AutofacServiceProviderFactory())
        .RunConsoleAsync();
}
````

It is causing a deadlock because their provider doesn't implement `IDisposable`. Unfortunately, the `ConsoleLifetime` locks until it is disposed, and this only happens if:
1. The `IServiceProvider` implements `IDisposable`
1. The `IServiceProvider` disposes all `IDisposable` instances it creates

`Autofac` opted not to implement `IDisposable` in the past because `if the service provider is supposed to be disposed, they should have put IDisposable on it` (from https://github.com/autofac/Autofac.Extensions.DependencyInjection/issues/3#issuecomment-242068640). I've opened a new issue where I hope they'll implement it (or allow me to), but I imagine this will be an issue for other DI containers.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
