### ISSUE TITLE
Add TimerHostedService base class

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Extensions#812]
This would have all of the boilerplate code for running an asynchronous operation on an interval. It would also be implemented using a single repeating timer instead of using Task.Delay (which creates a timer per operation). We would automatically handle overlapping calls to the Tick callback (something people have to deal with today) and disposing the timer when the application shuts down.

I have a prototype I'll send for PR

cc @glennc @Tratcher

**Comment by muratg** [comment]
@davidfowl please reopen if you actually have a PR.
