### ISSUE TITLE
Inconsistent behaviour between GetFileInfo & Watch

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Extensions#820]
_From @ycrumeyrolle on Friday, November 25, 2016 2:09:03 AM_

Take the following code : 
```
        ChangeToken.OnChange(() => _fileProvider.Watch(@".\test.txt"), FileChanged);

        private void FileChanged()
        {
            var file = _fileProvider.GetFileInfo(@".\test.txt");
            _fileExists = file != null && file.Exists;
        }
```
Tried with a PhysicalFileProvider. 
If I call the `FileChanged()` method directly, the file provider is functioning properly and providing information on the file. 
If I change the file, the change is not watched and the ChangeToken does not trigger.

If I update the code by removing the trailing `.\`, the ChangeToken is also functioning properly : 
```
        ChangeToken.OnChange(() => _fileProvider.Watch("test.txt"), FileChanged);

        private void FileChanged()
        {
            var file = _fileProvider.GetFileInfo("test.txt");
            _fileExists = file != null && file.Exists;
        }
```

The GetFileInfo do not consider the trailing `.\` as invalid characters, but the Watch does.

_Copied from original issue: aspnet/FileSystem#248_

**Comment by muratg** [comment]
I don't expect we'll be making changes here.
