### ISSUE TITLE
PhysicalPath for EmbeddedResourceFileSystem is null

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/Extensions#840]
_From @pranavkm on Wednesday, December 3, 2014 9:24:00 AM_

I can sort of see why `PhysicalPath` is [null](https://github.com/aspnet/FileSystem/blob/dev/src/Microsoft.AspNet.FileSystems/EmbeddedResourceFileSystem.cs#L159-L162) for an EmbeddedResource, but it would be useful for a way to get to the [`Path`](https://github.com/aspnet/FileSystem/blob/dev/src/Microsoft.AspNet.FileSystems/EmbeddedResourceFileSystem.cs#L134) of a `IFileInfo` without it being tied to a `PhysicalFileSystem`.

Suggestion
- Add a `Path` property to `IFileInfo` that is guaranteed to be not null.
- The value of the `Path` property is the same as `PhysicalPath` for `IFileInfo` returned from `PhysicalFileSystem`.
- Have it be set to _resourcePath in `EmbeddedResourceFileSystem`

_Copied from original issue: aspnet/FileSystem#23_

**Comment by pranavkm** [comment]
The property on the interface has been around for fairly long enough and most consumers of the API have tip-toed around it's nullability. Making a breaking change to the interface doesn't seem like worth the effort at this stage. I'm going to close this issue. I'd be happy to reconsider if there is a strong argument to reopening it.
