### ISSUE TITLE
No lifetime validation when consuming transient services in singletons

### ISSUE THREAD

**Issue by henkmollema** [aspnet/Extensions#850]
The default dependency injection container offers validation to guard against consuming scoped services in singleton services. However, this validation is not executed for transient services where this problem is also applicable.

### To Reproduce
1. Using ASP.NET Core 2.1.5
2. Create singleton service `FooService`
3. Create transient service `BarService`
4. `BarService` gets injected but is turned into a singleton because `FooService` is singleton

A gist for completeness: https://gist.github.com/henkmollema/1d75be0116fb8da80fded14dbebe81eb

### Expected behavior
A similar exception when `BarService` would be a scoped service:

> InvalidOperationException: Cannot consume scoped service `BarService` from singleton `FooService`.

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
