### ISSUE TITLE
Microsoft.Extensions.HealthChecks.AzureStorage

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Extensions#859]
The Microsoft.Extensions.HealthChecks.AzureStorage package should allow development using the local storage emulator and/or azure stack and not assume that the health check is to be performed on the cloud.

**Comment by rynowak** [comment]
@grahamehorner -  unfortunately, I don't think package is ours. 

/cc @Eilon @glennc

**Comment by Eilon** [comment]
Yeah it's just some random person's random package that got it in before we had the Microsoft.* namespace reserved. Unless it's a malicious package or there's a serious problem with it there's not much we do about these.
