### ISSUE TITLE
EventSourceLoggerProvider allocates *ALOT*

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Extensions#864]
Looking at some 3.0 memory profiles, it seems as though the event source logger we added by default in 2.2 increases the amount of pressure we put on the GC.

This application made ~67000 requests:

These are the top per request allocations (by size):

![image](https://user-images.githubusercontent.com/95136/50370796-2c51c100-0562-11e9-9869-c3830c484ac9.png)

The boxed `Int32`, the `Object[]`, the `KeyValuePair<string, string>[]`, the `List<KeyValuePair<string, string>>` the `EventSource.EventSourceLogger+ActivityScope` all come from the EventSourceLogger and the LoggingEventSource.

Here a view from the allocation callsites:

![image](https://user-images.githubusercontent.com/95136/50370853-2c05f580-0563-11e9-8378-a81c203d4cb8.png)
![image](https://user-images.githubusercontent.com/95136/50370857-45a73d00-0563-11e9-8ce9-fee6adf66abf.png)

We need to investigate this and avoid this many allocations.

cc: @pakrym

**Comment by pakrym** [comment]
I've improved no-op logging \*ALOT\* and improved subscriber case. A lot of allocations are internal to EventSource.
