### ISSUE TITLE
Validate the dependency graph

### ISSUE THREAD

**Issue by ilya-chumakov** [aspnet/Extensions#865]
Is it possible to check if all the services registered in `ConfigureServices(IServiceCollection services)` can be resolved? 

By default, we get a runtime error if the DI container can't resolve a class because of a missing dependency. I'd like to avoid such situations if possible and write an integration test checking the DI or at least see a warning in logs during the application startup if something is missing.

 3rd party DI containers have this feature. For example, there is `container.AssertConfigurationIsValid();` in [StructureMap](http://structuremap.github.io/diagnostics/validating-container-configuration/).

**Comment by davidfowl** [comment]
We added this feature in 3.0 https://github.com/aspnet/AspNetCore/issues/2348. It’s a Boolean setting called ValidateOnBuild.

**Comment by ilya-chumakov** [comment]
@davidfowl thank you! Can't wait for the stable 3.0 release.
