### ISSUE TITLE
allows the developers to interfere with the resolving

### ISSUE THREAD

**Issue by raochunjiang** [aspnet/Extensions#866]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is.
Example. I'm am trying to do [...] but [...]

**Comment by raochunjiang** [comment]
If we can replace another instance to a real instance after resolving,we can easily get an AOP module by a proxy tool, for example, the `DispatchProxy`.
I suggest that you can add some events to your implementations before or after resolving the services.
Maybe my idea is not worth,and please tell me how can i intercept an instance from MSDI easily,without the third-part framework.
by the way,while my English is soso,I'm still waiting for your reply

**Comment by raochunjiang** [comment]
If we can replace another instance to a real instance after resolving,we can easily get an AOP module by a proxy tool, for example, the DispatchProxy.
I suggest that you can add some events to your implementations before or after resolving the services.
Maybe my idea is not worth,and please tell me how can i intercept an instance from MSDI easily,without the third-part framework.
by the way,while my English is soso,I'm still waiting for your reply

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
