### ISSUE TITLE
Add extension method to `IHostBuilder` to set the application name (key)

### ISSUE THREAD

**Issue by kiapanahi** [aspnet/Extensions#873]
It would be nice to have an extension method for `IHostBuilder` for setting the application name value just like the existing methods for setting the environment or content root. At the moment the imperative way of doing this is not as easy and requires a little digging (unless someone decides to use the `applicationName` configuration key)

The proposed solution would offer the developer with something like:
```csharp
var host = new HostBuilder()
    .UseApplicationName("application-name")
    // ... other configs
```

Currently, I have found 3 other ways of doing this. One is using the `applicationName` config file.
The other two are as follows:

- using the `ConfigureAppConfiguration` method:
```csharp
var host = new HostBuilder()
    .ConfigureAppConfiguration((hostContext, appBuilder) =>
    {
        hostContext.HostingEnvironment.ApplicationName = "application-name";
    })
```

- using the `ConfigureHostConfiguration` method:
```csharp
var host = new HostBuilder()
    .ConfigureHostConfiguration(builder =>
    {
        builder.Add(new MemoryConfigurationSource
        {
            InitialData = new[]
            {
                new KeyValuePair<string, string>(HostDefaults.ApplicationKey, "my-app-name")
            }
        });
        builder.SetBasePath(Directory.GetCurrentDirectory());
        builder.AddJsonFile("hostsettings.json", true, true);
        builder.AddCommandLine(args);
    })
```

**Comment by anurse** [comment]
We really want to avoid overloading the list of methods hanging off of `IHostBuilder`. The mechanism you described using `ConfigureAppConfiguration` is our intended way of doing this right now.
