### ISSUE TITLE
Add a way to disable/ignore particular health checks

### ISSUE THREAD

**Issue by zihotki** [aspnet/Extensions#875]
I have some external services used by an app and the services can be reconfigured (enabled or disabled) at runtime. For those services we have implemented health checks but the problem is that health checks are configured at startup and there is no easy way to exclude disabled services from the health report.

So far I see the following possibilities to achieve desired result.
1. Either add additional `Disabled` status to `HealthStatus` enum 
2. Allow a health check to return null and ignore it inside `DefaultHealthCheckService` (but since `HealthReportEntry` is a structure it may be hard)
3. Provide an additional Predicate in `HealthCheckOptions` to filter-out instances of disabled health checks

**Comment by glennc** [comment]
Can't you use the predicate that can be passed into CheckHealth? Presumably you need to check against some external list of enabled/disabled services and you can match them there.

**Comment by rynowak** [comment]
@zihotki I'm closing this because we haven't heard back from you. You can provide a predicate to `HealthCheckService` and the middleware that filters the set of checks. It's unclear to me why we would need another feature to do what you need.

**Comment by zihotki** [comment]
Sorry for delay with response.

@rynowak For an example consider the following health check:
```
    public class RedisHealthCheck : IHealthCheck
    {
        private readonly RedisCacheOptions _options;

        public RedisHealthCheck(IOptions<RedisCacheOptions> options)
        {
            _options = options.Value;
        }
        public async Task<HealthCheckResult> CheckHealthAsync(...)
        {
...
        }
```
It's using options for passing in configuration values which are injected into constructor. I would like to implement a check which will use provided options to determine whether the service is configured or not. If it's not configured I want to ignore the health check.

Predicate unfortunately is not suitable for particular scenario because predicate doesn't have access to the scope and service provider. You can only check there only the registration and can't check instantiated health check service.

Another good candidate was to extend `HealthCheckRegistration` and do the check inside of registration's factory. But unfortunately current implementation will throw null reference exception if factory returns null.

So far I don't see any way of implementing the desired behavior.
