### ISSUE TITLE
Obsolete and remove usages of InplaceStringBuilder

### ISSUE THREAD

**Issue by pakrym** [aspnet/Extensions#877]
Now that we have `string.Create` that is safer and does the same thing.

**Comment by davidfowl** [comment]
I don't think we should do this yet. It's not a good replacement. We need better formatting APIs before we deprecate. string.Create alone isn't a good replacement. This also works on .NET Standard 2.0. Specifying a replacement that only works on .NET Core isn't the right thing to do.

That said, I do want to throw this type away but we need a good replacement for it.

**Comment by pakrym** [comment]
I buy .NET Standard 2.0 argument but not the ease of use one. InplaceStringBuilder usage is trivially convertible to `string.Create` because it forced a very use specific pattern.

We can obsolete the type only in netcoreapp target.
