### ISSUE TITLE
Perf: AzureKeyVaultConfigurationProvider loads secrets one by one

### ISSUE THREAD

**Issue by farazkamal** [aspnet/Extensions#910]
### Describe the bug
AzureKeyVaultConfigurationProvider loads secrets one by one, leading to significant slowness during startup of apps with several secrets.

### To Reproduce
1. Configure a .NET core web app to use the "AddAzureKeyVault" extension.
2. Start up the app with Fiddler (or similar tool) open.
3. Watch the requests go out to kevault one at a time without any parallelization.

### Expected behavior
AzureKeyVaultConfigurationProvider should have at least some degree of parallelism to speed up loading several secrets.

### Screenshots
N/A

### Additional context
The bug would appear to be on this line:
https://github.com/aspnet/Extensions/blob/5054f8a0e544b3f9e670808fd0f581d8ea03bc5f/src/Configuration/Config.AzureKeyVault/src/AzureKeyVaultConfigurationProvider.cs#L62
It has an await in a foreach loop.

**Comment by ajcvickers** [comment]
@farazkamal What numbers are you seeing?

**Comment by farazkamal** [comment]
About 20 seconds with 79 secrets. We have a large app with a lot of keys for app insights, redis etc.

**Comment by ajcvickers** [comment]
@davidfowl @HaoK @natemcmaster Thoughts? This seems pretty slow, but I don't know what the options are when it comes to loading multiple at the same time.

**Comment by natemcmaster** [comment]
@pakrym may be able to answer better. I haven't worked on this provider.

**Comment by pakrym** [comment]
I think we can parallelize `GetSecretAsync` calls just fine, they are all backed by HttpClient requests and paging nature of `GetSecretsAsync` should save us from running too many all at once.
