### ISSUE TITLE
(Microsoft.Extensions.Logging) Capturing objects 

### ISSUE THREAD

**Issue by eaidland** [aspnet/Extensions#934]
Hi!

This is both a question and feature request for the Microsoft.Extensions.Logging:

As of now is it possible to log class objects like Serilog do where the they serilize the data?

Serilog:
Log.Debug("Received {@Request}", request);
    // -> Received PublishRequest { PageId: "widget-2000", PublishAt: 08/31/2016 00:45:59 }

MS Logger:
// -> Received PublishRequest Models.PublishRequest 

Thanks

**Comment by poke** [comment]
M.E.Logging does support structured logging, so you can totally do this:

```
logger.LogInformation("Received {Request}", request);
```

By default, it will call `request.ToString()` to create a string representation that can be logged into string based logging targets. Targets that do support structured logging can also access the request object itself. You could use for example Serilog or Seq for that.

If you don’t care about using structured logging providers, you can also just implement `ToString` for your custom object to allow it to be serialized more nicely in string based loggers.

**Comment by anurse** [comment]
Closing, as the question has been answered (thanks @poke!). Feel free to comment further if you need us to elaborate on the answer!
