### ISSUE TITLE
MemoryCacheEntryOptions RegisterPostEvictionCallback executes before cache expiration

### ISSUE THREAD

**Issue by kshyju** [aspnet/Extensions#950]
I am trying to use IMemoryCache with `RegisterPostEvictionCallback` and running into some behavior which I am not quite sure is the expected.

Here is the relevant methods. The `GetQuote` will be an HTTP Get call coming from clients.

    public async Task<string> GetQuote()
    {
        if (_cache.TryGetValue(CacheKey, out DateTime cacheEntry))
        {
            logger.LogWarning("Cache has value:" + cacheEntry.ToString());
            return cacheEntry.ToString() + " - From cache";
        }

        logger.LogWarning("Cache does not have the entry, Getting from external method at " 
                                                                              + DateTime.Now);

        var apiResponse = await GetDataFromRestAPI();

        // Save data in cache.
        var cacheEntryOption = new MemoryCacheEntryOptions() { 
                                          AbsoluteExpirationRelativeToNow = TimeSpan.FromSeconds(10) };
        cacheEntryOption.RegisterPostEvictionCallback(callback: EvictionCallbackAsync, state: this);
        _cache.Set(CacheKey, apiResponse, cacheEntryOption);
        logger.LogWarning("New value from API call set to cache : " + apiResponse + ", at " + DateTime.Now);

        return apiResponse.ToString() + " - after reloading cache";
    }
                        
    private async Task<DateTime> GetDataFromRestAPI()
    {
        await Task.Delay(3000);
        return DateTime.Now;
    }
    private static async void EvictionCallbackAsync(object key, object value, EvictionReason reason, object state)
    {
        var _this = ((HomeController)state);
        _this.logger.LogWarning("Inside EvictionCallback  at " + DateTime.Now);
        var apiResponse =   await _this.GetDataFromRestAPI();

        var cacheEntryOption = new MemoryCacheEntryOptions() { 
                                              AbsoluteExpirationRelativeToNow = System.TimeSpan.FromSeconds(10) };
        _this._cache.Set(CacheKey, apiResponse, cacheEntryOption);
        _this.logger.LogWarning("New value set to cache inside EvictionCallback: " +
                                                   apiResponse + ", at " + DateTime.Now);

    }
My cache duration in 10 seconds and the dummy GetDataFromRestAPI has a 3 seconds simulated delay.

Now I have 3 incoming requests coming at the same time (as the first requests after the app started), So I get the below log messages in my debug output window.

```
Cache does not have the entry, Getting from external method at 1/15/2019 4:39:53 PM
Cache does not have the entry, Getting from external method at 1/15/2019 4:39:54 PM
Cache does not have the entry, Getting from external method at 1/15/2019 4:39:54 PM
New value from API call set to cache : 1/15/2019 4:39:56 PM, at 1/15/2019 4:39:56 PM
New value from API call set to cache : 1/15/2019 4:39:57 PM, at 1/15/2019 4:39:57 PM
Inside EvictionCallback  at 1/15/2019 4:39:57 PM
New value from API call set to cache : 1/15/2019 4:39:57 PM, at 1/15/2019 4:39:57 PM
Inside EvictionCallback  at 1/15/2019 4:39:57 PM
New value set to cache inside EvictionCallback: 1/15/2019 4:40:00 PM, at 1/15/2019 4:40:00 PM
Inside EvictionCallback  at 1/15/2019 4:40:00 PM
New value set to cache inside EvictionCallback: 1/15/2019 4:40:00 PM, at 1/15/2019 4:40:00 PM
New value set to cache inside EvictionCallback: 1/15/2019 4:40:03 PM, at 1/15/2019 4:40:03 PM
```

### Expected behavior
Why do I see the `EvictionCallback` getting executed twice here ? all the three requests were issued at the same time. I would imagine the `EvictionCallback` to execute in  the next call (10 seconds later from these 3 calls).

When I wait for more than 10 seconds (so that cache item expires) and make again 3 more calls, I get the below output.

```
Cache does not have the entry, Getting from external method at 1/15/2019 4:41:39 PM
Cache does not have the entry, Getting from external method at 1/15/2019 4:41:39 PM
Cache does not have the entry, Getting from external method at 1/15/2019 4:41:39 PM
New value from API call set to cache : 1/15/2019 4:41:42 PM, at 1/15/2019 4:41:42 PM
New value from API call set to cache : 1/15/2019 4:41:42 PM, at 1/15/2019 4:41:42 PM
Inside EvictionCallback  at 1/15/2019 4:41:42 PM
New value from API call set to cache : 1/15/2019 4:41:42 PM, at 1/15/2019 4:41:42 PM
Inside EvictionCallback  at 1/15/2019 4:41:42 PM
New value set to cache inside EvictionCallback: 1/15/2019 4:41:45 PM, at 1/15/2019 4:41:45 PM
Inside EvictionCallback  at 1/15/2019 4:41:45 PM
New value set to cache inside EvictionCallback: 1/15/2019 4:41:45 PM, at 1/15/2019 4:41:45 PM

```
The interesting thing here is, With my above code, It executes both my cache eviction callback code and the snippet when cache does not have an entry. How do we synchronize the code execution from both snippets so that it executes either one.  I feel that the PostEvictionCallback is unnecessary here.  If I am getting 1000 requests at the same time, It will spin up 1000 threads and execute the same code. correct ? (Actually 1000+1000 = 2000 with my above code)
 Why would one use this method (`RegisterPostEvictionCallback`) ?  Perhaps I am not correctly understanding the proper usage/use case for this API.

**Comment by mderriey** [comment]
Maybe `EvictionCallbackAsync` is invoked either after expiry or update of an existing value.

Here's how I interpret the logs you've posted:

 - `L1-L3` - 3 requests arrive pretty much at the same time, none of them finds a value in the cache, so each of them issues a new HTTP request to get the data from the REST API;
 - `L4` - one of the 3 HTTP requests issued before completes, and the result is put in the cache;
 - `L5` - one of the remaining 2 HTTP requests completes, and the result is put in the cache, effectively overwriting the previous value;
 - `L6` - the result of the previous operation (overwriting an existing value in the cache) triggers the `EvictionCallbackAsync` callback to be invoked, itself issuing a new HTTP request

So you're basically in a loop where after overwriting an existing value, you're fetching an _updated_ value with an HTTP request, and overwriting the new value with that.

I'd suggest you play with the `reason` parameter in the `EvictionCallbackAsync` callback to determine when it's required to fetch a new value. By the sounds of it, you only want to do this when a value expires. See the [`EvictionReason`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.memory.evictionreason?view=aspnetcore-2.2) enum in the docs for possible values.

**Comment by kshyju** [comment]
Thanks @mderriey , You made a good point!. The eviction reason is `Replaced`. So I think what you said is correct.  The updating of the cache value is calling EvictionCallback even though i am still in the window of 10 seconds (cache duration).

**Comment by mderriey** [comment]
@kshyju You might want to do some logging when entries are evicted from the cache, for example. This could help troubleshooting if you experience strange behaviours related to the cache.
