### ISSUE TITLE
StringValues: Inconsistent hashcode for single-valued instances depending on construction

### ISSUE THREAD

**Issue by acolomba** [aspnet/Extensions#953]
### Describe the bug

Two ```StringValues``` instances initialized in different ways with the same _single_ value may or may not produce the same hashcode depending on the actual value they hold. 

Or, given a fixed string value, they may produce the same or different hashcodes across different .NET runtime executions.

### To Reproduce

1. .NET Core 2.1.503, Microsoft.Extensions.Primitive 2.1.1

2. Run this unit test repeatedly.

```
var sv1 = new StringValues("value");
var sv2 = new StringValues(new [] { "value" });

Assert.Equal(sv1.GetHashCode(), sv2.GetHashCode());
```

The assertion will sporadically fail.

### Expected behavior

The assertion should succeed consistently.

```StringValues.Equals``` is always true for the many forms of ```sv1.Equals(sv2)```,  so right now we sometimes end up with equal instances with different hashcodes, breaking the contract between ```.Equals``` and ```.GetHashCode```.

### Root cause

For single-valued instances, ```StringValues.GetHashCode``` calculates the hashcode differently according to the internal representation:

* ```sv1.GetHashCode()``` returns the hashcode of the one string value stored in the ```_value``` internal field.
    * result: ```"value".GetHashCode()```

* ```sv2.GetHashCode()``` uses a ```HashCodeCombiner``` for the one value stored in the first element of the internal ```_values``` array field. The combiner accumulates hashcodes into a long, and then returns the hashcode of that long.
    * result: ```((long)"value".GetHashCode()).GetHashCode()```

Now, the hashcode of a long is:

```
(unchecked((int)((long)m_value)) ^ (int)(m_value >> 32))
```

This returns m_value if m_value is > 0 so the double ```.GetHashCode()``` above is ok when ```"value".GetHashCode()``` is in that range, and the two hashcodes will be the same. But a negative ```"value".GetHashCode()``` ends up producing a different value altogether.

In other words, two ```StringValues``` instances initialized in different ways with the same single value may or may not produce the same hashcode depending on whether the hashcode of the value they hold, by virtue of being negative, ends up setting the sign bit of a long.

Also, because hashcodes are seeded differently at every .NET runtime execution, across different runs ```StringValues``` hashcodes that were equal in one run won't be in another run.

### Suggested fix

This can be fixed in several ways, but I think the fix that meshes best with the style of this code would be to go from:

```
        public override int GetHashCode()
        {
            if (_values == null)
            {
                return _value == null ? 0 : _value.GetHashCode();
            }
```

to:

```
        public override int GetHashCode()
        {
            if (this.Count == 1)
            {
                return this[0].GetHashCode();
            }
```

I'm available to do a pull request incl. unit test.

### Additional context
```dotnet --info``` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.503
 Commit:    4c506e0f35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.503\

Host (useful for support):
  Version: 2.1.7
  Commit:  cca5d72d48

.NET Core SDKs installed:
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

Edits: clarifications on which hashcode values produce this bug.

**Comment by anurse** [comment]
We should make sure that `StringValues` with a single element array should be special-cased in `GetHashCode` and have it generate the same kind of hash code as it would if it was a single string.

**Comment by gfoidl** [comment]
@anurse  just stumbled accross this issue.
Since https://github.com/aspnet/Extensions/pull/2062 got merged, this issue could be closed.

**Comment by anurse** [comment]
Oops! Good catch @gfoidl, thanks!
