### ISSUE TITLE
ILoggingBuilder.AddConfiguration is not needed to pickup minimum logging level from appsettings.json ? 

### ISSUE THREAD

**Issue by kshyju** [aspnet/Extensions#958]
I have a simple 2.2 web app where I am setting up the Console and Debug loggers. In my `appsettings.json` file, I have specified Default log level as "Warning". But I have not called the `logging.AddConfiguration` method .  I see the loggers are picking up the minimum log level(Warning) I mentioned in the appsettings file.

My Program.cs

    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
            .ConfigureLogging((hostingContext, logging) =>
            {
                logging.AddConsole();
                logging.AddDebug();
            })
            .UseStartup<Startup>();
    }
appsettings.json

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Warning"
    }
  }
}
```
Logging code

    this.logger.LogTrace("Trace at " + DateTime.Now);
    this.logger.LogDebug("Debug at " + DateTime.Now);
    this.logger.LogInformation("Info at " + DateTime.Now);
    this.logger.LogWarning("Warning at " + DateTime.Now);
    this.logger.LogError("Error at " + DateTime.Now);
    this.logger.LogCritical("Critical at " + DateTime.Now);

Output

```
Core22.Controllers.HomeController:Warning: Warning at 1/16/2019 6:39:54 PM
Core22.Controllers.HomeController:Error: Error at 1/16/2019 6:39:54 PM
Core22.Controllers.HomeController:Critical: Critical at 1/16/2019 6:39:54 PM
```

By following the [log filtering](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2#log-filtering) section in the documentation, I was under the impression that `logging.AddConfiguration(hostingContext.Configuration.GetSection("Logging"))` is needed for the logger to use the configuration specified in the `Logging` section of the appsettings. Is that not the case ? Is it working by a convention ? Could not find any documentation stating that.

**Comment by pakrym** [comment]
WebHost.CreateDefaultBuilder does this for you by default : https://github.com/aspnet/AspNetCore/blob/9c017cd8054a55a2102369c3d526383d664c07ad/src/DefaultBuilder/src/WebHost.cs#L186
