### ISSUE TITLE
AddHostedService won't fail on regression to #552

### ISSUE THREAD

**Issue by daniel-v** [aspnet/Extensions#962]
### Describe the bug
Looking through the changes in #552 , the test to cover the change `HostedServiceRegisteredAsSingletons` won't fail if `AddHostedService` is changed from `AddSingleton` back to `AddTransient` eg.

### Expected behavior
`HostedServiceRegisteredAsSingletons` test to fail if hosted services are not registered as singletons via `AddHostedService`

**Comment by pakrym** [comment]
Did you try running the test with AddTransient? 

https://github.com/aspnet/Extensions/pull/552/files#diff-d67d75dcff2fcb22cd9d5a2208d17eaaR177

Would fail because `.GetService` would return a new instance of hosted service.

**Comment by anurse** [comment]
As @pakrym said, we don't believe this is the case. If you can provide an example that shows that no test fails when the lifetime of that service is changed, let us know and we can investigate further.
