### ISSUE TITLE
Documentation: IHostLifetime.StopAsync

### ISSUE THREAD

**Issue by ygoe** [aspnet/Extensions#990]
This issue is meant to go to this page, but unfortunately the Docs to GitHub connection is not there anymore (although now I probably have some "tech profile" I don't know what it's good for):

https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostlifetime.stopasync?view=aspnetcore-2.1

Since the documentation probably comes from the code, this place seems appropriate anyway.

The wording "and clean up resources" sounds like wrong grammar. What does it refer to?

**Comment by muratg** [comment]
Done.
