### ISSUE TITLE
Cannot get the same ILoggerFactory from the services.BuildServiceProvider.GetService

### ISSUE THREAD

**Issue by kevinlo** [aspnet/Extensions#994]
I am not sure if I should post on Hosting or Extensions.  I start from Hosting.

My app uses Log4Net so I need to call loggerFactory.AddLog4Net() to log to a log file.

I have read these threads:

[https://github.com/aspnet/Logging/issues/361](https://github.com/aspnet/Logging/issues/361)
[https://github.com/aspnet/Hosting/issues/1150](https://github.com/aspnet/Hosting/issues/1150)

I have called the loggerFactory.AddLog4Net at both Startup constructor and in the Configure function call.

However, in the ConfigureServices, I need to Add a IXmlRepository singleton and then uses it for the AddDataProtection call.   I call the services.BuildServiceProvider().GetService<IXmlRepository>() to generate that Singleton IXmlRepository.
```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton<IXmlRepository, MyXmlRepository>();

            services.AddDataProtection()
                .AddKeyManagementOptions(options =>
                {
                    options.XmlRepository = services.BuildServiceProvider().GetService<IXmlRepository>();

                })
                .ProtectKeysWithCertificate(_certificate)
                .SetApplicationName(APP_NAME);
        }
```

The MyXmlRepository keeps a ILogger member for logging.

```
        public MyXmlRepository(ILogger<MyXmlRepository> logger)
        {
            _logger = logger;
        }

```

I notice the logging inside MyXmlRepository are not logged to the file.  But I run the app in console, the console logging has it.    When I debug it, I can only see the Console and Debug logger from the ILogger injected into the MyXmlRepository ctor, it does not have the Log4Net one.   I think I need to call the loggerFactory.AddLog4Net before the GetService<IXmlRepository>.

I call the services.BuildServiceProvider() and koggerFactory.AddLog4Net() inside the AddKeyManagementOptions:

```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton<IXmlRepository, MyXmlRepository>();

            services.AddDataProtection()
                .AddKeyManagementOptions(options =>
                {
                    ServiceProvider sp = services.BuildServiceProvider();
                    
                    ILoggerFactory loggerFactory = sp.GetService<ILoggerFactory>();
                    if (loggerFactory != null)
                    {
                        loggerFactory.AddLog4Net();
                    }
.
                    options.XmlRepository = sp.GetService<IXmlRepository>();

                })
                .ProtectKeysWithCertificate(_certificate)
                .SetApplicationName(APP_NAME);
        }
```

After, it works fine and I can see the log4Net logger is available from the ILogger injected.

Later on, I need the log something before that AddSingleton and AddDataProtection, so I move the loggerFactory.AddLog4Net() at the beginning of the ConfigureServices function.

```
        public void ConfigureServices(IServiceCollection services)
        {
            ServiceProvider sp = services.BuildServiceProvider();
            
            ILoggerFactory loggerFactory = sp.GetService<ILoggerFactory>();
            if (loggerFactory != null)
            {
                loggerFactory.AddLog4Net();
                
                _logger = loggerFactory.CreateLogger(this.GetType().FullName);
            }

            _logger.LogDebug("Testing");

            services.AddSingleton<IXmlRepository, MyXmlRepository>();

            services.AddDataProtection()
                .AddKeyManagementOptions(options =>
                {
                    ServiceProvider sp = services.BuildServiceProvider();
.
                    options.XmlRepository = sp.GetService<IXmlRepository>();

                })
                .ProtectKeysWithCertificate(_certificate)
                .SetApplicationName(APP_NAME);
        }
```

After that, the Log4Net is not available in the ILogger injected into the MyXmlRepository.

I need to call the services.BuildServiceProvider at the beginning to call the AddLog4Net and set the _logger.     I need to call the services.BuildServiceProvider again in the AddKeyManagementOptions so it can create the IXmlRepository singleton.

I read [https://github.com/aspnet/DependencyInjection/issues/595#issuecomment-338059457](https://github.com/aspnet/DependencyInjection/issues/595#issuecomment-338059457) saying 

> calling BuildServiceProvider creates a new ServiceProvider every time, singletons are scoped to service provider

Then I try calling services.BuildServiceProvider at different place inside the ConfigureServices function like the followings
```

            ServiceProvider serviceProvider1 = services.BuildServiceProvider();
            ILoggerFactory loggerFactory1 = serviceProvider.GetService<ILoggerFactory>();

            ServiceProvider serviceProvider2 = services.BuildServiceProvider();
            ILoggerFactory loggerFactory2 = serviceProvider.GetService<ILoggerFactory>();

            ServiceProvider serviceProvider3 = services.BuildServiceProvider();
            ILoggerFactory loggerFactory3 = serviceProvider.GetService<ILoggerFactory>();

```

I use Visual Studio to debug it and Make Object ID to the loggerFactory1, loggerFactory2 and loggerFactory3.   It shows they are the same instance even they are created from different instances of serviceProvider1, serviceProvider2 and serviceProvider3.

So, it looks like the ILoggerFactory is the same throughout the ConfigureService function, but the one created in the AddKeyManagementOptions call back.   Why is that?   The BuildServiceProvider is called from the same services.

**Comment by glennc** [comment]
In general you shouldn't be calling BuildServiceProvider, it is rarely going to give you what you want.

If you need the same instance of the XMLRepository to be used both in ConfigureServices and elsewhere in your application then I would create an instance yourself in configure services, register in services, and then set it on your options class.

something like:

```csharp
var repo = new MyXmlRepository();

services.AddSingleton<IXmlRepository>(repo);
services.AddDataProtection()
            .AddKeyManagementOptions(options => options.XmlRepository repo);
```

Whenever you call BuildServiceProvider you are, conceptually, creating a whole new set of singletons that only work for the specific service provider you just built. It's completely unrelated to the other service provider that will by used by the rest of the application.

However, this whole thing seems strange. @blowdart @Tratcher can one of you tell me if data protection can just resolve an IXmlRepository from DI instead of having it set like what's being shown here?

**Comment by kevinlo** [comment]
@glennc  Thanks for your reply.   If that MyXmlRepository does not take any parameters in the constructor, that will work.  But the MyXmlRepository will have other injections like IOption, ILogger, ISomethingProvider.    I need to build up the dependency tree and create all those instance myself.

**Comment by Tratcher** [comment]
You could do this with IPhostConfigureOptions:
https://github.com/aspnet/AspNetCore/blob/9251dfe7c09f04c6a17dc8e5b96817031730c301/src/Security/Authentication/Cookies/src/PostConfigureCookieAuthenticationOptions.cs#L13-L29

There's also this approach:
https://github.com/aspnet/AspNetCore/blob/416d8cd1ea098eb643b4258247af3448f5545c32/src/DataProtection/DataProtection/src/DataProtectionBuilderExtensions.cs#L268-L275

**Comment by kevinlo** [comment]
@Tratcher .  Sorry, I don't get what you mean.  The first example you gave is for CookieAuthenticationOptions.  But I don't see the [KeyManagementOptions](https://github.com/aspnet/DataProtection/blob/master/src/Microsoft.AspNetCore.DataProtection/KeyManagement/KeyManagementOptions.cs) has the similar PostConfigure function.

I think @glennc question is if the IXmlRepository is added to the IServiceCollection by the following line

`services.AddSingleton<IXmlRepository, MyXmlRepository>();`

DataProtection will get this from the DI.   But I don't see the codes from your second example doing it.  That codes get the ILoggerFactory from DI, but I don't see it getting the IXmlRepository and set it.

Am I misunderstanding what you guys mean?

**Comment by Tratcher** [comment]
I was giving examples of how a property could be set from DI that wasn't normally. I.e. you could register your own PostConfigure, or in the second example you could call `GetService<IXmlRepository>()` just like is done for the logger.

**Comment by Tratcher** [comment]
I didn't see anywhere that DataProtection would resolve IXmlRepository from DI.

**Comment by kevinlo** [comment]
@Tratcher.  The following is what I am trying to do to call the GetService<IXmlRepository>().  But inside the AddKeyManagementOptions called in the ConfigureServices, the only way I can get the ServiceProvider is I call the services.BuildServiceProvider, but Glennc says I should not call it.

```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton<IXmlRepository, MyXmlRepository>();

            services.AddDataProtection()
                .AddKeyManagementOptions(options =>
                {
                    ServiceProvider sp = services.BuildServiceProvider();
                    
                    options.XmlRepository = sp.GetService<IXmlRepository>();

                })
                .ProtectKeysWithCertificate(_certificate)
                .SetApplicationName(APP_NAME);
        }
```

Do you know how I can get the ServiceProvider inside the ConfigServices without calling the BuildServiceProvider?

**Comment by Tratcher** [comment]
You can't get the ServiceProvider directly in ConfigureServices, only in callbacks like those examples showed.

**Comment by kevinlo** [comment]
@Tratcher, the PostConfigure function does not provide the ServiceProvider, where can it get the ServiceProvider inside the PostConfigure call?

```
    //
    // Summary:
    //     Represents something that configures the TOptions type. Note: These are run after
    //     all Microsoft.Extensions.Options.IConfigureOptions`1.
    //
    // Type parameters:
    //   TOptions:
    public interface IPostConfigureOptions<in TOptions> where TOptions : class
    {
        //
        // Summary:
        //     Invoked to configure a TOptions instance.
        //
        // Parameters:
        //   name:
        //     The name of the options instance being configured.
        //
        //   options:
        //     The options instance to configured.
        void PostConfigure(string name, TOptions options);
    }
```
Why doesn't the Data Protection provide a simple way to set the options.XmlRepository from DI?  

All PersistKeysToFileSystem, PersistKeysToRegistry, PersistKeysToRedis and PersistKeystoAzureBlobStorageInternal create the XmlRepository by new.   

Could you please show how to use the examples you shown to get the ServiceProvider to GetService<IXmlRepository>() and set it to the options.XmlRepository.   I really can't find a clean way.

**Comment by Tratcher** [comment]
If you're going to use IPostConfigureOptions then you inject the DI dependencies (IXmlRepository) into the constructor of your implementation like the PostConfigureCookieAuthenticationOptions example did with IDataProtectionProvider.

**Comment by kevinlo** [comment]
@Tratcher, you mean instead of calling the AddKeyManagementOptions, use the IPostConfigureOptions<KeyManagementOptions> to set the options.XmlRepository like this:

```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton<IXmlRepository, MyXmlRepository>();

            services.AddDataProtection()
                .ProtectKeysWithCertificate(_certificate)
                .SetApplicationName(APP_NAME);
                
            services.TryAddEnumerable(ServiceDescriptor.Singleton<IPostConfigureOptions<KeyManagementOptions>, PostConfigureKeyManagementOptions>());
        }            
        
        public class PostConfigureKeyManagementOptions : IPostConfigureOptions<KeyManagementOptions>
        {
            private readonly IXmlRepository _xmlRepo;

            public PostConfigureCookieAuthenticationOptions(IXmlRepository xmlRepository)
            {
                _xmlRepo = dataProtection;
            }    

            public void PostConfigure(string name, KeyManagementOptions options)
            {
                options.XmlRepository = options.XmlRepository ?? _xmlRepo;
            }            
        }   
```

Ok.  I can try.   But why doesn't the KeyManagementOptions is doing that like the CookieAuthenticationOptions out of the box as the options.XmlRepository should allow a custom one from DI?

But thanks, just learn another way to do the job.

**Comment by kevinlo** [comment]
@Tratcher.   The PostConfigureKeyManagementOptions works.  But now, I have another problem.  I use Log4Net to do logging.

As shown in the above codes, I call the loggerFactory.AddLog4Net() in the ConfigureServicesto add the Log4Net as the ILoggerProvider.
 
```
            ServiceProvider sp = services.BuildServiceProvider();
            
            ILoggerFactory loggerFactory = sp.GetService<ILoggerFactory>();
            if (loggerFactory != null)
            {
                loggerFactory.AddLog4Net();
                
                _logger = loggerFactory.CreateLogger(this.GetType().FullName);
            }

```
so that the ILogger or ILoggerFactory injected into the MyXmlRepository has the Log4Net.

I have read these two threads about the different ILoggerFactory instances used between the "HostingServices" and "ApplicationServices"

[https://github.com/aspnet/Logging/issues/361](https://github.com/aspnet/Logging/issues/361)
[https://github.com/aspnet/Hosting/issues/1150](https://github.com/aspnet/Hosting/issues/1150)

and I already call the loggerFactory.AddLog4Net() in the Configure function.
```
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddLog4Net();
            _logger = loggerFactory.CreateLogger(this.GetType().FullName);
```

But it seems the PostConfigureKeyManagementOptions  is called before the Configure and the ILogger injected into the MyXmlRepository for the PostConfigureKeyManagementOptions   does not have the Log4Net logger.

Do you think I should inject the ILoggerFactory into the PostConfigureKeyManagementOptions  and call loggerFactory.AddLog4Net() there.   I just find it ugly to call the loggerFactory.AddLog4Net() at different places.

Is the PostConfigureXXXOptions  called before Configure?   Where is the good place to call the loggerFactory.AddLog4Net().

**Comment by Tratcher** [comment]
Stop calling BuildServiceProvider, nothing good can come from it.

Setting up Log4Net in Configure should be enough.

**Comment by Tratcher** [comment]
You need a lot more help than we have resources for. I suggest taking questions like this to stackoverflow.com.

**Comment by kevinlo** [comment]
@Tratcher.   Sorry, I know I ask too much.  But I cannot find an answer from Stackoverflow

> Setting up Log4Net in Configure should be enough.

The Configure is called after the IPostConfigureOptions, setting up Log4Net there is after the MyXmlRepository is constructed and the ILogger or ILoggerFactory injected won't have the Log4Net.

**Comment by kevinlo** [comment]
I think I set up the Log4NetProvider at the wrong place.  It should do something like what the AddConsole or AddDebug do to set it using the ILoggingBuilder at the ConfigureLogging, then it does not need to call the loggerFactory.AddLog4Net at the Startup constructor or at Startup.Configure.

Thanks for your help.  I close this issue
